SPOOL 001_DMALM_AMBIENTE_TECNOLOGICO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_AMBIENTE_TECNOLOGICO 
    ( 
     DMALM_AMBIENTE_TECNOLOGICO_PK NUMBER (15)  NOT NULL , 
     DMALM_PRODOTTO_FK_01 NUMBER (15) , 
     ID_AMBIENTE_TECNOLOGICO VARCHAR2 (500 BYTE) , 
     TIPO_OGGETTO VARCHAR2 (1 BYTE) , 
     SIGLA_PRODOTTO VARCHAR2 (500 BYTE) , 
     SIGLA_MODULO VARCHAR2 (500 BYTE) , 
     NOME VARCHAR2 (500 BYTE) , 
     DS_AMBIENTE_TECNOLOGICO VARCHAR2 (4000 BYTE) , 
     VERSIONE_SO VARCHAR2 (500 BYTE) , 
     ARCHITETTURA VARCHAR2 (4000 BYTE) , 
     INFRASTRUTTURA VARCHAR2 (4000 BYTE) , 
     SISTEMA_OPERATIVO VARCHAR2 (4000 BYTE) , 
     TIPO_LAYER VARCHAR2 (4000 BYTE) , 
     DT_INIZIO_VALIDITA DATE , 
     DT_FINE_VALIDITA DATE , 
     DMALM_MODULO_FK_02 NUMBER (15) , 
     DT_INSERIMENTO_RECORD DATE , 
     DT_ANNULLAMENTO DATE , 
     ANNULLATO VARCHAR2 (2 BYTE) , 
     DMALM_AMBIENTE_TECNOLOGICO_SEQ NUMBER (15)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING 
        STORAGE ( 
        INITIAL 655360 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;                                                                                                                    
COMMENT ON TABLE DMALM_AMBIENTE_TECNOLOGICO IS 'DMALM_AMBIENTE_TECNOLOGICO        '                                        ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DMALM_AMBIENTE_TECNOLOGICO_PK IS 'DMALM_AMBIENTE_TECNOLOGICO_PK     '         ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DMALM_PRODOTTO_FK_01 IS 'DMALM_PRODOTTO_FK_01              '                  ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.ID_AMBIENTE_TECNOLOGICO IS 'ID_AMBIENTE_TECNOLOGICO           '               ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.TIPO_OGGETTO IS 'TIPO_OGGETTO                      '                          ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.SIGLA_PRODOTTO IS 'SIGLA_PRODOTTO                    '                        ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.SIGLA_MODULO IS 'SIGLA_MODULO                      '                          ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.NOME IS 'NOME                              '                                  ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DS_AMBIENTE_TECNOLOGICO IS 'DS_AMBIENTE_TECNOLOGICO           '               ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.VERSIONE_SO IS 'VERSIONE_SO                       '                           ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.ARCHITETTURA IS 'ARCHITETTURA                      '                          ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.INFRASTRUTTURA IS 'INFRASTRUTTURA                    '                        ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.SISTEMA_OPERATIVO IS 'SISTEMA_OPERATIVO                 '                     ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.TIPO_LAYER IS 'TIPO_LAYER                        '                            ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '                    ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '                      ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DMALM_MODULO_FK_02 IS 'DMALM_MODULO_FK_02                '                    ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DT_INSERIMENTO_RECORD IS 'DT_INSERIMENTO_RECORD             '                 ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DT_ANNULLAMENTO IS 'DT_ANNULLAMENTO                   '                       ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.ANNULLATO IS 'ANNULLATO                         '                             ;
COMMENT ON COLUMN DMALM_AMBIENTE_TECNOLOGICO.DMALM_AMBIENTE_TECNOLOGICO_SEQ IS 'DMALM_AMBIENTE_TECNOLOGICO_SEQ    '        ;
CREATE UNIQUE INDEX DMALM_AMBTECN_PK ON DMALM_AMBIENTE_TECNOLOGICO 
    ( 
     DMALM_AMBIENTE_TECNOLOGICO_SEQ ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING ;
CREATE INDEX DMALM_AMBIENTE_IDX_1 ON DMALM_AMBIENTE_TECNOLOGICO 
    ( 
     DT_FINE_VALIDITA ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING ;
CREATE UNIQUE INDEX AMBIENTE_TECNOLOGICO_UK_01 ON DMALM_AMBIENTE_TECNOLOGICO 
    ( 
     DMALM_PRODOTTO_FK_01 ASC , 
     DMALM_MODULO_FK_02 ASC , 
     ID_AMBIENTE_TECNOLOGICO ASC , 
     SIGLA_PRODOTTO ASC , 
     SIGLA_MODULO ASC , 
     DMALM_AMBIENTE_TECNOLOGICO_PK ASC , 
     DT_INIZIO_VALIDITA ASC , 
     DT_INSERIMENTO_RECORD ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 131072 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING ;
ALTER TABLE DMALM_AMBIENTE_TECNOLOGICO 
    ADD CONSTRAINT DMALM_AMBTECN_PK PRIMARY KEY ( DMALM_AMBIENTE_TECNOLOGICO_SEQ ) 
    USING INDEX DMALM_AMBTECN_PK ;
ALTER TABLE DMALM_AMBIENTE_TECNOLOGICO 
    ADD CONSTRAINT AMBIENTE_TECNOLOGICO_UK_01 UNIQUE ( DMALM_PRODOTTO_FK_01 , DMALM_MODULO_FK_02 , ID_AMBIENTE_TECNOLOGICO , SIGLA_PRODOTTO , SIGLA_MODULO , DMALM_AMBIENTE_TECNOLOGICO_PK , DT_INIZIO_VALIDITA , DT_INSERIMENTO_RECORD ) 
    USING INDEX AMBIENTE_TECNOLOGICO_UK_01 ;
SPOOL OFF;
