SPOOL 008_DMALM_ATTACHMENT.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_ATTACHMENT 
    ( 
     CD_ATTACHMENT VARCHAR2 (300 BYTE) , 
     STATO_CANCELLATO NUMBER (1) , 
     NOME_AUTORE VARCHAR2 (50 BYTE) , 
     NOME_FILE VARCHAR2 (500 BYTE) , 
     DIMENSIONE_FILE NUMBER (15) , 
     ID_PROJECT VARCHAR2 (50 BYTE) , 
     TITOLO VARCHAR2 (500 BYTE) , 
     DT_MODIFICA_ATTACHMENT TIMESTAMP , 
     URL VARCHAR2 (1000 BYTE) , 
     DMALM_FK_WORKITEM_01 NUMBER (15) , 
     DMALM_WORKITEM_TYPE VARCHAR2 (50 BYTE) , 
     DT_CARICAMENTO TIMESTAMP , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     ATTACHMENT_PK NUMBER (15)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 14680064 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_ATTACHMENT IS 'DMALM_ATTACHMENT                  ';
COMMENT ON COLUMN DMALM_ATTACHMENT.CD_ATTACHMENT IS 'CD_ATTACHMENT                     '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.STATO_CANCELLATO IS 'STATO_CANCELLATO                  '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.NOME_AUTORE IS 'NOME_AUTORE                       '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.NOME_FILE IS 'NOME_FILE                         '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.DIMENSIONE_FILE IS 'DIMENSIONE_FILE                   '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.ID_PROJECT IS 'ID_PROJECT                        '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.TITOLO IS 'TITOLO                            '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.DT_MODIFICA_ATTACHMENT IS 'DT_MODIFICA_ATTACHMENT            '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.URL IS 'URL                               '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.DMALM_FK_WORKITEM_01 IS 'DMALM_FK_WORKITEM_01              '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.DMALM_WORKITEM_TYPE IS 'DMALM_WORKITEM_TYPE               '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.DT_CARICAMENTO IS 'DT_CARICAMENTO                    '; 
COMMENT ON COLUMN DMALM_ATTACHMENT.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
CREATE UNIQUE INDEX PK_DMALM_ATTACHMENT ON DMALM_ATTACHMENT 
    ( 
     ATTACHMENT_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_ATTACHMENT 
    ADD CONSTRAINT PK_DMALM_ATTACHMENT PRIMARY KEY ( ATTACHMENT_PK ) 
    USING INDEX PK_DMALM_ATTACHMENT ;
SPOOL OFF;
