SPOOL 013_DMALM_DIFETTO_PRODOTTO_ODS.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_DIFETTO_PRODOTTO_ODS 
    ( 
     IDENTIFICATIVO_REPOSITORY VARCHAR2 (20 BYTE) , 
     IDENTIFICATIVO_DIFETTO VARCHAR2 (100 BYTE) , 
     DATA_RISOLUZIONE_DIFETTO TIMESTAMP , 
     DATA_CREAZIONE_DIFETTO TIMESTAMP , 
     DATA_MODIFICA_RECORD TIMESTAMP , 
     DATA_CHIUSURA_DIFETTO TIMESTAMP , 
     DATA_CAMBIO_STATO TIMESTAMP , 
     USERID_AUTORE_DIFETTO VARCHAR2 (100 BYTE) , 
     NOME_AUTORE_DIFETTO VARCHAR2 (100 BYTE) , 
     MOTIVO_RISOLUZIONE VARCHAR2 (255 BYTE) , 
     SEVERITY_DIFETTO VARCHAR2 (10 BYTE) , 
     DESCRIZIONE_DIFETTO VARCHAR2 (4000 BYTE) , 
     DATA_CARICAMENTO TIMESTAMP , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (15) , 
     DMALM_TEMPO_FK_04 NUMBER (15) , 
     DT_STORICIZZAZIONE TIMESTAMP , 
     PROVENIENZA_DIFETTO VARCHAR2 (2 BYTE) , 
     RANK_STATO_DIFETTO NUMBER (2) , 
     CODICE_AREA_ORESTE VARCHAR2 (200 BYTE) , 
     DMALM_DIFETTO_PRODOTTO_PK NUMBER (15)  NOT NULL , 
     GIORNI_FESTIVI NUMBER (5) , 
     TEMPO_TOTALE_RISOLUZIONE NUMBER (8) , 
     NUMERO_LINEA_RDI VARCHAR2 (3 BYTE) , 
     NUMERO_TESTATA_RDI VARCHAR2 (50 BYTE) , 
     ID_PROJECT VARCHAR2 (100 BYTE) , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     NATURA_DIFETTO VARCHAR2 (100 BYTE) , 
     CAUSA_DIFETTO VARCHAR2 (100 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 20971520 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_DIFETTO_PRODOTTO_ODS IS 'DMALM_DIFETTO_PRODOTTO_ODS        ';
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.IDENTIFICATIVO_REPOSITORY IS 'IDENTIFICATIVO_REPOSITORY         '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.IDENTIFICATIVO_DIFETTO IS 'IDENTIFICATIVO_DIFETTO            '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_RISOLUZIONE_DIFETTO IS 'DATA_RISOLUZIONE_DIFETTO          '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_CREAZIONE_DIFETTO IS 'DATA_CREAZIONE_DIFETTO            '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_MODIFICA_RECORD IS 'DATA_MODIFICA_RECORD              '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_CHIUSURA_DIFETTO IS 'DATA_CHIUSURA_DIFETTO             '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_CAMBIO_STATO IS 'DATA_CAMBIO_STATO                 '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.USERID_AUTORE_DIFETTO IS 'USERID_AUTORE_DIFETTO             '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.NOME_AUTORE_DIFETTO IS 'NOME_AUTORE_DIFETTO               '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.MOTIVO_RISOLUZIONE IS 'MOTIVO_RISOLUZIONE                '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.SEVERITY_DIFETTO IS 'SEVERITY_DIFETTO                  '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DESCRIZIONE_DIFETTO IS 'DESCRIZIONE_DIFETTO               '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.PROVENIENZA_DIFETTO IS 'PROVENIENZA_DIFETTO               '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.RANK_STATO_DIFETTO IS 'RANK_STATO_DIFETTO                '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.CODICE_AREA_ORESTE IS 'CODICE_AREA_ORESTE                '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_DIFETTO_PRODOTTO_PK IS 'DMALM_DIFETTO_PRODOTTO_PK         '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.GIORNI_FESTIVI IS 'GIORNI_FESTIVI                    '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.TEMPO_TOTALE_RISOLUZIONE IS 'TEMPO_TOTALE_RISOLUZIONE          '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.NUMERO_LINEA_RDI IS 'NUMERO_LINEA_RDI                  '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.NUMERO_TESTATA_RDI IS 'NUMERO_TESTATA_RDI                '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.ID_PROJECT IS 'ID_PROJECT                        '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.NATURA_DIFETTO IS 'NATURA_DIFETTO                    '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.CAUSA_DIFETTO IS 'CAUSA_DIFETTO                     '; 
COMMENT ON COLUMN DMALM_DIFETTO_PRODOTTO_ODS.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX PK_DMALM_DIFETTO_PRODOTTO_ODS ON DMALM_DIFETTO_PRODOTTO_ODS 
    ( 
     DMALM_DIFETTO_PRODOTTO_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_DIFETTO_PRODOTTO_ODS 
    ADD CONSTRAINT PK_DMALM_DIFETTO_PRODOTTO_ODS PRIMARY KEY ( DMALM_DIFETTO_PRODOTTO_PK ) 
    USING INDEX PK_DMALM_DIFETTO_PRODOTTO_ODS ;
;
;
;
;
SPOOL OFF;
