SPOOL 017_DMALM_ESITI_CARICAMENTI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_ESITI_CARICAMENTI 
    ( 
     DATA_CARICAMENTO TIMESTAMP  NOT NULL , 
     ENTITA_TARGET VARCHAR2 (50 BYTE)  NOT NULL , 
     STATO_ESECUZIONE VARCHAR2 (50 BYTE) , 
     DT_INIZIO_CARICAMENTO TIMESTAMP , 
     DT_FINE_CARICAMENTO TIMESTAMP , 
     RIGHE_CARICATE NUMBER (8) , 
     RIGHE_MODIFICATE NUMBER (8) , 
     RIGHE_ERRATE NUMBER (8) , 
     RIGHE_SCARTATE NUMBER (8) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 131072 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_ESITI_CARICAMENTI IS 'DMALM_ESITI_CARICAMENTI           ';
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.ENTITA_TARGET IS 'ENTITA_TARGET                     '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.STATO_ESECUZIONE IS 'STATO_ESECUZIONE                  '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.DT_INIZIO_CARICAMENTO IS 'DT_INIZIO_CARICAMENTO             '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.DT_FINE_CARICAMENTO IS 'DT_FINE_CARICAMENTO               '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.RIGHE_CARICATE IS 'RIGHE_CARICATE                    '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.RIGHE_MODIFICATE IS 'RIGHE_MODIFICATE                  '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.RIGHE_ERRATE IS 'RIGHE_ERRATE                      '; 
COMMENT ON COLUMN DMALM_ESITI_CARICAMENTI.RIGHE_SCARTATE IS 'RIGHE_SCARTATE                    '; 
CREATE UNIQUE INDEX DMALM_ESITI_CARICAMENTI_PK ON DMALM_ESITI_CARICAMENTI 
    ( 
     DATA_CARICAMENTO ASC , 
     ENTITA_TARGET ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_ESITI_CARICAMENTI 
    ADD CONSTRAINT DMALM_ESITI_CARICAMENTI_PK PRIMARY KEY ( DATA_CARICAMENTO, ENTITA_TARGET ) 
    USING INDEX DMALM_ESITI_CARICAMENTI_PK ;
SPOOL OFF;
