SPOOL 039_DMALM_PROGETTO_SVILUPPO_SVIL.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ( 
     CD_PROG_SVIL_S VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_PROG_SVIL_S DATE , 
     DT_RISOLUZIONE_PROG_SVIL_S DATE , 
     DT_MODIFICA_PROG_SVIL_S DATE , 
     DT_CAMBIO_STATO_PROG_SVIL_S DATE , 
     MOTIVO_RISOLUZIONE_PROG_SVIL_S VARCHAR2 (255 BYTE) , 
     ID_AUTORE_PROG_SVIL_S VARCHAR2 (100 BYTE) , 
     DS_AUTORE_PROG_SVIL_S VARCHAR2 (100 BYTE) , 
     DT_SCADENZA_PROG_SVIL_S DATE , 
     TITOLO_PROG_SVIL_S VARCHAR2 (4000 BYTE) , 
     DMALM_PROG_SVIL_S_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (16) , 
     DMALM_TEMPO_FK_04 NUMBER (15) DEFAULT 0 , 
     RANK_STATO_PROG_SVIL_S NUMBER , 
     DT_CARICAMENTO_PROG_SVIL_S DATE , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE DATE , 
     RANK_STATO_PROG_SVIL_S_MESE NUMBER (5) DEFAULT 0 , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) DEFAULT 0 , 
     NUMERO_TESTATA VARCHAR2 (200 BYTE) , 
     NUMERO_LINEA VARCHAR2 (200 BYTE) , 
     CODICE VARCHAR2 (200 BYTE) , 
     FORNITURA VARCHAR2 (80 BYTE) , 
     DATA_INIZIO TIMESTAMP , 
     DATA_INIZIO_EFF TIMESTAMP , 
     DATA_CHIUSURA_PROG_SVIL_S TIMESTAMP , 
     DATA_DISPONIBILITA_PIANIFICATA TIMESTAMP , 
     DATA_DISPONIBILITA_EFFETTIVA TIMESTAMP , 
     DURATA_EFFETTIVA_PROG_SVIL_S NUMBER (5) , 
     DESCRIZIONE_PROG_SVIL_S CLOB , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) DEFAULT 0 
    ) 
        TABLESPACE "TS_ALM_SV"; 
COMMENT ON TABLE DMALM_PROGETTO_SVILUPPO_SVIL IS 'DMALM_PROGETTO_SVILUPPO_SVIL      ';
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.CD_PROG_SVIL_S IS 'CD_PROG_SVIL_S                    '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_CREAZIONE_PROG_SVIL_S IS 'DT_CREAZIONE_PROG_SVIL_S          '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_RISOLUZIONE_PROG_SVIL_S IS 'DT_RISOLUZIONE_PROG_SVIL_S        '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_MODIFICA_PROG_SVIL_S IS 'DT_MODIFICA_PROG_SVIL_S           '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_CAMBIO_STATO_PROG_SVIL_S IS 'DT_CAMBIO_STATO_PROG_SVIL_S       '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.MOTIVO_RISOLUZIONE_PROG_SVIL_S IS 'MOTIVO_RISOLUZIONE_PROG_SVIL_S    '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.ID_AUTORE_PROG_SVIL_S IS 'ID_AUTORE_PROG_SVIL_S             '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DS_AUTORE_PROG_SVIL_S IS 'DS_AUTORE_PROG_SVIL_S             '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_SCADENZA_PROG_SVIL_S IS 'DT_SCADENZA_PROG_SVIL_S           '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.TITOLO_PROG_SVIL_S IS 'TITOLO_PROG_SVIL_S                '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_PROG_SVIL_S_PK IS 'DMALM_PROG_SVIL_S_PK              '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.RANK_STATO_PROG_SVIL_S IS 'RANK_STATO_PROG_SVIL_S            '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_CARICAMENTO_PROG_SVIL_S IS 'DT_CARICAMENTO_PROG_SVIL_S        '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.RANK_STATO_PROG_SVIL_S_MESE IS 'RANK_STATO_PROG_SVIL_S_MESE       '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.NUMERO_TESTATA IS 'NUMERO_TESTATA                    '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.NUMERO_LINEA IS 'NUMERO_LINEA                      '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.FORNITURA IS 'FORNITURA                         '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DATA_INIZIO IS 'DATA_INIZIO                       '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DATA_INIZIO_EFF IS 'DATA_INIZIO_EFF                   '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DATA_CHIUSURA_PROG_SVIL_S IS 'DATA_CHIUSURA_PROG_SVIL_S         '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DATA_DISPONIBILITA_PIANIFICATA IS 'DATA_DISPONIBILITA_PIANIFICATA    '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DATA_DISPONIBILITA_EFFETTIVA IS 'DATA_DISPONIBILITA_EFFETTIVA      '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DURATA_EFFETTIVA_PROG_SVIL_S IS 'DURATA_EFFETTIVA_PROG_SVIL_S      '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DESCRIZIONE_PROG_SVIL_S IS 'DESCRIZIONE_PROG_SVIL_S           '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN DMALM_PROGETTO_SVILUPPO_SVIL.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX SYS_C0011279 ON DMALM_PROGETTO_SVILUPPO_SVIL 
    ( 
     DMALM_PROG_SVIL_S_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 458752 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE INDEX IDX_PROGETTO_SVILUPPO_SVIL ON DMALM_PROGETTO_SVILUPPO_SVIL 
    ( 
     DT_STORICIZZAZIONE ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ADD CONSTRAINT DMALM_PROGETTO_SVIL_SVIL_PK PRIMARY KEY ( DMALM_PROG_SVIL_S_PK ) 
    USING INDEX SYS_C0011279 ;
ALTER TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ADD CONSTRAINT PROGETTO_SVILUPPO_SVIL_FK_02 FOREIGN KEY 
    ( 
     DMALM_PROJECT_FK_02
    ) 
    REFERENCES DMALM_PROJECT 
    ( 
     DMALM_PROJECT_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ADD CONSTRAINT PROGETTO_SVILUPPO_SVIL_FK_03 FOREIGN KEY 
    ( 
     DMALM_STATO_WORKITEM_FK_03
    ) 
    REFERENCES DMALM_STATO_WORKITEM 
    ( 
     DMALM_STATO_WORKITEM_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ADD CONSTRAINT PROGETTO_SVILUPPO_SVIL_FK_04 FOREIGN KEY 
    ( 
     DMALM_TEMPO_FK_04
    ) 
    REFERENCES DMALM_TEMPO 
    ( 
     DMALM_TEMPO_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_PROGETTO_SVILUPPO_SVIL 
    ADD CONSTRAINT PROGETTO_SVILUPPO_SVIL_FK_06 FOREIGN KEY 
    ( 
     DMALM_USER_FK_06
    ) 
    REFERENCES DMALM_USER 
    ( 
     DMALM_USER_PK
    ) 
    NOT DEFERRABLE 
;
SPOOL OFF;
