SPOOL 062_DMALM_SIRE_HISTORY_PROJGROUP.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_SIRE_HISTORY_PROJGROUP 
    ( 
     C_LOCATION VARCHAR2 (4000 BYTE) , 
     C_IS_LOCAL NUMBER (1) , 
     C_PK VARCHAR2 (4000 BYTE) , 
     FK_URI_PARENT VARCHAR2 (4000 BYTE) , 
     FK_PARENT VARCHAR2 (4000 BYTE) , 
     C_NAME VARCHAR2 (4000 BYTE) , 
     C_DELETED NUMBER (1) , 
     C_REV NUMBER (38) , 
     C_URI VARCHAR2 (4000 BYTE) , 
     DATA_CARICAMENTO TIMESTAMP , 
     SIRE_HISTORY_PROJGROUP_PK NUMBER  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 262144 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_SIRE_HISTORY_PROJGROUP IS 'DMALM_SIRE_HISTORY_PROJGROUP      ';
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_LOCATION IS 'C_LOCATION                        '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_IS_LOCAL IS 'C_IS_LOCAL                        '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_PK IS 'C_PK                              '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.FK_URI_PARENT IS 'FK_URI_PARENT                     '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.FK_PARENT IS 'FK_PARENT                         '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_NAME IS 'C_NAME                            '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_DELETED IS 'C_DELETED                         '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_REV IS 'C_REV                             '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.C_URI IS 'C_URI                             '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN DMALM_SIRE_HISTORY_PROJGROUP.SIRE_HISTORY_PROJGROUP_PK IS 'SIRE_HISTORY_PROJGROUP_PK         '; 
CREATE INDEX HISTORY_SIRE_PROJGROUP_IDX_1 ON DMALM_SIRE_HISTORY_PROJGROUP 
    ( 
     C_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 167 
    STORAGE ( 
        INITIAL 131072 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE UNIQUE INDEX DMALM_SIRE_HISTORY_PROJGR_PK ON DMALM_SIRE_HISTORY_PROJGROUP 
    ( 
     SIRE_HISTORY_PROJGROUP_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE INDEX HISTORY_SIRE_PROJGROUP_IDX_2 ON DMALM_SIRE_HISTORY_PROJGROUP 
    ( 
     DATA_CARICAMENTO ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_SIRE_HISTORY_PROJGROUP 
    ADD CONSTRAINT DMALM_SIRE_HIST_PROJGROUP_PK PRIMARY KEY ( SIRE_HISTORY_PROJGROUP_PK ) 
    USING INDEX DMALM_SIRE_HISTORY_PROJGR_PK ;
SPOOL OFF;
