SPOOL 077_DMALM_SISS_HISTORY_WORKUSERASS.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_SISS_HISTORY_WORKUSERASS 
    ( 
     FK_USER VARCHAR2 (4000 BYTE) , 
     FK_URI_WORKITEM VARCHAR2 (4000 BYTE) , 
     FK_WORKITEM VARCHAR2 (4000 BYTE) , 
     FK_URI_USER VARCHAR2 (4000 BYTE) , 
     DATA_CARICAMENTO TIMESTAMP , 
     SISS_HISTORY_WORKUSERASS_PK NUMBER  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 142606336 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_SISS_HISTORY_WORKUSERASS IS 'DMALM_SISS_HISTORY_WORKUSERASS    ';
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.FK_USER IS 'FK_USER                           '; 
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.FK_URI_WORKITEM IS 'FK_URI_WORKITEM                   '; 
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.FK_WORKITEM IS 'FK_WORKITEM                       '; 
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.FK_URI_USER IS 'FK_URI_USER                       '; 
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN DMALM_SISS_HISTORY_WORKUSERASS.SISS_HISTORY_WORKUSERASS_PK IS 'SISS_HISTORY_WORKUSERASS_PK       '; 
CREATE UNIQUE INDEX DMALM_SISS_HISTORY_WORKUS_PK ON DMALM_SISS_HISTORY_WORKUSERASS 
    ( 
     SISS_HISTORY_WORKUSERASS_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 8388608 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE DMALM_SISS_HISTORY_WORKUSERASS 
    ADD CONSTRAINT DMALM_SISS_HIST_WORKUSERASS_PK PRIMARY KEY ( SISS_HISTORY_WORKUSERASS_PK ) 
    USING INDEX DMALM_SISS_HISTORY_WORKUS_PK ;
SPOOL OFF;
