SPOOL 091_DMALM_STG_UNITA_ORGANIZZATIVE.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_STG_UNITA_ORGANIZZATIVE 
    ( 
     ID VARCHAR2 (50 BYTE)  NOT NULL , 
     CODICE VARCHAR2 (20 BYTE) , 
     DATA_INIZIO_VALIDITA VARCHAR2 (22 BYTE) , 
     DATA_FINE_VALIDITA VARCHAR2 (22 BYTE) , 
     DESCRIZIONE VARCHAR2 (200 BYTE) , 
     DATA_ATTIVAZIONE VARCHAR2 (22 BYTE) , 
     DATA_DISATTIVAZIONE VARCHAR2 (22 BYTE) , 
     NOTE VARCHAR2 (200 BYTE) , 
     INTERNO VARCHAR2 (2 BYTE) , 
     COD_RESPONSABILE VARCHAR2 (20 BYTE) , 
     INDIRIZZO_EMAIL VARCHAR2 (50 BYTE) , 
     ID_TIPOLOGIA_UFFICIO VARCHAR2 (10 BYTE) , 
     ID_GRADO_UFFICIO VARCHAR2 (10 BYTE) , 
     ID_SEDE VARCHAR2 (10 BYTE) , 
     COD_SUPERIORE VARCHAR2 (50 BYTE) , 
     COD_ENTE VARCHAR2 (50 BYTE) , 
     COD_VISIBILITA VARCHAR2 (50 BYTE) , 
     TIPO_PERSONA VARCHAR2 (2 BYTE) , 
     DATA_CARICAMENTO TIMESTAMP  NOT NULL , 
     DMALM_STG_UNITA_ORG_PK NUMBER  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_STG_UNITA_ORGANIZZATIVE IS 'DMALM_STG_UNITA_ORGANIZZATIVE     ';
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.ID IS 'ID                                '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DATA_INIZIO_VALIDITA IS 'DATA_INIZIO_VALIDITA              '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DATA_FINE_VALIDITA IS 'DATA_FINE_VALIDITA                '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DESCRIZIONE IS 'DESCRIZIONE                       '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DATA_ATTIVAZIONE IS 'DATA_ATTIVAZIONE                  '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DATA_DISATTIVAZIONE IS 'DATA_DISATTIVAZIONE               '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.NOTE IS 'NOTE                              '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.INTERNO IS 'INTERNO                           '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.COD_RESPONSABILE IS 'COD_RESPONSABILE                  '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.INDIRIZZO_EMAIL IS 'INDIRIZZO_EMAIL                   '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.ID_TIPOLOGIA_UFFICIO IS 'ID_TIPOLOGIA_UFFICIO              '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.ID_GRADO_UFFICIO IS 'ID_GRADO_UFFICIO                  '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.ID_SEDE IS 'ID_SEDE                           '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.COD_SUPERIORE IS 'COD_SUPERIORE                     '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.COD_ENTE IS 'COD_ENTE                          '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.COD_VISIBILITA IS 'COD_VISIBILITA                    '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.TIPO_PERSONA IS 'TIPO_PERSONA                      '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN DMALM_STG_UNITA_ORGANIZZATIVE.DMALM_STG_UNITA_ORG_PK IS 'DMALM_STG_UNITA_ORG_PK            '; 
CREATE UNIQUE INDEX DMALM_STG_UNITA_ORGANIZZA_PK ON DMALM_STG_UNITA_ORGANIZZATIVE 
    ( 
     DMALM_STG_UNITA_ORG_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_STG_UNITA_ORGANIZZATIVE 
    ADD CONSTRAINT DMALM_STG_UNITA_ORGANIZZA_PK PRIMARY KEY ( DMALM_STG_UNITA_ORG_PK ) 
    USING INDEX DMALM_STG_UNITA_ORGANIZZA_PK ;
SPOOL OFF;
