SPOOL 094_DMALM_TASK_IT_ODS.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_TASK_IT_ODS 
    ( 
     CD_TASK_IT VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_TASK_IT TIMESTAMP , 
     DT_RISOLUZIONE_TASK_IT TIMESTAMP , 
     DT_MODIFICA_TASK_IT TIMESTAMP , 
     DT_CAMBIO_STATO_TASK_IT TIMESTAMP , 
     DESCRIZIONE_TASK_IT VARCHAR2 (4000 BYTE) , 
     MOTIVO_RISOLUZIONE_TASK_IT VARCHAR2 (255 BYTE) , 
     ID_AUTORE_TASK_IT VARCHAR2 (32 BYTE) , 
     DS_AUTORE_TASK_IT VARCHAR2 (50 BYTE) , 
     DT_SCADENZA_TASK_IT TIMESTAMP , 
     TITOLO_TASK_IT VARCHAR2 (4000 BYTE) , 
     DMALM_TASK_IT_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (15) , 
     DMALM_TEMPO_FK_04 NUMBER (15) , 
     RANK_STATO_TASK_IT NUMBER (1) , 
     DT_CARICAMENTO_TASK_IT TIMESTAMP , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE TIMESTAMP , 
     RANK_STATO_TASK_IT_MESE NUMBER (5) DEFAULT 0 , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     AVANZAMENTO NUMBER (8) , 
     CODICE VARCHAR2 (200 BYTE) , 
     DT_INIZIO_PIANIFICATO TIMESTAMP , 
     DT_FINE_PIANIFICATA TIMESTAMP , 
     TIPO_TASK VARCHAR2 (200 BYTE) , 
     DT_INIZIO_EFFETTIVO TIMESTAMP , 
     DT_FINE_EFFETTIVA TIMESTAMP , 
     SEVERITY_TASK_IT VARCHAR2 (20 BYTE) , 
     PRIORITY_TASK_IT VARCHAR2 (20 BYTE) , 
     DURATA_EFFETTIVA NUMBER (8) , 
     DMALM_USER_FK_06 NUMBER (15) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 4194304 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE DMALM_TASK_IT_ODS IS 'DMALM_TASK_IT_ODS                 ';
COMMENT ON COLUMN DMALM_TASK_IT_ODS.CD_TASK_IT IS 'CD_TASK_IT                        '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_CREAZIONE_TASK_IT IS 'DT_CREAZIONE_TASK_IT              '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_RISOLUZIONE_TASK_IT IS 'DT_RISOLUZIONE_TASK_IT            '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_MODIFICA_TASK_IT IS 'DT_MODIFICA_TASK_IT               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_CAMBIO_STATO_TASK_IT IS 'DT_CAMBIO_STATO_TASK_IT           '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DESCRIZIONE_TASK_IT IS 'DESCRIZIONE_TASK_IT               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.MOTIVO_RISOLUZIONE_TASK_IT IS 'MOTIVO_RISOLUZIONE_TASK_IT        '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.ID_AUTORE_TASK_IT IS 'ID_AUTORE_TASK_IT                 '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DS_AUTORE_TASK_IT IS 'DS_AUTORE_TASK_IT                 '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_SCADENZA_TASK_IT IS 'DT_SCADENZA_TASK_IT               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.TITOLO_TASK_IT IS 'TITOLO_TASK_IT                    '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_TASK_IT_PK IS 'DMALM_TASK_IT_PK                  '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.RANK_STATO_TASK_IT IS 'RANK_STATO_TASK_IT                '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_CARICAMENTO_TASK_IT IS 'DT_CARICAMENTO_TASK_IT            '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.RANK_STATO_TASK_IT_MESE IS 'RANK_STATO_TASK_IT_MESE           '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.AVANZAMENTO IS 'AVANZAMENTO                       '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_INIZIO_PIANIFICATO IS 'DT_INIZIO_PIANIFICATO             '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_FINE_PIANIFICATA IS 'DT_FINE_PIANIFICATA               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.TIPO_TASK IS 'TIPO_TASK                         '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_INIZIO_EFFETTIVO IS 'DT_INIZIO_EFFETTIVO               '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DT_FINE_EFFETTIVA IS 'DT_FINE_EFFETTIVA                 '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.SEVERITY_TASK_IT IS 'SEVERITY_TASK_IT                  '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.PRIORITY_TASK_IT IS 'PRIORITY_TASK_IT                  '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DURATA_EFFETTIVA IS 'DURATA_EFFETTIVA                  '; 
COMMENT ON COLUMN DMALM_TASK_IT_ODS.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX SYS_C0011411 ON DMALM_TASK_IT_ODS 
    ( 
     DMALM_TASK_IT_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 327680 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_TASK_IT_ODS 
    ADD CONSTRAINT DMALM_TASK_IT_ODS_PK PRIMARY KEY ( DMALM_TASK_IT_PK ) 
    USING INDEX SYS_C0011411 ;
;
;
;
;
;
;
;
;
SPOOL OFF;
