SPOOL 097_DMALM_TESTCASE.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE DMALM_TESTCASE 
    ( 
     CD_TESTCASE VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_TESTCASE DATE , 
     DT_RISOLUZIONE_TESTCASE DATE , 
     DT_MODIFICA_TESTCASE DATE , 
     DT_CAMBIO_STATO_TESTCASE DATE , 
     MOTIVO_RISOLUZIONE_TESTCASE VARCHAR2 (255 BYTE) , 
     ID_AUTORE_TESTCASE VARCHAR2 (100 BYTE) , 
     DS_AUTORE_TESTCASE VARCHAR2 (100 BYTE) , 
     DT_SCADENZA_TESTCASE DATE , 
     TITOLO_TESTCASE VARCHAR2 (4000 BYTE) , 
     DMALM_TESTCASE_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (16) , 
     DMALM_TEMPO_FK_04 NUMBER (15) DEFAULT 0 , 
     RANK_STATO_TESTCASE NUMBER , 
     DT_CARICAMENTO_TESTCASE DATE , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE DATE , 
     RANK_STATO_TESTCASE_MESE NUMBER (5) DEFAULT 0 , 
     DESCRIZIONE_TESTCASE CLOB , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) DEFAULT 0 , 
     CODICE VARCHAR2 (200 BYTE) , 
     DATA_ESECUZIONE_TESTCASE TIMESTAMP , 
     NUMERO_TESTATA VARCHAR2 (200 BYTE) , 
     NUMERO_LINEA VARCHAR2 (200 BYTE) , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) DEFAULT 0 
    ) 
        TABLESPACE "TS_ALM_SV"; 
COMMENT ON TABLE DMALM_TESTCASE IS 'DMALM_TESTCASE                    ';
COMMENT ON COLUMN DMALM_TESTCASE.CD_TESTCASE IS 'CD_TESTCASE                       '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_CREAZIONE_TESTCASE IS 'DT_CREAZIONE_TESTCASE             '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_RISOLUZIONE_TESTCASE IS 'DT_RISOLUZIONE_TESTCASE           '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_MODIFICA_TESTCASE IS 'DT_MODIFICA_TESTCASE              '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_CAMBIO_STATO_TESTCASE IS 'DT_CAMBIO_STATO_TESTCASE          '; 
COMMENT ON COLUMN DMALM_TESTCASE.MOTIVO_RISOLUZIONE_TESTCASE IS 'MOTIVO_RISOLUZIONE_TESTCASE       '; 
COMMENT ON COLUMN DMALM_TESTCASE.ID_AUTORE_TESTCASE IS 'ID_AUTORE_TESTCASE                '; 
COMMENT ON COLUMN DMALM_TESTCASE.DS_AUTORE_TESTCASE IS 'DS_AUTORE_TESTCASE                '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_SCADENZA_TESTCASE IS 'DT_SCADENZA_TESTCASE              '; 
COMMENT ON COLUMN DMALM_TESTCASE.TITOLO_TESTCASE IS 'TITOLO_TESTCASE                   '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_TESTCASE_PK IS 'DMALM_TESTCASE_PK                 '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN DMALM_TESTCASE.RANK_STATO_TESTCASE IS 'RANK_STATO_TESTCASE               '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_CARICAMENTO_TESTCASE IS 'DT_CARICAMENTO_TESTCASE           '; 
COMMENT ON COLUMN DMALM_TESTCASE.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN DMALM_TESTCASE.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN DMALM_TESTCASE.RANK_STATO_TESTCASE_MESE IS 'RANK_STATO_TESTCASE_MESE          '; 
COMMENT ON COLUMN DMALM_TESTCASE.DESCRIZIONE_TESTCASE IS 'DESCRIZIONE_TESTCASE              '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN DMALM_TESTCASE.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN DMALM_TESTCASE.DATA_ESECUZIONE_TESTCASE IS 'DATA_ESECUZIONE_TESTCASE          '; 
COMMENT ON COLUMN DMALM_TESTCASE.NUMERO_TESTATA IS 'NUMERO_TESTATA                    '; 
COMMENT ON COLUMN DMALM_TESTCASE.NUMERO_LINEA IS 'NUMERO_LINEA                      '; 
COMMENT ON COLUMN DMALM_TESTCASE.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN DMALM_TESTCASE.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN DMALM_TESTCASE.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX SYS_C0011415 ON DMALM_TESTCASE 
    ( 
     DMALM_TESTCASE_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE INDEX IDX_TESTCASE ON DMALM_TESTCASE 
    ( 
     DT_STORICIZZAZIONE ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE DMALM_TESTCASE 
    ADD CONSTRAINT DMALM_TESTCASE_PK PRIMARY KEY ( DMALM_TESTCASE_PK ) 
    USING INDEX SYS_C0011415 ;
ALTER TABLE DMALM_TESTCASE 
    ADD CONSTRAINT TESTCASE_FK_02 FOREIGN KEY 
    ( 
     DMALM_PROJECT_FK_02
    ) 
    REFERENCES DMALM_PROJECT 
    ( 
     DMALM_PROJECT_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_TESTCASE 
    ADD CONSTRAINT TESTCASE_FK_03 FOREIGN KEY 
    ( 
     DMALM_STATO_WORKITEM_FK_03
    ) 
    REFERENCES DMALM_STATO_WORKITEM 
    ( 
     DMALM_STATO_WORKITEM_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_TESTCASE 
    ADD CONSTRAINT TESTCASE_FK_04 FOREIGN KEY 
    ( 
     DMALM_TEMPO_FK_04
    ) 
    REFERENCES DMALM_TEMPO 
    ( 
     DMALM_TEMPO_PK
    ) 
    NOT DEFERRABLE 
;
ALTER TABLE DMALM_TESTCASE 
    ADD CONSTRAINT TESTCASE_FK_06 FOREIGN KEY 
    ( 
     DMALM_USER_FK_06
    ) 
    REFERENCES DMALM_USER 
    ( 
     DMALM_USER_PK
    ) 
    NOT DEFERRABLE 
;
SPOOL OFF;
