SPOOL 104_SIRE_WORKITEM_LINK.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE SIRE_WORKITEM_LINK 
    ( 
     DATACARICAMENTO TIMESTAMP  NOT NULL , 
     URI_WORKITEM VARCHAR2 (4000 BYTE) , 
     STATO_WORKITEM VARCHAR2 (100 BYTE) , 
     TYPE_WORKITEM VARCHAR2 (100 BYTE) , 
     URI_LINK VARCHAR2 (4000 BYTE) , 
     STATO_LINK VARCHAR2 (100 BYTE) , 
     TYPE_LINK VARCHAR2 (100 BYTE) , 
     ID_LINK VARCHAR2 (100 BYTE) , 
     PK_LINK VARCHAR2 (4000 BYTE) , 
     CCREATED_LINK TIMESTAMP , 
     WORKITEM_LINK_PK NUMBER (15)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 9437184 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE SIRE_WORKITEM_LINK IS 'SIRE_WORKITEM_LINK                ';
COMMENT on column sire_workitem_link.datacaricamento is 'data_caricamento';
COMMENT on column sire_workitem_link.URI_WORKITEM is 'URI_WORKITEM';
COMMENT on column sire_workitem_link.STATO_WORKITEM is 'STATO_WORKITEM';
COMMENT on column sire_workitem_link.TYPE_WORKITEM is 'TYPE_WORKITEM';
COMMENT on column sire_workitem_link.URI_LINK is 'URI_LINK';
COMMENT on column sire_workitem_link.STATO_LINK is 'STATO_LINK';
COMMENT on column sire_workitem_link.TYPE_LINK is 'TYPE_LINK';
COMMENT on column sire_workitem_link.ID_LINK is 'ID_LINK';
COMMENT on column sire_workitem_link.PK_LINK is 'PK_LINK';
COMMENT on column sire_workitem_link.CCREATED_LINK is 'CCREATED_LINK';
COMMENT on column sire_workitem_link.WORKITEM_LINK_PK is 'WORKITEM_LINK_PK';
CREATE INDEX SIRE_WORKITEM_LINK_IDX_0 ON SIRE_WORKITEM_LINK 
    ( 
     URI_WORKITEM ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 167 
    STORAGE ( 
        INITIAL 5242880 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE INDEX SIRE_WORKITEM_LINK_IDX_1 ON SIRE_WORKITEM_LINK 
    ( 
     DATACARICAMENTO ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 1048576 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE INDEX SIRE_WORKITEM_LINK_IDX_2 ON SIRE_WORKITEM_LINK 
    ( 
     TYPE_LINK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 983040 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
CREATE UNIQUE INDEX PK_SIRE_WORKITEM_LINK ON SIRE_WORKITEM_LINK 
    ( 
     WORKITEM_LINK_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE SIRE_WORKITEM_LINK 
    ADD CONSTRAINT PK_SIRE_WORKITEM_LINK PRIMARY KEY ( WORKITEM_LINK_PK ) 
    USING INDEX PK_SIRE_WORKITEM_LINK ;
SPOOL OFF;
