SPOOL 112_T_DMALM_BUILD.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_BUILD 
    ( 
     CD_BUILD VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_BUILD DATE , 
     DT_RISOLUZIONE_BUILD DATE , 
     DT_MODIFICA_BUILD DATE , 
     DT_CAMBIO_STATO_BUILD DATE , 
     MOTIVO_RISOLUZIONE_BUILD VARCHAR2 (255 BYTE) , 
     ID_AUTORE_BUILD VARCHAR2 (100 BYTE) , 
     DS_AUTORE_BUILD VARCHAR2 (100 BYTE) , 
     DT_SCADENZA_BUILD DATE , 
     TITOLO_BUILD VARCHAR2 (4000 BYTE) , 
     DMALM_BUILD_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (15) , 
     DMALM_TEMPO_FK_04 NUMBER (15) , 
     RANK_STATO_BUILD NUMBER , 
     DT_CARICAMENTO_BUILD DATE , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE DATE , 
     RANK_STATO_BUILD_MESE NUMBER (5) , 
     CODICE VARCHAR2 (200 BYTE) , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     DESCRIZIONE_BUILD CLOB , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) 
    ) 
        TABLESPACE "TS_ALM_SV"; 
COMMENT ON TABLE T_DMALM_BUILD IS 'T_DMALM_BUILD                     ';
COMMENT ON COLUMN T_DMALM_BUILD.CD_BUILD IS 'CD_BUILD                          '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_CREAZIONE_BUILD IS 'DT_CREAZIONE_BUILD                '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_RISOLUZIONE_BUILD IS 'DT_RISOLUZIONE_BUILD              '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_MODIFICA_BUILD IS 'DT_MODIFICA_BUILD                 '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_CAMBIO_STATO_BUILD IS 'DT_CAMBIO_STATO_BUILD             '; 
COMMENT ON COLUMN T_DMALM_BUILD.MOTIVO_RISOLUZIONE_BUILD IS 'MOTIVO_RISOLUZIONE_BUILD          '; 
COMMENT ON COLUMN T_DMALM_BUILD.ID_AUTORE_BUILD IS 'ID_AUTORE_BUILD                   '; 
COMMENT ON COLUMN T_DMALM_BUILD.DS_AUTORE_BUILD IS 'DS_AUTORE_BUILD                   '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_SCADENZA_BUILD IS 'DT_SCADENZA_BUILD                 '; 
COMMENT ON COLUMN T_DMALM_BUILD.TITOLO_BUILD IS 'TITOLO_BUILD                      '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_BUILD_PK IS 'DMALM_BUILD_PK                    '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN T_DMALM_BUILD.RANK_STATO_BUILD IS 'RANK_STATO_BUILD                  '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_CARICAMENTO_BUILD IS 'DT_CARICAMENTO_BUILD              '; 
COMMENT ON COLUMN T_DMALM_BUILD.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN T_DMALM_BUILD.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN T_DMALM_BUILD.RANK_STATO_BUILD_MESE IS 'RANK_STATO_BUILD_MESE             '; 
COMMENT ON COLUMN T_DMALM_BUILD.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN T_DMALM_BUILD.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN T_DMALM_BUILD.DESCRIZIONE_BUILD IS 'DESCRIZIONE_BUILD                 '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN T_DMALM_BUILD.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_BUILD.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX PK_T_DMALM_BUILD ON T_DMALM_BUILD 
    ( 
     DMALM_BUILD_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_BUILD 
    ADD CONSTRAINT PK_T_DMALM_BUILD PRIMARY KEY ( DMALM_BUILD_PK ) 
    USING INDEX PK_T_DMALM_BUILD ;
;
;
;
;
SPOOL OFF;
