SPOOL 113_T_DMALM_CLASSIFICATORI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_CLASSIFICATORI 
    ( 
     DMALM_CLASSIFICATORI_PK NUMBER (15)  NOT NULL , 
     TIPO_CLASSIFICATORE VARCHAR2 (255 BYTE)  NOT NULL , 
     CODICE_CLASSIFICATORE VARCHAR2 (200 BYTE)  NOT NULL , 
     ID_ORESTE NUMBER (8) , 
     DT_CARICAMENTO DATE  NOT NULL , 
     DT_INIZIO_VALIDITA DATE  NOT NULL , 
     DT_FINE_VALIDITA DATE  NOT NULL , 
     DT_INSERIMENTO_RECORD DATE 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_CLASSIFICATORI IS 'T_DMALM_CLASSIFICATORI            ';
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.DMALM_CLASSIFICATORI_PK IS 'DMALM_CLASSIFICATORI_PK           '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.TIPO_CLASSIFICATORE IS 'TIPO_CLASSIFICATORE               '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.CODICE_CLASSIFICATORE IS 'CODICE_CLASSIFICATORE             '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.ID_ORESTE IS 'ID_ORESTE                         '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.DT_CARICAMENTO IS 'DT_CARICAMENTO                    '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '; 
COMMENT ON COLUMN T_DMALM_CLASSIFICATORI.DT_INSERIMENTO_RECORD IS 'DT_INSERIMENTO_RECORD             '; 
CREATE UNIQUE INDEX PK_T_DMALM_CLASSIFICATORI ON T_DMALM_CLASSIFICATORI 
    ( 
     DMALM_CLASSIFICATORI_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_CLASSIFICATORI 
    ADD CONSTRAINT PK_T_DMALM_CLASSIFICATORI PRIMARY KEY ( DMALM_CLASSIFICATORI_PK ) 
    USING INDEX PK_T_DMALM_CLASSIFICATORI ;
SPOOL OFF;
