SPOOL 122_T_DMALM_MODULO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_MODULO 
    ( 
     DMALM_MODULO_PK NUMBER (15)  NOT NULL , 
     DMALM_PRODOTTO_FK_02 NUMBER (15) , 
     ID_MODULO VARCHAR2 (100 BYTE) , 
     TIPO_OGGETTO VARCHAR2 (1 BYTE) , 
     SIGLA_PRODOTTO VARCHAR2 (500 BYTE) , 
     SIGLA_SOTTOSISTEMA VARCHAR2 (500 BYTE) , 
     SIGLA_MODULO VARCHAR2 (500 BYTE) , 
     NOME VARCHAR2 (500 BYTE) , 
     DS_MODULO VARCHAR2 (4000 BYTE) , 
     ANNULLATO VARCHAR2 (2 BYTE) , 
     DT_INIZIO_VALIDITA DATE  NOT NULL , 
     DT_FINE_VALIDITA DATE , 
     DMALM_PERSONALE_FK_01 NUMBER , 
     SOTTOSISTEMA VARCHAR2 (4000 BYTE) , 
     TECNOLOGIE VARCHAR2 (4000 BYTE) , 
     TIPO_MODULO VARCHAR2 (4000 BYTE) , 
     DT_INSERIMENTO_RECORD DATE , 
     DMALM_SOTTOSISTEMA_FK_03 NUMBER (15) , 
     DT_ANNULLAMENTO DATE , 
     DMALM_MODULO_SEQ NUMBER (15)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_MODULO IS 'T_DMALM_MODULO                    ';
COMMENT ON COLUMN T_DMALM_MODULO.DMALM_MODULO_PK IS 'DMALM_MODULO_PK                   '; 
COMMENT ON COLUMN T_DMALM_MODULO.DMALM_PRODOTTO_FK_02 IS 'DMALM_PRODOTTO_FK_02              '; 
COMMENT ON COLUMN T_DMALM_MODULO.ID_MODULO IS 'ID_MODULO                         '; 
COMMENT ON COLUMN T_DMALM_MODULO.TIPO_OGGETTO IS 'TIPO_OGGETTO                      '; 
COMMENT ON COLUMN T_DMALM_MODULO.SIGLA_PRODOTTO IS 'SIGLA_PRODOTTO                    '; 
COMMENT ON COLUMN T_DMALM_MODULO.SIGLA_SOTTOSISTEMA IS 'SIGLA_SOTTOSISTEMA                '; 
COMMENT ON COLUMN T_DMALM_MODULO.SIGLA_MODULO IS 'SIGLA_MODULO                      '; 
COMMENT ON COLUMN T_DMALM_MODULO.NOME IS 'NOME                              '; 
COMMENT ON COLUMN T_DMALM_MODULO.DS_MODULO IS 'DS_MODULO                         '; 
COMMENT ON COLUMN T_DMALM_MODULO.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_MODULO.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '; 
COMMENT ON COLUMN T_DMALM_MODULO.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '; 
COMMENT ON COLUMN T_DMALM_MODULO.DMALM_PERSONALE_FK_01 IS 'DMALM_PERSONALE_FK_01             '; 
COMMENT ON COLUMN T_DMALM_MODULO.SOTTOSISTEMA IS 'SOTTOSISTEMA                      '; 
COMMENT ON COLUMN T_DMALM_MODULO.TECNOLOGIE IS 'TECNOLOGIE                        '; 
COMMENT ON COLUMN T_DMALM_MODULO.TIPO_MODULO IS 'TIPO_MODULO                       '; 
COMMENT ON COLUMN T_DMALM_MODULO.DT_INSERIMENTO_RECORD IS 'DT_INSERIMENTO_RECORD             '; 
COMMENT ON COLUMN T_DMALM_MODULO.DMALM_SOTTOSISTEMA_FK_03 IS 'DMALM_SOTTOSISTEMA_FK_03          '; 
COMMENT ON COLUMN T_DMALM_MODULO.DT_ANNULLAMENTO IS 'DT_ANNULLAMENTO                   '; 
COMMENT ON COLUMN T_DMALM_MODULO.DMALM_MODULO_SEQ IS 'DMALM_MODULO_SEQ                  '; 
CREATE UNIQUE INDEX PK_T_DMALM_MODULO ON T_DMALM_MODULO 
    ( 
     DMALM_MODULO_SEQ ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_MODULO 
    ADD CONSTRAINT PK_T_DMALM_MODULO PRIMARY KEY ( DMALM_MODULO_SEQ ) 
    USING INDEX PK_T_DMALM_MODULO ;
;
SPOOL OFF;
