SPOOL 126_T_DMALM_PRODOTTO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_PRODOTTO 
    ( 
     DMALM_PRODOTTO_PK NUMBER (15)  NOT NULL , 
     ID_PRODOTTO VARCHAR2 (100 BYTE) , 
     TIPO_OGGETTO VARCHAR2 (12 BYTE) , 
     SIGLA VARCHAR2 (4000 BYTE) , 
     NOME VARCHAR2 (4000 BYTE) , 
     DS_PRODOTTO VARCHAR2 (4000 BYTE) , 
     DMALM_UNITAORGANIZZATIVA_FK_01 NUMBER (15) , 
     DMALM_PERSONALE_FK_02 NUMBER (15) , 
     ANNULLATO VARCHAR2 (2 BYTE) , 
     DT_INIZIO_VALIDITA TIMESTAMP  NOT NULL , 
     DT_FINE_VALIDITA TIMESTAMP , 
     AMBITO_MANUTENZIONE VARCHAR2 (4000 BYTE) , 
     AREA_TEMATICA VARCHAR2 (4000 BYTE) , 
     BASE_DATI_ETL VARCHAR2 (4000 BYTE) , 
     BASE_DATI_LETTURA VARCHAR2 (4000 BYTE) , 
     BASE_DATI_SCRITTURA VARCHAR2 (4000 BYTE) , 
     CATEGORIA VARCHAR2 (4000 BYTE) , 
     FORNITURA_RISORSE_ESTERNE VARCHAR2 (4000 BYTE) , 
     DT_INSERIMENTO_RECORD DATE , 
     DT_ANNULLAMENTO DATE , 
     DMALM_PRODOTTO_SEQ NUMBER (15)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_PRODOTTO IS 'T_DMALM_PRODOTTO                  ';
COMMENT ON COLUMN T_DMALM_PRODOTTO.DMALM_PRODOTTO_PK IS 'DMALM_PRODOTTO_PK                 '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.ID_PRODOTTO IS 'ID_PRODOTTO                       '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.TIPO_OGGETTO IS 'TIPO_OGGETTO                      '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.SIGLA IS 'SIGLA                             '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.NOME IS 'NOME                              '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DS_PRODOTTO IS 'DS_PRODOTTO                       '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DMALM_UNITAORGANIZZATIVA_FK_01 IS 'DMALM_UNITAORGANIZZATIVA_FK_01    '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DMALM_PERSONALE_FK_02 IS 'DMALM_PERSONALE_FK_02             '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.AMBITO_MANUTENZIONE IS 'AMBITO_MANUTENZIONE               '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.AREA_TEMATICA IS 'AREA_TEMATICA                     '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.BASE_DATI_ETL IS 'BASE_DATI_ETL                     '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.BASE_DATI_LETTURA IS 'BASE_DATI_LETTURA                 '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.BASE_DATI_SCRITTURA IS 'BASE_DATI_SCRITTURA               '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.CATEGORIA IS 'CATEGORIA                         '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.FORNITURA_RISORSE_ESTERNE IS 'FORNITURA_RISORSE_ESTERNE         '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DT_INSERIMENTO_RECORD IS 'DT_INSERIMENTO_RECORD             '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DT_ANNULLAMENTO IS 'DT_ANNULLAMENTO                   '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO.DMALM_PRODOTTO_SEQ IS 'DMALM_PRODOTTO_SEQ                '; 
CREATE UNIQUE INDEX PK_T_DMALM_PRODOTTO ON T_DMALM_PRODOTTO 
    ( 
     DMALM_PRODOTTO_SEQ ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_PRODOTTO 
    ADD CONSTRAINT PK_T_DMALM_PRODOTTO PRIMARY KEY ( DMALM_PRODOTTO_SEQ ) 
    USING INDEX PK_T_DMALM_PRODOTTO ;
;
;
SPOOL OFF;
