SPOOL 127_T_DMALM_PRODOTTO_ARCH_CLASF.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_PRODOTTO_ARCH_CLASF 
    ( 
     FK_PRODOTTO NUMBER (15)  NOT NULL , 
     FK_CLASSIFICATORI NUMBER (15)  NOT NULL , 
     DT_CARICAMENTO TIMESTAMP 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_PRODOTTO_ARCH_CLASF IS 'T_DMALM_PRODOTTO_ARCH_CLASF       ';
COMMENT ON COLUMN T_DMALM_PRODOTTO_ARCH_CLASF.FK_PRODOTTO IS 'FK_PRODOTTO                       '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO_ARCH_CLASF.FK_CLASSIFICATORI IS 'FK_CLASSIFICATORI                 '; 
COMMENT ON COLUMN T_DMALM_PRODOTTO_ARCH_CLASF.DT_CARICAMENTO IS 'DT_CARICAMENTO                    '; 
CREATE UNIQUE INDEX PK_T_DMALM_PRODOTTO_ARCH_CLASF ON T_DMALM_PRODOTTO_ARCH_CLASF 
    ( 
     FK_PRODOTTO ASC , 
     FK_CLASSIFICATORI ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_PRODOTTO_ARCH_CLASF 
    ADD CONSTRAINT PK_T_DMALM_PRODOTTO_ARCH_CLASF PRIMARY KEY ( FK_PRODOTTO, FK_CLASSIFICATORI ) 
    USING INDEX PK_T_DMALM_PRODOTTO_ARCH_CLASF ;
;
;
;
;
SPOOL OFF;
