SPOOL 130_T_DMALM_PROGETTO_SVILUPPO_DEM.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_PROGETTO_SVILUPPO_DEM 
    ( 
     CD_PROG_SVIL_D VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_PROG_SVIL_D DATE , 
     DT_RISOLUZIONE_PROG_SVIL_D DATE , 
     DT_MODIFICA_PROG_SVIL_D DATE , 
     DT_CAMBIO_STATO_PROG_SVIL_D DATE , 
     DESCRIZIONE_PROG_SVIL_D VARCHAR2 (4000 BYTE) , 
     MOTIVO_RISOLUZIONE_PROG_SVIL_D VARCHAR2 (255 BYTE) , 
     ID_AUTORE_PROG_SVIL_D VARCHAR2 (100 BYTE) , 
     DS_AUTORE_PROG_SVIL_D VARCHAR2 (100 BYTE) , 
     DT_SCADENZA_PROG_SVIL_D TIMESTAMP , 
     TITOLO_PROG_SVIL_D VARCHAR2 (4000 BYTE) , 
     DMALM_PROG_SVIL_D_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (15) , 
     DMALM_TEMPO_FK_04 NUMBER (15) , 
     RANK_STATO_PROG_SVIL_D NUMBER , 
     DT_CARICAMENTO_PROG_SVIL_D DATE , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE DATE , 
     RANK_STATO_PROG_SVIL_D_MESE NUMBER (5) , 
     DT_PASSAGGIO_ESERCIZIO TIMESTAMP , 
     SEVERITY_PROGETTO_SVIL_DEMAND VARCHAR2 (20 BYTE) , 
     PRIORITY_PROGETTO_SVIL_DEMAND VARCHAR2 (20 BYTE) , 
     ASSIGNEE VARCHAR2 (4000 BYTE) , 
     CF_DATA_INIZIO TIMESTAMP , 
     CF_DATA_INIZIO_EFF TIMESTAMP , 
     CF_DATA_DISP_PIANIFICATA TIMESTAMP , 
     CF_DATA_DISP_EFFETTIVA TIMESTAMP , 
     CF_CODICE VARCHAR2 (200 BYTE) , 
     CF_FORNITURA VARCHAR2 (80 BYTE) , 
     TEMPO_TOTALE_RISOLUZIONE NUMBER (8) , 
     LISTA_HYPERLINKS VARCHAR2 (4000 BYTE) , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_PROGETTO_SVILUPPO_DEM IS 'T_DMALM_PROGETTO_SVILUPPO_DEM     ';
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CD_PROG_SVIL_D IS 'CD_PROG_SVIL_D                    '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_CREAZIONE_PROG_SVIL_D IS 'DT_CREAZIONE_PROG_SVIL_D          '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_RISOLUZIONE_PROG_SVIL_D IS 'DT_RISOLUZIONE_PROG_SVIL_D        '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_MODIFICA_PROG_SVIL_D IS 'DT_MODIFICA_PROG_SVIL_D           '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_CAMBIO_STATO_PROG_SVIL_D IS 'DT_CAMBIO_STATO_PROG_SVIL_D       '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DESCRIZIONE_PROG_SVIL_D IS 'DESCRIZIONE_PROG_SVIL_D           '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.MOTIVO_RISOLUZIONE_PROG_SVIL_D IS 'MOTIVO_RISOLUZIONE_PROG_SVIL_D    '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.ID_AUTORE_PROG_SVIL_D IS 'ID_AUTORE_PROG_SVIL_D             '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DS_AUTORE_PROG_SVIL_D IS 'DS_AUTORE_PROG_SVIL_D             '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_SCADENZA_PROG_SVIL_D IS 'DT_SCADENZA_PROG_SVIL_D           '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.TITOLO_PROG_SVIL_D IS 'TITOLO_PROG_SVIL_D                '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_PROG_SVIL_D_PK IS 'DMALM_PROG_SVIL_D_PK              '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.RANK_STATO_PROG_SVIL_D IS 'RANK_STATO_PROG_SVIL_D            '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_CARICAMENTO_PROG_SVIL_D IS 'DT_CARICAMENTO_PROG_SVIL_D        '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.RANK_STATO_PROG_SVIL_D_MESE IS 'RANK_STATO_PROG_SVIL_D_MESE       '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DT_PASSAGGIO_ESERCIZIO IS 'DT_PASSAGGIO_ESERCIZIO            '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.SEVERITY_PROGETTO_SVIL_DEMAND IS 'SEVERITY_PROGETTO_SVIL_DEMAND     '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.PRIORITY_PROGETTO_SVIL_DEMAND IS 'PRIORITY_PROGETTO_SVIL_DEMAND     '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.ASSIGNEE IS 'ASSIGNEE                          '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_DATA_INIZIO IS 'CF_DATA_INIZIO                    '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_DATA_INIZIO_EFF IS 'CF_DATA_INIZIO_EFF                '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_DATA_DISP_PIANIFICATA IS 'CF_DATA_DISP_PIANIFICATA          '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_DATA_DISP_EFFETTIVA IS 'CF_DATA_DISP_EFFETTIVA            '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_CODICE IS 'CF_CODICE                         '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.CF_FORNITURA IS 'CF_FORNITURA                      '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.TEMPO_TOTALE_RISOLUZIONE IS 'TEMPO_TOTALE_RISOLUZIONE          '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.LISTA_HYPERLINKS IS 'LISTA_HYPERLINKS                  '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_PROGETTO_SVILUPPO_DEM.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX PK_T_DMALM_PROG_SVIL_DEM ON T_DMALM_PROGETTO_SVILUPPO_DEM 
    ( 
     DMALM_PROG_SVIL_D_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_PROGETTO_SVILUPPO_DEM 
    ADD CONSTRAINT PK_T_DMALM_PROG_SVIL_DEM PRIMARY KEY ( DMALM_PROG_SVIL_D_PK ) 
    USING INDEX PK_T_DMALM_PROG_SVIL_DEM ;
;
;
;
;
SPOOL OFF;
