SPOOL 133_T_DMALM_PROJECT.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_PROJECT 
    ( 
     DMALM_PROJECT_PK NUMBER (15)  NOT NULL , 
     DMALM_AREA_TEMATICA_FK_01 NUMBER (15) , 
     ID_PROJECT VARCHAR2 (50 BYTE) , 
     ID_REPOSITORY VARCHAR2 (10 BYTE) , 
     SIGLA_PROJECT VARCHAR2 (50 BYTE) , 
     NOME_COMPLETO_PROJECT VARCHAR2 (255 BYTE) , 
     PATH_PROJECT VARCHAR2 (500 BYTE) , 
     SERVICE_MANAGERS VARCHAR2 (2000 BYTE) , 
     FL_ATTIVO NUMBER (1) , 
     DT_INIZIO_VALIDITA DATE , 
     DT_FINE_VALIDITA DATE , 
     DT_CARICAMENTO DATE , 
     TEMPLATE VARCHAR2 (20 BYTE) , 
     DMALM_STRUTTURA_ORG_FK_02 NUMBER (15) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DATA_MODIFICA_PROJECT TIMESTAMP 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_PROJECT IS 'T_DMALM_PROJECT                   ';
COMMENT ON COLUMN T_DMALM_PROJECT.DMALM_PROJECT_PK IS 'DMALM_PROJECT_PK                  '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DMALM_AREA_TEMATICA_FK_01 IS 'DMALM_AREA_TEMATICA_FK_01         '; 
COMMENT ON COLUMN T_DMALM_PROJECT.ID_PROJECT IS 'ID_PROJECT                        '; 
COMMENT ON COLUMN T_DMALM_PROJECT.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN T_DMALM_PROJECT.SIGLA_PROJECT IS 'SIGLA_PROJECT                     '; 
COMMENT ON COLUMN T_DMALM_PROJECT.NOME_COMPLETO_PROJECT IS 'NOME_COMPLETO_PROJECT             '; 
COMMENT ON COLUMN T_DMALM_PROJECT.PATH_PROJECT IS 'PATH_PROJECT                      '; 
COMMENT ON COLUMN T_DMALM_PROJECT.SERVICE_MANAGERS IS 'SERVICE_MANAGERS                  '; 
COMMENT ON COLUMN T_DMALM_PROJECT.FL_ATTIVO IS 'FL_ATTIVO                         '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DT_CARICAMENTO IS 'DT_CARICAMENTO                    '; 
COMMENT ON COLUMN T_DMALM_PROJECT.TEMPLATE IS 'TEMPLATE                          '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DMALM_STRUTTURA_ORG_FK_02 IS 'DMALM_STRUTTURA_ORG_FK_02         '; 
COMMENT ON COLUMN T_DMALM_PROJECT.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_PROJECT.DATA_MODIFICA_PROJECT IS 'DATA_MODIFICA_PROJECT             '; 
CREATE UNIQUE INDEX PK_T_DMALM_PROJECT ON T_DMALM_PROJECT 
    ( 
     DMALM_PROJECT_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_PROJECT 
    ADD CONSTRAINT PK_T_DMALM_PROJECT PRIMARY KEY ( DMALM_PROJECT_PK ) 
    USING INDEX PK_T_DMALM_PROJECT ;
;
;
SPOOL OFF;
