SPOOL 142_T_DMALM_STATO_WORKITEM.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_STATO_WORKITEM 
    ( 
     DMALM_STATO_WORKITEM_PK NUMBER (16)  NOT NULL , 
     CD_STATO VARCHAR2 (50 BYTE) , 
     DS_STATO VARCHAR2 (50 BYTE) , 
     DT_CARICAMENTO DATE , 
     ORIGINE_STATO VARCHAR2 (50 BYTE) , 
     TEMPLATE VARCHAR2 (50 BYTE) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_STATO_WORKITEM IS 'T_DMALM_STATO_WORKITEM            ';
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.DMALM_STATO_WORKITEM_PK IS 'DMALM_STATO_WORKITEM_PK           '; 
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.CD_STATO IS 'CD_STATO                          '; 
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.DS_STATO IS 'DS_STATO                          '; 
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.DT_CARICAMENTO IS 'DT_CARICAMENTO                    '; 
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.ORIGINE_STATO IS 'ORIGINE_STATO                     '; 
COMMENT ON COLUMN T_DMALM_STATO_WORKITEM.TEMPLATE IS 'TEMPLATE                          '; 
CREATE UNIQUE INDEX PK_T_DMALM_STATO_WORKITEM ON T_DMALM_STATO_WORKITEM 
    ( 
     DMALM_STATO_WORKITEM_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_STATO_WORKITEM 
    ADD CONSTRAINT PK_T_DMALM_STATO_WORKITEM PRIMARY KEY ( DMALM_STATO_WORKITEM_PK ) 
    USING INDEX PK_T_DMALM_STATO_WORKITEM ;
SPOOL OFF;
