SPOOL 145_T_DMALM_TESTCASE.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_TESTCASE 
    ( 
     CD_TESTCASE VARCHAR2 (100 BYTE) , 
     DT_CREAZIONE_TESTCASE DATE , 
     DT_RISOLUZIONE_TESTCASE DATE , 
     DT_MODIFICA_TESTCASE DATE , 
     DT_CAMBIO_STATO_TESTCASE DATE , 
     MOTIVO_RISOLUZIONE_TESTCASE VARCHAR2 (255 BYTE) , 
     ID_AUTORE_TESTCASE VARCHAR2 (100 BYTE) , 
     DS_AUTORE_TESTCASE VARCHAR2 (100 BYTE) , 
     DT_SCADENZA_TESTCASE DATE , 
     TITOLO_TESTCASE VARCHAR2 (4000 BYTE) , 
     DMALM_TESTCASE_PK NUMBER (15)  NOT NULL , 
     DMALM_STRUTTURA_ORG_FK_01 NUMBER (15) , 
     DMALM_PROJECT_FK_02 NUMBER (15) , 
     DMALM_STATO_WORKITEM_FK_03 NUMBER (15) , 
     DMALM_TEMPO_FK_04 NUMBER (15) , 
     RANK_STATO_TESTCASE NUMBER , 
     DT_CARICAMENTO_TESTCASE DATE , 
     ID_REPOSITORY VARCHAR2 (20 BYTE) , 
     DT_STORICIZZAZIONE DATE , 
     RANK_STATO_TESTCASE_MESE NUMBER (5) , 
     DESCRIZIONE_TESTCASE CLOB , 
     DMALM_AREA_TEMATICA_FK_05 NUMBER (15) , 
     CODICE VARCHAR2 (200 BYTE) , 
     DATA_ESECUZIONE_TESTCASE TIMESTAMP , 
     NUMERO_TESTATA VARCHAR2 (200 BYTE) , 
     NUMERO_LINEA VARCHAR2 (200 BYTE) , 
     STG_PK VARCHAR2 (4000 BYTE) , 
     ANNULLATO VARCHAR2 (50 BYTE) , 
     DMALM_USER_FK_06 NUMBER (15) 
    ) 
        TABLESPACE "TS_ALM_SV"; 
COMMENT ON TABLE T_DMALM_TESTCASE IS 'T_DMALM_TESTCASE                  ';
COMMENT ON COLUMN T_DMALM_TESTCASE.CD_TESTCASE IS 'CD_TESTCASE                       '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_CREAZIONE_TESTCASE IS 'DT_CREAZIONE_TESTCASE             '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_RISOLUZIONE_TESTCASE IS 'DT_RISOLUZIONE_TESTCASE           '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_MODIFICA_TESTCASE IS 'DT_MODIFICA_TESTCASE              '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_CAMBIO_STATO_TESTCASE IS 'DT_CAMBIO_STATO_TESTCASE          '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.MOTIVO_RISOLUZIONE_TESTCASE IS 'MOTIVO_RISOLUZIONE_TESTCASE       '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.ID_AUTORE_TESTCASE IS 'ID_AUTORE_TESTCASE                '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DS_AUTORE_TESTCASE IS 'DS_AUTORE_TESTCASE                '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_SCADENZA_TESTCASE IS 'DT_SCADENZA_TESTCASE              '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.TITOLO_TESTCASE IS 'TITOLO_TESTCASE                   '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_TESTCASE_PK IS 'DMALM_TESTCASE_PK                 '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_STRUTTURA_ORG_FK_01 IS 'DMALM_STRUTTURA_ORG_FK_01         '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02               '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_TEMPO_FK_04 IS 'DMALM_TEMPO_FK_04                 '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.RANK_STATO_TESTCASE IS 'RANK_STATO_TESTCASE               '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_CARICAMENTO_TESTCASE IS 'DT_CARICAMENTO_TESTCASE           '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DT_STORICIZZAZIONE IS 'DT_STORICIZZAZIONE                '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.RANK_STATO_TESTCASE_MESE IS 'RANK_STATO_TESTCASE_MESE          '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DESCRIZIONE_TESTCASE IS 'DESCRIZIONE_TESTCASE              '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_AREA_TEMATICA_FK_05 IS 'DMALM_AREA_TEMATICA_FK_05         '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.CODICE IS 'CODICE                            '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DATA_ESECUZIONE_TESTCASE IS 'DATA_ESECUZIONE_TESTCASE          '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.NUMERO_TESTATA IS 'NUMERO_TESTATA                    '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.NUMERO_LINEA IS 'NUMERO_LINEA                      '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.STG_PK IS 'STG_PK                            '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.ANNULLATO IS 'ANNULLATO                         '; 
COMMENT ON COLUMN T_DMALM_TESTCASE.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06                  '; 
CREATE UNIQUE INDEX PK_T_DMALM_TESTCASE ON T_DMALM_TESTCASE 
    ( 
     DMALM_TESTCASE_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_TESTCASE 
    ADD CONSTRAINT PK_T_DMALM_TESTCASE PRIMARY KEY ( DMALM_TESTCASE_PK ) 
    USING INDEX PK_T_DMALM_TESTCASE ;
;
;
;
;
SPOOL OFF;
