SPOOL 147_T_DMALM_USER.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_USER 
    ( 
     ID_USER VARCHAR2 (4000 BYTE) , 
     INITIALS_USER VARCHAR2 (4000 BYTE) , 
     DISABLED_NOTIFICATION NUMBER (1) , 
     USER_NAME VARCHAR2 (4000 BYTE) , 
     DELETED NUMBER (1) , 
     USER_EMAIL VARCHAR2 (4000 BYTE) , 
     USER_AVATAR_FILENAME VARCHAR2 (4000 BYTE) , 
     DATA_CARICAMENTO TIMESTAMP , 
     DT_INIZIO_VALIDITA TIMESTAMP , 
     DT_FINE_VALIDITA TIMESTAMP , 
     DMALM_USER_PK NUMBER (15)  NOT NULL , 
     ID_REPOSITORY VARCHAR2 (10 BYTE) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE "TS_ALM_SV" 
        LOGGING; 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
COMMENT ON TABLE T_DMALM_USER IS 'T_DMALM_USER                      ';
COMMENT ON COLUMN T_DMALM_USER.ID_USER IS 'ID_USER                           '; 
COMMENT ON COLUMN T_DMALM_USER.INITIALS_USER IS 'INITIALS_USER                     '; 
COMMENT ON COLUMN T_DMALM_USER.DISABLED_NOTIFICATION IS 'DISABLED_NOTIFICATION             '; 
COMMENT ON COLUMN T_DMALM_USER.USER_NAME IS 'USER_NAME                         '; 
COMMENT ON COLUMN T_DMALM_USER.DELETED IS 'DELETED                           '; 
COMMENT ON COLUMN T_DMALM_USER.USER_EMAIL IS 'USER_EMAIL                        '; 
COMMENT ON COLUMN T_DMALM_USER.USER_AVATAR_FILENAME IS 'USER_AVATAR_FILENAME              '; 
COMMENT ON COLUMN T_DMALM_USER.DATA_CARICAMENTO IS 'DATA_CARICAMENTO                  '; 
COMMENT ON COLUMN T_DMALM_USER.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA                '; 
COMMENT ON COLUMN T_DMALM_USER.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA                  '; 
COMMENT ON COLUMN T_DMALM_USER.DMALM_USER_PK IS 'DMALM_USER_PK                     '; 
COMMENT ON COLUMN T_DMALM_USER.ID_REPOSITORY IS 'ID_REPOSITORY                     '; 
CREATE UNIQUE INDEX PK_T_DMALM_USER ON T_DMALM_USER 
    ( 
     DMALM_USER_PK ASC 
    ) 
    TABLESPACE "TS_ALM_SV" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
ALTER TABLE T_DMALM_USER 
    ADD CONSTRAINT PK_T_DMALM_USER PRIMARY KEY ( DMALM_USER_PK ) 
    USING INDEX PK_T_DMALM_USER ;
SPOOL OFF;
