SPOOL 196_TRIGGER_PRODOTTO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE OR REPLACE TRIGGER TRIGGER_PRODOTTO 
    BEFORE INSERT ON DMALM_PRODOTTO REFERENCING 
    NEW AS N 
    FOR EACH ROW 
DECLARE 
  err_msg VARCHAR2(200);
  err_code VARCHAR2(20);
  l_today_timestamp   TIMESTAMP := SYSTIMESTAMP;
  V_UO_PRODOTTO DMALM_PRODOTTO.DMALM_UNITAORGANIZZATIVA_FK_01%TYPE;
  CURSOR C1
  IS
    SELECT DMALM_UNITAORGANIZZATIVA_FK_01
    FROM DMALM_PRODOTTO prod
    WHERE prod.DMALM_PRODOTTO_PK = :N.DMALM_PRODOTTO_PK
    AND prod.DT_FINE_VALIDITA    =
      (SELECT MAX(p.dt_fine_validita)
      FROM dmalm_prodotto p
      WHERE p.DMALM_PRODOTTO_PK=prod.DMALM_PRODOTTO_PK
      )
  AND DMALM_UNITAORGANIZZATIVA_FK_01 ^= :N.DMALM_UNITAORGANIZZATIVA_FK_01
  and prod.SIGLA ^= 'Non presente';
  V_PROGETTO DMALM_PROJECT%ROWTYPE;
  CURSOR C2
  IS
    SELECT *
    FROM
      (SELECT *
      FROM DMALM_PROJECT PR
      WHERE SUBSTR(PR.SIGLA_PROJECT ,1,REGEXP_INSTR(PR.SIGLA_PROJECT,'$|\.',1,1)-1) = :N.SIGLA
      and PR.SIGLA_PROJECT is not null
      and PR.TEMPLATE = 'SVILUPPO'
	  and PR.DT_FINE_VALIDITA = TIMESTAMP '9999-12-31 00:00:00.0'
      ORDER BY PR.DT_FINE_VALIDITA DESC
      )
  WHERE ROWNUM =1;
  CURSOR C3
  IS
    SELECT *
    FROM
      (SELECT *
      FROM DMALM_PROJECT PR
      WHERE SUBSTR(PR.SIGLA_PROJECT ,1,REGEXP_INSTR(PR.SIGLA_PROJECT,'$|\.',1,1)-1) = :N.SIGLA
      AND PR.DMALM_STRUTTURA_ORG_FK_02 = 0
      and PR.DT_FINE_VALIDITA = TIMESTAMP '9999-12-31 00:00:00.0'
      )
  WHERE ROWNUM =1;
  
BEGIN
  insert into DMALM_LOG_DEBUG (OBJECT_TYPE,LOG_DEBUG,ACTION,ID,RELATED_OBJECT_NAME,ID_RELATED_OBJECT,DATA_CARICAMENTO)values('TRIGGER_PRODOTTO', 'INSERTING PRODOTTO RECORD WITH SIGLA: "'|| :N.SIGLA|| '" AND PK: "'||:N.DMALM_PRODOTTO_SEQ|| '"','INSERTING',:N.DMALM_PRODOTTO_SEQ, 'DMALM_PRODOTTO',0,l_today_timestamp);
	OPEN C1;
	FETCH C1 INTO V_UO_PRODOTTO;
	IF C1%NOTFOUND AND :N.SIGLA^='Non presente' THEN
		OPEN C3;
    FETCH C3 INTO V_PROGETTO;
		IF C3%FOUND and :N.DMALM_UNITAORGANIZZATIVA_FK_01^=0 THEN
			STORICIZZA_PROJ_PRODOTTO(V_PROGETTO,:N.DMALM_UNITAORGANIZZATIVA_FK_01);
		ELSE 
    null;
		END IF;
	ELSIF :N.SIGLA='Non presente' THEN 
    null;
  ELSE 
		LOOP
			EXIT WHEN C1%NOTFOUND;
			OPEN C2;
			LOOP
				FETCH C2 INTO V_PROGETTO;
				EXIT
				WHEN C2%NOTFOUND;
				STORICIZZA_PROJ_PRODOTTO(V_PROGETTO,:N.DMALM_UNITAORGANIZZATIVA_FK_01);
			END LOOP;
			CLOSE C2;
			FETCH C1 INTO V_UO_PRODOTTO;
		END LOOP ;
		CLOSE C1;
		
    END IF;
EXCEPTION
WHEN OTHERS THEN
    err_code := SQLCODE;
    err_msg := SUBSTR(SQLERRM, 1, 200);
  insert into DMALM_LOG_DEBUG (OBJECT_TYPE,
               LOG_DEBUG,
               ACTION,
               ID,
               RELATED_OBJECT_NAME,
               ID_RELATED_OBJECT,
               DATA_CARICAMENTO)
               values('TRIGGER_PRODOTTO',
               'EXCEPTION WITH SQLCODE: '||err_code||' AND MESSAGE ' ||err_msg,
               'EXCEPTION',
                V_UO_PRODOTTO, 
               null,
               0,
               l_today_timestamp);
RAISE;
END; 
/
SHOW ERRORS;
SPOOL OFF;