SPOOL 201_ALTER_TABLE_URI_LINKED_WI_PMEV_1_6.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
ALTER TABLE DMALM_LINKED_WORKITEMS ADD URI_WI_PADRE VARCHAR2(4000);
ALTER TABLE DMALM_LINKED_WORKITEMS ADD URI_WI_FIGLIO VARCHAR2(4000);
ALTER TABLE T_DMALM_LINKED_WORKITEMS ADD URI_WI_PADRE VARCHAR2(4000);
ALTER TABLE T_DMALM_LINKED_WORKITEMS ADD URI_WI_FIGLIO VARCHAR2(4000);
SPOOL OFF;