SPOOL 206_TOTAL_TEMP.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE GLOBAL TEMPORARY TABLE TOTAL_TEMP (
   STG_PK varchar2(4000),
   DMALM_PK decimal(15),
   TYPE varchar2(19),
   ID_REPOSITORY varchar2(20),
   CODICE varchar2(100),
   DT_STORICIZZAZIONE timestamp,
   URI                 VARCHAR2(4000 BYTE),
   RANK_STATO          NUMBER,
   PROJECT_FK          NUMBER(15),
   TITOLO              VARCHAR2(4000 BYTE)
) ON COMMIT PRESERVE ROWS;

CREATE INDEX IDX_TBL_TEMP ON TOTAL_TEMP(STG_PK);
CREATE INDEX IDX2_TBL_TEMP ON TOTAL_TEMP
(
  TYPE,
  CODICE,
  DT_STORICIZZAZIONE
);
COMMENT ON COLUMN TOTAL_TEMP.STG_PK				      IS 'STG_PK			 ' ;
COMMENT ON COLUMN TOTAL_TEMP.DMALM_PK                 IS 'DMALM_PK           ' ;
COMMENT ON COLUMN TOTAL_TEMP.TYPE                     IS 'TYPE               ' ;
COMMENT ON COLUMN TOTAL_TEMP.ID_REPOSITORY            IS 'ID_REPOSITORY      ' ;
COMMENT ON COLUMN TOTAL_TEMP.CODICE                   IS 'CODICE             ' ;
COMMENT ON COLUMN TOTAL_TEMP.DT_STORICIZZAZIONE       IS 'DT_STORICIZZAZIONE ' ;
COMMENT ON COLUMN TOTAL_TEMP.URI       IS 'URI' ;
COMMENT ON COLUMN TOTAL_TEMP.RANK_STATO       IS 'RANK_STATO' ;
COMMENT ON COLUMN TOTAL_TEMP.PROJECT_FK       IS 'PROJECT_FK' ;
COMMENT ON COLUMN TOTAL_TEMP.TITOLO       IS 'TITOLO' ;
SPOOL OFF;