SPOOL 214_DMALM_STG_MPS_RILASCI_VERBALI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_STG_MPS_RILASCI_VERBALI
(
  CODVERBALE            VARCHAR2(32 BYTE),
  IDVERBALEVALIDAZIONE  NUMBER(10),
  IDRILASCIO            NUMBER(10),
  IMPORTO               NUMBER,
)
 PCTFREE 10 
 PCTUSED 40 
 MAXTRANS 255 
 TABLESPACE TS_ALM 
 LOGGING 
 STORAGE ( 
   INITIAL 655360 
   NEXT 1048576 
   PCTINCREASE 0 
   MINEXTENTS 1 
   MAXEXTENTS 2147483645 
   FREELISTS 1 
   FREELIST GROUPS 1 
   BUFFER_POOL DEFAULT 
 ); 
COMMENT ON TABLE DMALM_STG_MPS_RILASCI_VERBALI IS 'DMALM_STG_MPS_RILASCI_VERBALI';
COMMENT ON COLUMN DMALM_STG_MPS_RILASCI_VERBALI.CODVERBALE           IS 'CODVERBALE          ' ;
COMMENT ON COLUMN DMALM_STG_MPS_RILASCI_VERBALI.IDVERBALEVALIDAZIONE IS 'IDVERBALEVALIDAZIONE' ;
COMMENT ON COLUMN DMALM_STG_MPS_RILASCI_VERBALI.IDRILASCIO           IS 'IDRILASCIO          ' ;
COMMENT ON COLUMN DMALM_STG_MPS_RILASCI_VERBALI.IMPORTO              IS 'IMPORTO             ' ;


    TABLESPACE TS_ALM 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING;
SPOOL OFF;