SPOOL 231_T_MPS_BO_RESPONSABILI_OFFERTA.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE T_MPS_BO_RESPONSABILI_OFFERTA
(
  IDCONTRATTO                    NUMBER(10),
  AM_NOME                        VARCHAR2(257 BYTE),
  AM_DATAFIRMA                   DATE,
  AM_FIRMATO                     CHAR(1 BYTE),
  SAM_NOME                       VARCHAR2(257 BYTE),
  SAM_DATAFIRMA                  DATE,
  SAM_FIRMATO                    CHAR(1 BYTE),
  VDG_NOME                       VARCHAR2(257 BYTE),
  VDG_DATAFIRMA                  DATE,
  VDG_FIRMATO                    CHAR(1 BYTE),
  DG_NOME                        VARCHAR2(257 BYTE),
  DG_DATAFIRMA                   DATE,
  DG_FIRMATO                     CHAR(1 BYTE),
  CD_NOME                        VARCHAR2(257 BYTE),
  CD_DATAFIRMA                   DATE,
  CD_FIRMATO                     CHAR(1 BYTE),
  COPERTINA_FIRMATA              VARCHAR2(4000 BYTE),
  DATA_FIRMA_COPERTINA           DATE,
  STATO_RAZIONALE                CHAR(1 BYTE),
  CONTROLLER                     VARCHAR2(257 BYTE),
  DATA_VERIFICA                  DATE,
  PROSSIMO_FIRMATARIO_RAZIONALE  VARCHAR2(257 BYTE),
  RAZIONALE_DIGITALE             CHAR(1 BYTE),
  NOTA_RAZIONALE                 VARCHAR2(4000 BYTE),
  MOTIVAZIONE_RIGETTO            VARCHAR2(4000 BYTE)
)
 PCTFREE 10 
 PCTUSED 40 
 MAXTRANS 255 
 TABLESPACE TS_ALM 
 LOGGING 
 STORAGE ( 
   INITIAL 655360 
   NEXT 1048576 
   PCTINCREASE 0 
   MINEXTENTS 1 
   MAXEXTENTS 2147483645 
   FREELISTS 1 
   FREELIST GROUPS 1 
   BUFFER_POOL DEFAULT 
 ); 
COMMENT ON TABLE T_MPS_BO_RESPONSABILI_OFFERTA IS 'T_MPS_BO_RESPONSABILI_OFFERTA';
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.IDCONTRATTO                   IS 'IDCONTRATTO                  ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.AM_NOME                       IS 'AM_NOME                      ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.AM_DATAFIRMA                  IS 'AM_DATAFIRMA                 ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.AM_FIRMATO                    IS 'AM_FIRMATO                   ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.SAM_NOME                      IS 'SAM_NOME                     ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.SAM_DATAFIRMA                 IS 'SAM_DATAFIRMA                ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.SAM_FIRMATO                   IS 'SAM_FIRMATO                  ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.VDG_NOME                      IS 'VDG_NOME                     ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.VDG_DATAFIRMA                 IS 'VDG_DATAFIRMA                ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.VDG_FIRMATO                   IS 'VDG_FIRMATO                  ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.DG_NOME                       IS 'DG_NOME                      ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.DG_DATAFIRMA                  IS 'DG_DATAFIRMA                 ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.DG_FIRMATO                    IS 'DG_FIRMATO                   ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.CD_NOME                       IS 'CD_NOME                      ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.CD_DATAFIRMA                  IS 'CD_DATAFIRMA                 ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.CD_FIRMATO                    IS 'CD_FIRMATO                   ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.COPERTINA_FIRMATA             IS 'COPERTINA_FIRMATA            ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.DATA_FIRMA_COPERTINA          IS 'DATA_FIRMA_COPERTINA         ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.STATO_RAZIONALE               IS 'STATO_RAZIONALE              ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.CONTROLLER                    IS 'CONTROLLER                   ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.DATA_VERIFICA                 IS 'DATA_VERIFICA                ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.PROSSIMO_FIRMATARIO_RAZIONALE IS 'PROSSIMO_FIRMATARIO_RAZIONALE' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.RAZIONALE_DIGITALE            IS 'RAZIONALE_DIGITALE           ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.NOTA_RAZIONALE                IS 'NOTA_RAZIONALE               ' ;
COMMENT ON COLUMN T_MPS_BO_RESPONSABILI_OFFERTA.MOTIVAZIONE_RIGETTO           IS 'MOTIVAZIONE_RIGETTO          ' ;
CREATE UNIQUE INDEX T_MPS_BO_RESPONS_OFFERTA_PK ON T_MPS_BO_RESPONSABILI_OFFERTA 
    ( 
     IDCONTRATTO ASC 
    ) 
    TABLESPACE TS_ALM 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING;
ALTER TABLE T_MPS_BO_RESPONSABILI_OFFERTA 
    ADD CONSTRAINT T_MPS_BO_RESPONS_OFFERTA_PK PRIMARY KEY ( IDCONTRATTO ) 
    USING INDEX T_MPS_BO_RESPONS_OFFERTA_PK;
SPOOL OFF;