SPOOL 233_T_MPS_BO_RILASCI_VERBALI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE T_MPS_BO_RILASCI_VERBALI
(
  CODVERBALE            VARCHAR2(32 BYTE),
  IDVERBALEVALIDAZIONE  NUMBER(10),
  IDRILASCIO            NUMBER(10),
  IMPORTO               NUMBER,
  RILASCI_VERBALI_PK    RAW(16)                 DEFAULT sys_guid()
)
 PCTFREE 10 
 PCTUSED 40 
 MAXTRANS 255 
 TABLESPACE TS_ALM 
 LOGGING 
 STORAGE ( 
   INITIAL 655360 
   NEXT 1048576 
   PCTINCREASE 0 
   MINEXTENTS 1 
   MAXEXTENTS 2147483645 
   FREELISTS 1 
   FREELIST GROUPS 1 
   BUFFER_POOL DEFAULT 
 ); 
COMMENT ON TABLE T_MPS_BO_RILASCI_VERBALI IS 'T_MPS_BO_RILASCI_VERBALI';
COMMENT ON COLUMN T_MPS_BO_RILASCI_VERBALI.CODVERBALE           IS 'CODVERBALE          ' ;
COMMENT ON COLUMN T_MPS_BO_RILASCI_VERBALI.IDVERBALEVALIDAZIONE IS 'IDVERBALEVALIDAZIONE' ;
COMMENT ON COLUMN T_MPS_BO_RILASCI_VERBALI.IDRILASCIO           IS 'IDRILASCIO          ' ;
COMMENT ON COLUMN T_MPS_BO_RILASCI_VERBALI.IMPORTO              IS 'IMPORTO             ' ;
COMMENT ON COLUMN T_MPS_BO_RILASCI_VERBALI.RILASCI_VERBALI_PK   IS 'RILASCI_VERBALI_PK  ' ;

CREATE UNIQUE INDEX T_MPS_BO_RILASCI_VERBALI_PK ON T_MPS_BO_RILASCI_VERBALI 
    ( 
     RILASCI_VERBALI_PK 
    ) 
    TABLESPACE TS_ALM 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING;
ALTER TABLE T_MPS_BO_RILASCI_VERBALI 
    ADD CONSTRAINT T_MPS_BO_RILASCI_VERBALI_PK PRIMARY KEY ( RILASCI_VERBALI_PK ) 
    USING INDEX T_MPS_BO_RILASCI_VERBALI_PK;	
SPOOL OFF;