SPOOL 244_DMALM_ASM_PRODOTTO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_ASM_PRODOTTO
(
  DMALM_ASM_PK                    NUMBER(16)    NOT NULL,
  DMALM_PRODOTTO_SEQ               NUMBER(15)    NOT NULL,
  DT_INIZIO_VALIDITA              TIMESTAMP(6)  NOT NULL,
  DT_FINE_VALIDITA                TIMESTAMP(6)  NOT NULL
)        
    PCTFREE 10 
    PCTUSED 40 
    MAXTRANS 255 
    TABLESPACE TS_ALM 
    LOGGING 
    STORAGE ( 
      INITIAL 655360 
      NEXT 1048576 
      PCTINCREASE 0 
      MINEXTENTS 1 
      MAXEXTENTS 2147483645 
      FREELISTS 1 
      FREELIST GROUPS 1 
      BUFFER_POOL DEFAULT 
    );
COMMENT ON TABLE DMALM_ASM_PRODOTTO IS 'DMALM_ASM_PRODOTTO';
COMMENT ON COLUMN DMALM_ASM_PRODOTTO.DMALM_ASM_PK IS 'DMALM_ASM_PK';
COMMENT ON COLUMN DMALM_ASM_PRODOTTO.DMALM_PRODOTTO_SEQ IS 'DMALM_PRODOTTO_SEQ';
COMMENT ON COLUMN DMALM_ASM_PRODOTTO.DT_INIZIO_VALIDITA IS 'DT_INIZIO_VALIDITA';
COMMENT ON COLUMN DMALM_ASM_PRODOTTO.DT_FINE_VALIDITA IS 'DT_FINE_VALIDITA';
CREATE UNIQUE INDEX DMALM_ASM_PRODOTTO_PK ON DMALM_ASM_PRODOTTO 
    ( 
     DMALM_ASM_PK, DMALM_PRODOTTO_SEQ, DT_INIZIO_VALIDITA
    ) 
    TABLESPACE TS_ALM 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING;
ALTER TABLE DMALM_ASM_PRODOTTO 
    ADD CONSTRAINT DMALM_ASM_PRODOTTO_PK PRIMARY KEY ( DMALM_ASM_PK, DMALM_PRODOTTO_SEQ, DT_INIZIO_VALIDITA ) 
    USING INDEX DMALM_ASM_PRODOTTO_PK;
ALTER TABLE DMALM_ASM_PRODOTTO 
    ADD CONSTRAINT DMALM_ASM_PRODOTTO_FK_01 FOREIGN KEY 
    ( 
     DMALM_ASM_PK
    ) 
    REFERENCES DMALM_ASM 
    ( 
     DMALM_ASM_PK
    ) 
    NOT DEFERRABLE;
ALTER TABLE DMALM_ASM_PRODOTTO 
    ADD CONSTRAINT DMALM_ASM_PRODOTTO_FK_02 FOREIGN KEY 
    ( 
     DMALM_PRODOTTO_SEQ
    ) 
    REFERENCES DMALM_PRODOTTO 
    ( 
     DMALM_PRODOTTO_SEQ
    ) 
    NOT DEFERRABLE;
SPOOL OFF;