SPOOL 253_DMALM_STG_EL_FUNZIONALITA.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_STG_EL_FUNZIONALITA 
 ( 
  DMALM_STG_FUNZIONALITA_PK NUMBER(15)           NOT NULL,
  ID_FUNZIONALITA_EDMA      VARCHAR2(100 BYTE)   NOT NULL,
  ID_EDMA_PADRE             VARCHAR2(100 BYTE),
  ID_FUNZIONALITA           VARCHAR2(100 BYTE),
  TIPO_OGGETTO              VARCHAR2(12 BYTE),
  SIGLA_PRODOTTO            VARCHAR2(4000 BYTE),
  SIGLA_SOTTOSISTEMA        VARCHAR2(4000 BYTE),
  SIGLA_MODULO              VARCHAR2(4000 BYTE),
  SIGLA_FUNZIONALITA        VARCHAR2(4000 BYTE),
  NOME                      VARCHAR2(4000 BYTE),
  DS_FUNZIONALITA           VARCHAR2(4000 BYTE),
  ANNULLATO                 VARCHAR2(2 BYTE),
  DT_ANNULLAMENTO           VARCHAR2(8 BYTE),
  CATEGORIA                 VARCHAR2(4000 BYTE),
  LINGUAGGI                 VARCHAR2(4000 BYTE),
  TIPI_ELABORAZIONE         VARCHAR2(4000 BYTE),
  DT_CARICAMENTO            DATE
 ) 
 TABLESPACE "TS_ALM"; 
COMMENT ON TABLE DMALM_STG_EL_FUNZIONALITA IS 'DMALM_STG_EL_FUNZIONALITA';
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.DMALM_STG_FUNZIONALITA_PK IS 'DMALM_STG_FUNZIONALITA_PK'; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.ID_FUNZIONALITA_EDMA      IS 'ID_FUNZIONALITA_EDMA     '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.ID_EDMA_PADRE             IS 'ID_EDMA_PADRE            '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.ID_FUNZIONALITA           IS 'ID_FUNZIONALITA          '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.TIPO_OGGETTO              IS 'TIPO_OGGETTO             '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.SIGLA_PRODOTTO            IS 'SIGLA_PRODOTTO           '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.SIGLA_SOTTOSISTEMA        IS 'SIGLA_SOTTOSISTEMA       '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.SIGLA_MODULO              IS 'SIGLA_MODULO             '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.SIGLA_FUNZIONALITA        IS 'SIGLA_FUNZIONALITA       '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.NOME                      IS 'NOME                     '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.DS_FUNZIONALITA           IS 'DS_FUNZIONALITA          '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.ANNULLATO                 IS 'ANNULLATO                '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.DT_ANNULLAMENTO           IS 'DT_ANNULLAMENTO          '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.CATEGORIA                 IS 'CATEGORIA                '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.LINGUAGGI                 IS 'LINGUAGGI                '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.TIPI_ELABORAZIONE         IS 'TIPI_ELABORAZIONE        '; 
COMMENT ON COLUMN DMALM_STG_EL_FUNZIONALITA.DT_CARICAMENTO            IS 'DT_CARICAMENTO           '; 

CREATE UNIQUE INDEX DMALM_STG_EL_FUNZIONALITA_PK ON DMALM_STG_EL_FUNZIONALITA
(DMALM_STG_FUNZIONALITA_PK)
    TABLESPACE "TS_ALM" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
	
ALTER TABLE DMALM_STG_EL_FUNZIONALITA ADD (
  CONSTRAINT DMALM_STG_EL_FUNZIONALITA_PK
  PRIMARY KEY
  (DMALM_STG_FUNZIONALITA_PK)
  USING INDEX DMALM_STG_EL_FUNZIONALITA_PK);
SPOOL OFF;
