SPOOL 262_DMALM_EL_MODULI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_EL_MODULI 
 ( 
  DMALM_MODULO_PK           NUMBER(15)           NOT NULL,
  ID_MODULO_EDMA            VARCHAR2(100 BYTE),
  ID_MODULO_EDMA_PADRE      VARCHAR2(100 BYTE),
  ID_MODULO                 VARCHAR2(100 BYTE),
  TIPO_OGGETTO              VARCHAR2(1 BYTE),
  SIGLA_PRODOTTO            VARCHAR2(500 BYTE),
  SIGLA_SOTTOSISTEMA        VARCHAR2(500 BYTE),
  SIGLA_MODULO              VARCHAR2(500 BYTE),
  NOME                      VARCHAR2(500 BYTE),
  DS_MODULO                 VARCHAR2(4000 BYTE),
  ANNULLATO                 VARCHAR2(2 BYTE),
  DT_ANNULLAMENTO           DATE,
  RESPONSABILE              VARCHAR2(4000 BYTE),
  SOTTOSISTEMA              VARCHAR2(4000 BYTE),
  TECNOLOGIE                VARCHAR2(4000 BYTE),
  TIPO_MODULO               VARCHAR2(4000 BYTE),
  DT_CARICAMENTO            DATE,
  DMALM_PERSONALE_FK_01     NUMBER(15),
  DMALM_PRODOTTO_FK_02      NUMBER(15),
  DT_INIZIO_VALIDITA        DATE,
  DT_FINE_VALIDITA          DATE
 ) 
 TABLESPACE "TS_ALM"; 
COMMENT ON TABLE DMALM_EL_MODULI IS 'DMALM_EL_MODULI';
COMMENT ON COLUMN DMALM_EL_MODULI.DMALM_MODULO_PK       IS 'DMALM_MODULO_PK      '; 
COMMENT ON COLUMN DMALM_EL_MODULI.ID_MODULO_EDMA        IS 'ID_MODULO_EDMA       '; 
COMMENT ON COLUMN DMALM_EL_MODULI.ID_MODULO_EDMA_PADRE  IS 'ID_MODULO_EDMA_PADRE '; 
COMMENT ON COLUMN DMALM_EL_MODULI.ID_MODULO             IS 'ID_MODULO            '; 
COMMENT ON COLUMN DMALM_EL_MODULI.TIPO_OGGETTO          IS 'TIPO_OGGETTO         '; 
COMMENT ON COLUMN DMALM_EL_MODULI.SIGLA_PRODOTTO        IS 'SIGLA_PRODOTTO       '; 
COMMENT ON COLUMN DMALM_EL_MODULI.SIGLA_SOTTOSISTEMA    IS 'SIGLA_SOTTOSISTEMA   '; 
COMMENT ON COLUMN DMALM_EL_MODULI.SIGLA_MODULO          IS 'SIGLA_MODULO         '; 
COMMENT ON COLUMN DMALM_EL_MODULI.NOME                  IS 'NOME                 '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DS_MODULO             IS 'DS_MODULO            '; 
COMMENT ON COLUMN DMALM_EL_MODULI.ANNULLATO             IS 'ANNULLATO            '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DT_ANNULLAMENTO       IS 'DT_ANNULLAMENTO      '; 
COMMENT ON COLUMN DMALM_EL_MODULI.RESPONSABILE          IS 'RESPONSABILE         '; 
COMMENT ON COLUMN DMALM_EL_MODULI.SOTTOSISTEMA          IS 'SOTTOSISTEMA         '; 
COMMENT ON COLUMN DMALM_EL_MODULI.TECNOLOGIE            IS 'TECNOLOGIE           '; 
COMMENT ON COLUMN DMALM_EL_MODULI.TIPO_MODULO           IS 'TIPO_MODULO          '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DT_CARICAMENTO        IS 'DT_CARICAMENTO       '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DMALM_PERSONALE_FK_01 IS 'DMALM_PERSONALE_FK_01'; 
COMMENT ON COLUMN DMALM_EL_MODULI.DMALM_PRODOTTO_FK_02  IS 'DMALM_PRODOTTO_FK_02 '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DT_INIZIO_VALIDITA    IS 'DT_INIZIO_VALIDITA   '; 
COMMENT ON COLUMN DMALM_EL_MODULI.DT_FINE_VALIDITA      IS 'DT_FINE_VALIDITA     '; 

CREATE UNIQUE INDEX DMALM_EL_MODULI_PK ON DMALM_EL_MODULI
(DMALM_MODULO_PK)
    TABLESPACE "TS_ALM" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
	
ALTER TABLE DMALM_EL_MODULI ADD (
  CONSTRAINT DMALM_EL_MODULI_PK
  PRIMARY KEY
  (DMALM_MODULO_PK)
  USING INDEX DMALM_EL_MODULI_PK);

ALTER TABLE DMALM_EL_MODULI ADD (
  CONSTRAINT DMALM_EL_PERSONALE_FK_01 
  FOREIGN KEY (DMALM_PERSONALE_FK_01) 
  REFERENCES DMALM_EL_PERSONALE (DMALM_PERSONALE_PK));  
SPOOL OFF;
