SPOOL 264_DMALM_EL_AMBIENTE_TECNOLOGICO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_EL_AMBIENTE_TECNOLOGICO 
 ( 
  DMALM_AMBIENTE_TECNOLOGICO_PK   NUMBER(15)          NOT NULL,
  ID_AMB_TECNOLOGICO_EDMA         VARCHAR2(100 BYTE)  NOT NULL,
  ID_AMB_TECNOLOGICO_EDMA_PADRE   VARCHAR2(100 BYTE),
  ID_AMB_TECNOLOGICO              VARCHAR2(100 BYTE),
  SIGLA_PRODOTTO                  VARCHAR2(4000 BYTE),
  SIGLA_MODULO                    VARCHAR2(4000 BYTE),
  NOME                            VARCHAR2(4000 BYTE),
  ARCHITETTURA                    VARCHAR2(4000 BYTE),
  INFRASTRUTTURA                  VARCHAR2(4000 BYTE),
  SISTEMA_OPERATIVO               VARCHAR2(4000 BYTE),
  TIPO_LAYER                      VARCHAR2(4000 BYTE),
  VERSIONE_SO                     VARCHAR2(4000 BYTE),
  DS_AMBIENTE_TECNOLOGICO         VARCHAR2(4000 BYTE),
  DT_CARICAMENTO                  DATE,
  ANNULLATO                       VARCHAR2(2 BYTE),
  DT_ANNULLAMENTO                 DATE,
  DMALM_PRODOTTO_FK_01            NUMBER(15),
  DMALM_MODULO_FK_02              NUMBER(15),
  DT_INIZIO_VALIDITA              DATE,
  DT_FINE_VALIDITA                DATE
 ) 
 TABLESPACE "TS_ALM"; 
COMMENT ON TABLE DMALM_EL_AMBIENTE_TECNOLOGICO IS 'DMALM_EL_AMBIENTE_TECNOLOGICO';
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DMALM_AMBIENTE_TECNOLOGICO_PK  IS 'DMALM_AMBIENTE_TECNOLOGICO_PK '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.ID_AMB_TECNOLOGICO_EDMA       IS 'ID_AMB_TECNOLOGICO_EDMA      '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.ID_AMB_TECNOLOGICO_EDMA_PADRE IS 'ID_AMB_TECNOLOGICO_EDMA_PADRE'; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.ID_AMB_TECNOLOGICO            IS 'ID_AMB_TECNOLOGICO           '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.SIGLA_PRODOTTO                IS 'SIGLA_PRODOTTO               '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.SIGLA_MODULO                  IS 'SIGLA_MODULO                 '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.NOME                          IS 'NOME                         '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.ARCHITETTURA                  IS 'ARCHITETTURA                 '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.INFRASTRUTTURA                IS 'INFRASTRUTTURA               '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.SISTEMA_OPERATIVO             IS 'SISTEMA_OPERATIVO            '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.TIPO_LAYER                    IS 'TIPO_LAYER                   '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.VERSIONE_SO                   IS 'VERSIONE_SO                  '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DS_AMBIENTE_TECNOLOGICO       IS 'DS_AMBIENTE_TECNOLOGICO      '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DT_CARICAMENTO                IS 'DT_CARICAMENTO               '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.ANNULLATO                     IS 'ANNULLATO                    '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DT_ANNULLAMENTO               IS 'DT_ANNULLAMENTO              '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DMALM_PRODOTTO_FK_01          IS 'DMALM_PRODOTTO_FK_01         '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DMALM_MODULO_FK_02            IS 'DMALM_MODULO_FK_02           '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DT_INIZIO_VALIDITA            IS 'DT_INIZIO_VALIDITA           '; 
COMMENT ON COLUMN DMALM_EL_AMBIENTE_TECNOLOGICO.DT_FINE_VALIDITA              IS 'DT_FINE_VALIDITA             '; 

CREATE UNIQUE INDEX DMALM_EL_AMBIENTE_TECNO_PK ON DMALM_EL_AMBIENTE_TECNOLOGICO
(DMALM_AMBIENTE_TECNOLOGICO_PK)
    TABLESPACE "TS_ALM" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
	
ALTER TABLE DMALM_EL_AMBIENTE_TECNOLOGICO ADD (
  CONSTRAINT DMALM_EL_AMBIENTE_TECNO_PK
  PRIMARY KEY
  (DMALM_AMBIENTE_TECNOLOGICO_PK)
  USING INDEX DMALM_EL_AMBIENTE_TECNO_PK);
SPOOL OFF;
