SPOOL 280_DMALM_PARAM_DELETE_ESITI.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_PARAM_DELETE_ESITI 
 ( 
  ID                 NUMBER                     NOT NULL,
  DT_ESECUZIONE_OP   DATE                       NOT NULL,
  COD_OPERAZIONE     VARCHAR2(50 BYTE)          NOT NULL,
  ENTITA             VARCHAR2(50 BYTE)          NOT NULL,
  DATA_DA            DATE                       NOT NULL,
  DATA_A             DATE                       NOT NULL,
  CANC_TUTTO_DT_DA   DATE,
  CANC_TUTTO_DT_A    DATE,
  ENTITA_TARGET      VARCHAR2(50 BYTE),
  ENTITA_SORGENTE    VARCHAR2(50 BYTE),
  DT_CARICAMENTO     DATE,
  DT_ESEC_EFFETTIVA  TIMESTAMP(6)
 ) 
 TABLESPACE "TS_ALM"; 
COMMENT ON TABLE DMALM_PARAM_DELETE_ESITI IS 'DMALM_PARAM_DELETE_ESITI';
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.ID                IS 'ID               '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.DT_ESECUZIONE_OP  IS 'DT_ESECUZIONE_OP '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.COD_OPERAZIONE    IS 'COD_OPERAZIONE   '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.ENTITA            IS 'ENTITA           '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.DATA_DA           IS 'DATA_DA          '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.DATA_A            IS 'DATA_A           '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.CANC_TUTTO_DT_DA  IS 'CANC_TUTTO_DT_DA '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.CANC_TUTTO_DT_A   IS 'CANC_TUTTO_DT_A  '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.ENTITA_TARGET     IS 'ENTITA_TARGET    '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.ENTITA_SORGENTE   IS 'ENTITA_SORGENTE  '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.DT_CARICAMENTO    IS 'DT_CARICAMENTO   '; 
COMMENT ON COLUMN DMALM_PARAM_DELETE_ESITI.DT_ESEC_EFFETTIVA IS 'DT_ESEC_EFFETTIVA'; 

CREATE UNIQUE INDEX DMALM_PARAM_DELETE_ESITI_PK ON DMALM_PARAM_DELETE_ESITI
(ID)
    TABLESPACE "TS_ALM" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 
	
ALTER TABLE DMALM_PARAM_DELETE_ESITI ADD (
  CONSTRAINT DMALM_PARAM_DELETE_ESITI_PK
  PRIMARY KEY
  (ID)
  USING INDEX DMALM_PARAM_DELETE_ESITI_PK);
SPOOL OFF;
