SPOOL 296_T_DMALM_TEMPLATE_DEMAND.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE T_DMALM_TEMPLATE_DEMAND
(
  ID_FILIERA      NUMBER(6)                     NOT NULL,
  LIVELLO         NUMBER(6)                     NOT NULL,
  SOTTOLIVELLO    NUMBER(6),
  FK_WI           NUMBER(16)                    NOT NULL,
  CODICE_WI       VARCHAR2(100 BYTE),
  TIPO_WI         VARCHAR2(100 BYTE),
  ID_REPOSITORY   VARCHAR2(20 BYTE),
  URI_WI          VARCHAR2(4000 BYTE),
  CODICE_PROJECT  VARCHAR2(100 BYTE),
  RUOLO           VARCHAR2(100 BYTE),
  DT_CARICAMENTO  TIMESTAMP(6)                  NOT NULL
)
TABLESPACE "TS_ALM"; 

COMMENT ON TABLE T_DMALM_TEMPLATE_DEMAND IS 'T_DMALM_TEMPLATE_DEMAND';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.ID_FILIERA IS 'ID_FILIERA';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.LIVELLO IS 'LIVELLO';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.SOTTOLIVELLO IS 'SOTTOLIVELLO';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.FK_WI IS 'FK_WI';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.CODICE_WI IS 'CODICE_WI';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.TIPO_WI IS 'TIPO_WI';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.ID_REPOSITORY IS 'ID_REPOSITORY';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.URI_WI IS 'URI_WI';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.CODICE_PROJECT IS 'CODICE_PROJECT';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.RUOLO IS 'RUOLO';
COMMENT ON COLUMN T_DMALM_TEMPLATE_DEMAND.DT_CARICAMENTO IS 'DT_CARICAMENTO';

CREATE UNIQUE INDEX T_DMALM_TEMPLATE_DEMAND_PK ON T_DMALM_TEMPLATE_DEMAND
(ID_FILIERA, LIVELLO)
TABLESPACE "TS_ALM" 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING; 

ALTER TABLE T_DMALM_TEMPLATE_DEMAND ADD (
  CONSTRAINT T_DMALM_TEMPLATE_DEMAND_PK
  PRIMARY KEY
  (ID_FILIERA, LIVELLO)
  USING INDEX T_DMALM_TEMPLATE_DEMAND_PK);
SPOOL OFF;
