SPOOL 312_V_REL_INT_TECNICA_SVILUPPO.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;SET SQLBLANKLINES ON;
CREATE OR REPLACE FORCE VIEW V_REL_INT_TECNICA_SVILUPPO
(
   FK_WI_INT_TECNICA,
   TIPO_WI_INT_TECNICA,
   FK_WI_SVILUPPO,
   TIPO_WI_SVILUPPO
)
AS
(select lw.FK_WI_PADRE, lw.TIPO_WI_PADRE, lw.FK_WI_FIGLIO, lw.TIPO_WI_FIGLIO
 from DMALM_LINKED_WORKITEMS lw
 join DMALM_TEMPLATE_INT_TECNICA tit on lw.FK_WI_PADRE = tit.fk_wi
 join DMALM_TEMPLATE_SVILUPPO ts on lw.FK_WI_FIGLIO = ts.fk_wi
 union
 select lw.FK_WI_FIGLIO, lw.TIPO_WI_FIGLIO, lw.FK_WI_PADRE, lw.TIPO_WI_PADRE
 from DMALM_LINKED_WORKITEMS lw
 join DMALM_TEMPLATE_INT_TECNICA tit on lw.FK_WI_FIGLIO = tit.fk_wi
 join DMALM_TEMPLATE_SVILUPPO ts on lw.FK_WI_PADRE = ts.fk_wi);
SPOOL OFF;
