SPOOL 317_DMALM_USER_EL_PERSONALE.log
SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_USER_EL_PERSONALE (
    ID_USER VARCHAR2(4000) NOT NULL,
    DMALM_PERSONALE_PK NUMBER(15, 0) NOT NULL,
    DT_CARICAMENTO DATE,
    CONSTRAINTS PK_USER_EL_PERSONALE PRIMARY KEY (ID_USER, DMALM_PERSONALE_PK),
    CONSTRAINTS FK_DMALM_PERSONALE_PK FOREIGN KEY (DMALM_PERSONALE_PK) REFERENCES DMALM_EL_PERSONALE(DMALM_PERSONALE_PK)
) TABLESPACE "TS_ALM_SV";
SPOOL OFF;
