SPOOL 318_DMALM_RICHIESTA_SUPPORTO.log

SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
  CREATE TABLE DMALM_RICHIESTA_SUPPORTO 
   (	ID_REPOSITORY VARCHAR2(20 BYTE), 
	URI_RICHIESTA_SUPPORTO VARCHAR2(4000 BYTE), 
	DMALM_RICH_SUPPORTO_PK NUMBER(15,0), 
	STG_PK VARCHAR2(4000 BYTE), 
	DMALM_PROJECT_FK_02 NUMBER(15,0), 
	DMALM_USER_FK_06 NUMBER(15,0), 
	ID_RICHIESTA_SUPPORTO VARCHAR2(250 BYTE), 
	DATA_RISOLUZIONE_RICH_SUPPORTO TIMESTAMP (6), 
	NR_GIORNI_FESTIVI NUMBER(8,0), 
	TEMPO_TOT_RICH_SUPPORTO NUMBER(8,2), 
	DMALM_STATO_WORKITEM_FK_03 NUMBER(15,0), 
	DATA_CREAZ_RICH_SUPPORTO TIMESTAMP (6), 
	DATA_MODIFICA_RECORD TIMESTAMP (6), 
	DATA_CHIUS_RICH_SUPPORTO TIMESTAMP (6), 
	USERID_RICH_SUPPORTO VARCHAR2(4000 BYTE), 
	NOME_RICH_SUPPORTO VARCHAR2(4000 BYTE), 
	MOTIVO_RISOLUZIONE VARCHAR2(4000 BYTE), 
	SEVERITY_RICH_SUPPORTO VARCHAR2(4000 BYTE), 
	DESCRIZIONE_RICH_SUPPORTO VARCHAR2(4000 BYTE), 
	NUMERO_TESTATA_RDI VARCHAR2(4000 BYTE), 
	RANK_STATO_RICH_SUPPORTO NUMBER(5,0), 
	DATA_CAMBIO_STATO_RIC_SUPP TIMESTAMP (6), 
	DATA_DISPONIBILITA TIMESTAMP (6), 
	PRIORITY_RICH_SUPPORTO VARCHAR2(4000 BYTE), 
	ANNULLATO VARCHAR2(50 BYTE), 
	DATA_ANNULLAMENTO TIMESTAMP (6), 
	DATA_STORICIZZAZIONE TIMESTAMP (6), 
	DATA_CARICAMENTO TIMESTAMP (6), 
	CODICE_AREA VARCHAR2(4000 BYTE), 
	CODICE_PRODOTTO VARCHAR2(4000 BYTE), 
	DATA_SCADENZA TIMESTAMP (6), 
	TIMESPENT FLOAT(126), 
	 CONSTRAINT RICHIESTA_SUPPORTO_PK PRIMARY KEY (DMALM_RICH_SUPPORTO_PK)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE TS_ALM_SV  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING

   TABLESPACE TS_ALM_SV ;
   
    
COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.ID_REPOSITORY IS 'ID_REPOSITORY     ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.URI_RICHIESTA_SUPPORTO IS 'URI_RICHIESTA_SUPPORTO                ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DMALM_RICH_SUPPORTO_PK IS 'DMALM_RICH_SUPPORTO_PK           ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.STG_PK IS 'STG_PK';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DMALM_PROJECT_FK_02 IS 'DMALM_PROJECT_FK_02  ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DMALM_USER_FK_06 IS 'DMALM_USER_FK_06         ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.ID_RICHIESTA_SUPPORTO IS 'ID_RICHIESTA_SUPPORTO      ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_RISOLUZIONE_RICH_SUPPORTO IS 'DATA_RISOLUZIONE_RICH_SUPPORTO                   ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.NR_GIORNI_FESTIVI IS 'NR_GIORNI_FESTIVI                ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.TEMPO_TOT_RICH_SUPPORTO IS 'TEMPO_TOT_RICH_SUPPORTO        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DMALM_STATO_WORKITEM_FK_03 IS 'DMALM_STATO_WORKITEM_FK_03        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_CREAZ_RICH_SUPPORTO IS 'DATA_CREAZ_RICH_SUPPORTO                   ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_MODIFICA_RECORD IS 'DATA_MODIFICA_RECORD                ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_CHIUS_RICH_SUPPORTO IS 'DATA_CHIUS_RICH_SUPPORTO              ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.USERID_RICH_SUPPORTO IS 'USERID_RICH_SUPPORTO         ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.NOME_RICH_SUPPORTO IS 'NOME_RICH_SUPPORTO         ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.MOTIVO_RISOLUZIONE IS 'MOTIVO_RISOLUZIONE               ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.SEVERITY_RICH_SUPPORTO IS 'SEVERITY_RICH_SUPPORTO                ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DESCRIZIONE_RICH_SUPPORTO IS 'DESCRIZIONE_RICH_SUPPORTO           ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.NUMERO_TESTATA_RDI IS 'NUMERO_TESTATA_RDI                ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.RANK_STATO_RICH_SUPPORTO IS 'RANK_STATO_RICH_SUPPORTO          ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_CAMBIO_STATO_RIC_SUPP IS 'DATA_CAMBIO_STATO_RIC_SUPP         ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_DISPONIBILITA IS 'DATA_DISPONIBILITA     ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.PRIORITY_RICH_SUPPORTO IS 'PRIORITY_RICH_SUPPORTO       ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.ANNULLATO IS 'ANNULLATO              ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_ANNULLAMENTO IS 'DATA_ANNULLAMENTO        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_STORICIZZAZIONE IS 'DATA_STORICIZZAZIONE        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_CARICAMENTO IS 'DATA_CARICAMENTO        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.CODICE_AREA IS 'CODICE_AREA        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.CODICE_PRODOTTO IS 'CODICE_PRODOTTO        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.DATA_SCADENZA IS 'DATA_SCADENZA        ';
   COMMENT ON COLUMN DMALM_RICHIESTA_SUPPORTO.TIMESPENT IS 'TIMESPENT        ';
   COMMENT ON TABLE DMALM_RICHIESTA_SUPPORTO  IS 'DMALM_RICHIESTA_SUPPORTO';  
   
SPOOL OFF;
