--STAGING
create or replace TYPE "DM_ALMSTGCALIPSOSCHEDASERVTYPE" as object(
    "Codice servizio" VARCHAR2(500),
	"Servizio di business" VARCHAR2(500),
	"Ambito" VARCHAR2(500),
	"Cliente" VARCHAR2(500),
	"Responsabile di Struttura" VARCHAR2(500),
	"Responsabile del Servizio" VARCHAR2(500),
	"Responsabile di Gestione" VARCHAR2(500),
	"Referente di Gestione" VARCHAR2(500),
	"Referente dell applicazione" VARCHAR2(500),
	"Software a supporto" VARCHAR2(500),
	"Ambito manutenzione ordinar sw" VARCHAR2(500),
	"Tipologia Incarico" VARCHAR2(500),
	"Scheda Incarico" VARCHAR2(500),
	"Stato del servizio" VARCHAR2(500),
	"Tipologia Infrastruttura" VARCHAR2(500),
	"Classe di servizio infrstrttrl" VARCHAR2(500),
	"Ambito ASSI e GEST per RL" VARCHAR2(500),
	"Data Ultimo Aggiornamento" VARCHAR2(500)
);

CREATE TABLE DM_ALM_STG_CALIPSO_SCHEDA_SERV (
	"Codice servizio" VARCHAR2(500),
	"Servizio di business" VARCHAR2(500),
	"Ambito" VARCHAR2(500),
	"Cliente" VARCHAR2(500),
	"Responsabile di Struttura" VARCHAR2(500),
	"Responsabile del Servizio" VARCHAR2(500),
	"Responsabile di Gestione" VARCHAR2(500),
	"Referente di Gestione" VARCHAR2(500),
	"Referente dell applicazione" VARCHAR2(500),
	"Software a supporto" VARCHAR2(500),
	"Ambito manutenzione ordinar sw" VARCHAR2(500),
	"Tipologia Incarico" VARCHAR2(500),
	"Scheda Incarico" VARCHAR2(500),
	"Stato del servizio" VARCHAR2(500),
	"Tipologia Infrastruttura" VARCHAR2(500),
	"Classe di servizio infrstrttrl" VARCHAR2(500),
	"Ambito ASSI e GEST per RL" VARCHAR2(500),
	"Data Ultimo Aggiornamento" VARCHAR2(500)
);

CREATE SEQUENCE  DMALM_CALIPSO_AMBITO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_AMBITO (
    DMALM_CALIPSO_AMBITO_PK NUMBER(15,0) PRIMARY KEY,
    DESC_NOME_AMBITO VARCHAR2(200),
	DESC_NATURA_AMBITO VARCHAR2(200)
);

CREATE TABLE DMALM_CALIPSO_STATO_SERVIZIO (
    DMALM_CALIPSO_STATO_SERVZ_PK VARCHAR2(200) PRIMARY KEY,
	DESC_STATO_SERVIZIO VARCHAR2(200)
);

CREATE TABLE DMALM_CALIPSO_TIPLG_STRUTTURA (
    DMALM_CALIPSO_TIPLG_STRUTTR_PK VARCHAR2(200) PRIMARY KEY,
	DESC_TIPOLOGIA_STRUTTURA VARCHAR2(200)
);

CREATE TABLE DMALM_CALIPSO_CLASSE_SERVIZIO (
    DMALM_CALIPSO_CLASSE_SERVZ_PK VARCHAR2(200) PRIMARY KEY,
    DESC_CALIPSO_CLASSE_SERVIZIO VARCHAR2(200)
);

/*CREATE SEQUENCE  DMALM_CALIPSO_TIPLG_INCRC_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_TIPLG_INCARICO (
    DMALM_CALIPSO_TIPLG_INCAR_PK NUMBER(15,0) PRIMARY KEY,
    DESC_CALIPSO_TIPLG_INCARICO VARCHAR2(200)
);*/

/*CREATE SEQUENCE  DMALM_CALIPSO_SCHEDA_INCRC_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_SCHEDA_INCARICO (
    DMALM_CALIPSO_SCHEDA_INCAR_PK NUMBER(15,0) PRIMARY KEY,
    DESC_CALIPSO_SCHEDA_INCARICO VARCHAR2(200)
);*/

/*CREATE SEQUENCE  DMALM_CALIPSO_AMBITO_AS_GE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_AMBITO_AS_GE (
    DMALM_CALIPSO_AMBT_AS_GE_PK NUMBER(15,0) PRIMARY KEY,
    DESC_CALIPSO_AMBT_AS_GE VARCHAR2(200)
);*/
/*CREATE TABLE DMALM_CALIPSO_STR_RIF_LISPA (
	DMALM_CALIPSO_STR_RIF_LISPA_PK VARCHAR2(200) PRIMARY KEY,
    DESC_CALIPSO_STR_RIF_LISPA VARCHAR2(200)
);
CREATE SEQUENCE  DMALM_CALIPSO_SW_SUPPORTO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_SW_SUPPORTO (
    DMALM_CALIPSO_SW_SUPPORTO_PK NUMBER(15,0) PRIMARY KEY,
    DESC_CALIPSO_SW_SUPPORTO VARCHAR2(200)
);
CREATE SEQUENCE  DMALM_CALIPSO_MAN_ORD_SW_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_CALIPSO_AMB_MAN_ORD_SW (
    DMALM_CALIPSO_AM_MAN_ORD_SW_PK NUMBER(15,0) PRIMARY KEY,
    DESC_CALIPSO_AMB_MAN_ORD_SW VARCHAR2(200)
);*/

CREATE SEQUENCE  DMALM_CALIPSO_SCHEDA_SERVZ_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE DMALM_STG_CALIPSO_SCHEDA_SERVZ (
	DMALM_CALIPSO_SCHEDA_SERVZ_PK NUMBER(15,0) PRIMARY KEY,
	SCHEDA_SERVIZIO VARCHAR(100),
    SERVIZIO_BUSINESS VARCHAR2(4000),
	AMBITO VARCHAR2(500),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CLIENTE VARCHAR2(200),
	RESPONSABILE_STRUTTURA VARCHAR2(500),
	RESPONSABILE_SERVIZIO VARCHAR2(500),
	RESPONSABILE_GESTIONE VARCHAR2(500),
	REFERENTE_GESTIONE VARCHAR2(500),
	REFERENTE_APPLICAZIONE VARCHAR2(500),
	SOFTWARE_SUPPORTO VARCHAR2(200),
	AMBITO_MANUTNZN_ORDNAR_SW VARCHAR2(200),
	DMALM_CALIPSO_STATO_SERVZ_FK VARCHAR2(200),
	DMALM_CALIPSO_TIPLG_STRUTTR_FK VARCHAR2(200),
	DMALM_CALIPSO_CLASSE_SERVZ_FK VARCHAR2(200),
	TIPOLOGIA_INCARICO VARCHAR2(200),
	SCHEDA_INCARICO VARCHAR2(200),
	AMBITO_ASSI_GEST_RL VARCHAR2(200),
	DATA_AGGIORNAMENTO TIMESTAMP,
	DATA_CARICAMENTO TIMESTAMP,
	CONSTRAINT FK_STG_CALIPSO_SCHEDA_SERVZ_01 FOREIGN KEY (DMALM_CALIPSO_STATO_SERVZ_FK) REFERENCES DMALM_CALIPSO_STATO_SERVIZIO(DMALM_CALIPSO_STATO_SERVZ_PK),
	CONSTRAINT FK_STG_CALIPSO_SCHEDA_SERVZ_02 FOREIGN KEY (DMALM_CALIPSO_TIPLG_STRUTTR_FK) REFERENCES DMALM_CALIPSO_TIPLG_STRUTTURA(DMALM_CALIPSO_TIPLG_STRUTTR_PK),
	CONSTRAINT FK_STG_CALIPSO_SCHEDA_SERVZ_03 FOREIGN KEY (DMALM_CALIPSO_CLASSE_SERVZ_FK) REFERENCES DMALM_CALIPSO_CLASSE_SERVIZIO(DMALM_CALIPSO_CLASSE_SERVZ_PK)
);

--TARGET
CREATE TABLE DMALM_CALIPSO_SCHEDA_SERVIZIO (
    DMALM_SCHEDA_SERVIZIO_PK VARCHAR(100) PRIMARY KEY,
    SERVIZIO_BUSINESS VARCHAR2(4000),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CLIENTE VARCHAR2(200),
	DMALM_CALIPSO_STATO_SERVZ_FK VARCHAR2(200),
	DATA_CARICAMENTO TIMESTAMP
);

CREATE TABLE DMALM_CALIPSO_SCHED_SERVZ_STOR (
	DMALM_SCHEDA_SERVIZIO_STOR_PK VARCHAR(100),
	DATA_INIZIO_STOR TIMESTAMP,
	DATA_FINE_STOR TIMESTAMP,
    SERVIZIO_BUSINESS VARCHAR2(4000),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CLIENTE VARCHAR2(200),
	DMALM_CALIPSO_STATO_SERVZ_FK VARCHAR2(200),
	DATA_CARICAMENTO TIMESTAMP,
	CONSTRAINT PK_CALIPSO_SCHED_SERVZ_STOR PRIMARY KEY (DMALM_SCHEDA_SERVIZIO_STOR_PK, DATA_INIZIO_STOR)
);

CREATE TABLE T_DMALM_CALIPSO_SCHED_SERVIZIO (
    DMALM_SCHEDA_SERVIZIO_PK VARCHAR(100) PRIMARY KEY,
    SERVIZIO_BUSINESS VARCHAR2(4000),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CLIENTE VARCHAR2(200),
	DMALM_CALIPSO_STATO_SERVZ_FK VARCHAR2(200),
	DATA_CARICAMENTO TIMESTAMP
);

CREATE TABLE T_DMALM_CALIPSO_SCHED_SERVZ_ST (
	DMALM_SCHEDA_SERVIZIO_STOR_PK VARCHAR(100),
	DATA_INIZIO_STOR TIMESTAMP,
	DATA_FINE_STOR TIMESTAMP,
    SERVIZIO_BUSINESS VARCHAR2(4000),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CLIENTE VARCHAR2(200),
	DMALM_CALIPSO_STATO_SERVZ_FK VARCHAR2(200),
	DATA_CARICAMENTO TIMESTAMP,
	CONSTRAINT PK_T_CALIPSO_SCHED_SERVZ_STOR PRIMARY KEY (DMALM_SCHEDA_SERVIZIO_STOR_PK, DATA_INIZIO_STOR)
);

CREATE TABLE DMALM_CALIPSO_AMBT_SCHED_SERVZ (
	DMALM_CALIPSO_AMBITO_FK NUMBER(15,0),
	DMALM_CALIPSO_SCHEDA_SERVZ_FK VARCHAR(100),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CONSTRAINT PK_CALIPSO_AMBT_SCHED_SERVZ PRIMARY KEY (DMALM_CALIPSO_AMBITO_FK, DMALM_CALIPSO_SCHEDA_SERVZ_FK, DATA_INIZIO_VALIDITA),
	CONSTRAINT FK_CALIPSO_AMBT_SCHED_SERVZ_01 FOREIGN KEY (DMALM_CALIPSO_AMBITO_FK) REFERENCES DMALM_CALIPSO_AMBITO(DMALM_CALIPSO_AMBITO_PK),
	CONSTRAINT FK_CALIPSO_AMBT_SCHED_SERVZ_02 FOREIGN KEY (DMALM_CALIPSO_SCHEDA_SERVZ_FK) REFERENCES DMALM_CALIPSO_SCHEDA_SERVIZIO(DMALM_SCHEDA_SERVIZIO_PK)
);
CREATE TABLE DMALM_CALIPSO_SCH_SERVZ_PERSNL (
	DMALM_CALIPSO_SCHEDA_SERVZ_FK VARCHAR(100),
	DMALM_STG_EL_PERSONALE_FK NUMBER(15,0),
	TIPO_PERSONALE VARCHAR2(200),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CONSTRAINT PK_CALIPSO_SCHEDA_SERVZ_PER PRIMARY KEY (DMALM_CALIPSO_SCHEDA_SERVZ_FK, DMALM_STG_EL_PERSONALE_FK, TIPO_PERSONALE, DATA_INIZIO_VALIDITA),
	CONSTRAINT FK_CALIPSO_SCHEDA_SERVZ_PER_01 FOREIGN KEY (DMALM_STG_EL_PERSONALE_FK) REFERENCES DMALM_STG_EL_PERSONALE(DMALM_STG_PERSONALE_PK),
	CONSTRAINT FK_CALIPSO_SCHEDA_SERVZ_PER_02 FOREIGN KEY (DMALM_CALIPSO_SCHEDA_SERVZ_FK) REFERENCES DMALM_CALIPSO_SCHEDA_SERVIZIO(DMALM_SCHEDA_SERVIZIO_PK)
);
CREATE TABLE DMALM_CALIPSO_SCH_SUPP_MAN_SW (
	DMALM_CALIPSO_SCHEDA_SERVZ_FK VARCHAR(100),
	SOFTWARE_SUPPORTO VARCHAR2(200),
	AMBITO_MANUTNZN_ORDNAR_SW VARCHAR2(200),
	DATA_INIZIO_VALIDITA DATE,
	DATA_FINE_VALIDITA DATE,
	CONSTRAINT PK_CALIPSO_SCH_SUPP_MAN_SW PRIMARY KEY (DMALM_CALIPSO_SCHEDA_SERVZ_FK, SOFTWARE_SUPPORTO, AMBITO_MANUTNZN_ORDNAR_SW, DATA_INIZIO_VALIDITA),
	CONSTRAINT FK_CALIPSO_SCH_SUPP_MAN_SW_01 FOREIGN KEY (DMALM_CALIPSO_SCHEDA_SERVZ_FK) REFERENCES DMALM_CALIPSO_SCHEDA_SERVIZIO(DMALM_SCHEDA_SERVIZIO_PK)
);