SPOOL 323_DMALM_RFC.sql

SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;

--------------------------------------------------------
--  File creato - lunedì-ottobre-28-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMALM_RFC
--------------------------------------------------------

  CREATE TABLE DMALM_RFC 
   (	CD_RFC VARCHAR2(250 BYTE), 
	DMALM_RFC_PK NUMBER, 
	DMALM_PROJECT_FK_02 VARCHAR2(15 BYTE), 
	DMALM_STATO_WORKITEM_FK_03 NUMBER(15,0), 
	DMALM_TEMPO_FK_04 NUMBER(15,0), 
	DMALM_USER_FK_06 NUMBER(15,0), 
	RANK_STATO_RFC NUMBER, 
	RANK_STATO_RFC_MESE NUMBER(5,0) DEFAULT 0, 
	DT_CARICAMENTO_RFC DATE, 
	TAG_ALM VARCHAR2(4000 BYTE), 
	TS_TAG_ALM TIMESTAMP (6), 
	ANNULLATO VARCHAR2(500 BYTE), 
	STG_PK VARCHAR2(4000 BYTE), 
	URI_RFC VARCHAR2(4000 BYTE), 
	DT_STORICIZZAZIONE TIMESTAMP (6), 
	DATA_MODIFICA_RECORD TIMESTAMP (6), 
	TIMESPENT FLOAT(126), 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	TIPOLOGIA_INTERVENTO VARCHAR2(250 BYTE), 
	TIPOLOGIA_DATI_TRATTATI VARCHAR2(250 BYTE), 
	RICHIESTA_IT VARCHAR2(20 BYTE), 
	INFRASTRUTTURA_ESISTENTE VARCHAR2(4000 BYTE), 
	CAMBIAMENTO_RICHIESTO VARCHAR2(4000 BYTE), 
	DESCRIZIONE_UTENZA VARCHAR2(4000 BYTE), 
	REQUISITI_DI_UTILIZZO VARCHAR2(4000 BYTE), 
	MODALITA_GESTIONE VARCHAR2(4000 BYTE), 
	CRIPTAZIONE_DATI VARCHAR2(20 BYTE), 
	POLITICA_ARCHIVIZIONE_DATI VARCHAR2(20 BYTE), 
	SEPARAZIONE_RUOLI_ACCESSO_DATI VARCHAR2(20 BYTE), 
	CLASSE_DI_SERVIZIO VARCHAR2(20 BYTE), 
	ACCESSO_AL_SERVIZIO VARCHAR2(4000 BYTE), 
	ASSISTENZA_UTENTI VARCHAR2(250 BYTE), 
	ANALISI_DEI_RISCHI VARCHAR2(4000 BYTE), 
	DESCRIZIONE_DEL_SERVIZIO VARCHAR2(4000 BYTE), 
	COD_SCHEDA_SERVIZIO_POLARION VARCHAR2(4000 BYTE), 
	TITOLO_DELLA_RICHIESTA VARCHAR2(250 BYTE), 
	ID_REPOSITORY VARCHAR2(20 BYTE), 
	DATA_CAMBIO_STATO_RFC TIMESTAMP (6), 
	DATA_ANNULLAMENTO TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_ALM ;
--------------------------------------------------------
--  DDL for Table DMALM_RFC_ODS
--------------------------------------------------------

  CREATE TABLE DMALM_RFC_ODS 
   (	CD_RFC VARCHAR2(250 BYTE), 
	DMALM_RFC_PK NUMBER, 
	DMALM_STRUTTURA_ORG_FK_01 NUMBER(15,0), 
	DMALM_PROJECT_FK_02 VARCHAR2(15 BYTE), 
	DMALM_STATO_WORKITEM_FK_03 NUMBER(15,0), 
	DMALM_TEMPO_FK_04 NUMBER(15,0), 
	DMALM_USER_FK_06 NUMBER(15,0), 
	RANK_STATO_RFC NUMBER, 
	RANK_STATO_RFC_MESE NUMBER(5,0) DEFAULT 0, 
	DT_CARICAMENTO_RFC DATE, 
	TAG_ALM VARCHAR2(4000 BYTE), 
	TS_TAG_ALM TIMESTAMP (6), 
	ANNULLATO VARCHAR2(500 BYTE), 
	STG_PK VARCHAR2(4000 BYTE), 
	URI_RFC VARCHAR2(4000 BYTE), 
	DT_STORICIZZAZIONE TIMESTAMP (6), 
	DATA_MODIFICA_RECORD TIMESTAMP (6), 
	TIMESPENT FLOAT(126), 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	TIPOLOGIA_INTERVENTO VARCHAR2(250 BYTE), 
	TIPOLOGIA_DATI_TRATTATI VARCHAR2(250 BYTE), 
	RICHIESTA_IT VARCHAR2(20 BYTE), 
	INFRASTRUTTURA_ESISTENTE VARCHAR2(4000 BYTE), 
	CAMBIAMENTO_RICHIESTO VARCHAR2(4000 BYTE), 
	DESCRIZIONE_UTENZA VARCHAR2(4000 BYTE), 
	REQUISITI_DI_UTILIZZO VARCHAR2(4000 BYTE), 
	MODALITA_GESTIONE VARCHAR2(4000 BYTE), 
	CRIPTAZIONE_DATI VARCHAR2(20 BYTE), 
	POLITICA_ARCHIVIZIONE_DATI VARCHAR2(20 BYTE), 
	SEPARAZIONE_RUOLI_ACCESSO_DATI VARCHAR2(20 BYTE), 
	CLASSE_DI_SERVIZIO VARCHAR2(20 BYTE), 
	ACCESSO_AL_SERVIZIO VARCHAR2(4000 BYTE), 
	ASSISTENZA_UTENTI VARCHAR2(250 BYTE), 
	ANALISI_DEI_RISCHI VARCHAR2(4000 BYTE), 
	DESCRIZIONE_DEL_SERVIZIO VARCHAR2(4000 BYTE), 
	CODICE_SCHEDA_SERVIZIO VARCHAR2(4000 BYTE), 
	TITOLO_DELLA_RICHIESTA VARCHAR2(250 BYTE), 
	ID_REPOSITORY VARCHAR2(20 BYTE), 
	DATA_CAMBIO_STATO_RFC TIMESTAMP (6), 
	DATA_ANNULLAMENTO TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_ALM ;
--------------------------------------------------------
--  DDL for Index DMALM_RFC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX DMALM_RFC_PK ON DMALM_RFC (DMALM_RFC_PK) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_ALM ;
--------------------------------------------------------
--  DDL for Index DMALM_RFC_ODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX DMALM_RFC_ODS_PK ON DMALM_RFC_ODS (DMALM_RFC_PK) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE TS_ALM ;
--------------------------------------------------------
--  Constraints for Table DMALM_RFC
--------------------------------------------------------

  ALTER TABLE DMALM_RFC ADD CONSTRAINT DMALM_RFC_PK PRIMARY KEY (DMALM_RFC_PK)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_ALM  ENABLE;
  ALTER TABLE DMALM_RFC MODIFY (DMALM_RFC_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DMALM_RFC_ODS
--------------------------------------------------------

  ALTER TABLE DMALM_RFC_ODS ADD CONSTRAINT DMALM_RFC_ODS_PK PRIMARY KEY (DMALM_RFC_PK)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE TS_ALM  ENABLE;
  ALTER TABLE DMALM_RFC_ODS MODIFY (DMALM_RFC_PK NOT NULL ENABLE);

  
  CREATE TABLE T_DMALM_RFC 
   (	CD_RFC VARCHAR2(250 BYTE), 
	DMALM_RFC_PK NUMBER, 
	DMALM_PROJECT_FK_02 VARCHAR2(15 BYTE), 
	DMALM_STATO_WORKITEM_FK_03 NUMBER(15,0), 
	DMALM_TEMPO_FK_04 NUMBER(15,0), 
	DMALM_USER_FK_06 NUMBER(15,0), 
	RANK_STATO_RFC NUMBER, 
	RANK_STATO_RFC_MESE NUMBER(5,0), 
	DT_CARICAMENTO_RFC DATE, 
	TAG_ALM VARCHAR2(4000 BYTE), 
	TS_TAG_ALM TIMESTAMP (6), 
	ANNULLATO VARCHAR2(500 BYTE), 
	STG_PK VARCHAR2(4000 BYTE), 
	URI_RFC VARCHAR2(4000 BYTE), 
	DT_STORICIZZAZIONE TIMESTAMP (6), 
	DATA_MODIFICA_RECORD TIMESTAMP (6), 
	TIMESPENT FLOAT(126), 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	TIPOLOGIA_INTERVENTO VARCHAR2(250 BYTE), 
	TIPOLOGIA_DATI_TRATTATI VARCHAR2(250 BYTE), 
	RICHIESTA_IT VARCHAR2(20 BYTE), 
	INFRASTRUTTURA_ESISTENTE VARCHAR2(4000 BYTE), 
	CAMBIAMENTO_RICHIESTO VARCHAR2(4000 BYTE), 
	DESCRIZIONE_UTENZA VARCHAR2(4000 BYTE), 
	REQUISITI_DI_UTILIZZO VARCHAR2(4000 BYTE), 
	MODALITA_GESTIONE VARCHAR2(4000 BYTE), 
	CRIPTAZIONE_DATI VARCHAR2(20 BYTE), 
	POLITICA_ARCHIVIZIONE_DATI VARCHAR2(20 BYTE), 
	SEPARAZIONE_RUOLI_ACCESSO_DATI VARCHAR2(20 BYTE), 
	CLASSE_DI_SERVIZIO VARCHAR2(20 BYTE), 
	ACCESSO_AL_SERVIZIO VARCHAR2(4000 BYTE), 
	ASSISTENZA_UTENTI VARCHAR2(250 BYTE), 
	ANALISI_DEI_RISCHI VARCHAR2(4000 BYTE), 
	DESCRIZIONE_DEL_SERVIZIO VARCHAR2(4000 BYTE), 
	COD_SCHEDA_SERVIZIO_POLARION VARCHAR2(4000 BYTE), 
	TITOLO_DELLA_RICHIESTA VARCHAR2(250 BYTE), 
	ID_REPOSITORY VARCHAR2(20 BYTE), 
	DATA_CAMBIO_STATO_RFC TIMESTAMP (6), 
	DATA_ANNULLAMENTO TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_ALM ;
--------------------------------------------------------
--  Constraints for Table T_DMALM_RFC
--------------------------------------------------------

  ALTER TABLE T_DMALM_RFC MODIFY (DMALM_RFC_PK NOT NULL ENABLE);
