SPOOL 326_TYPE_RFC.sql

SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
  CREATE OR REPLACE TYPE RFCTYPE AS OBJECT 
( CD_RFC	VARCHAR2(250 BYTE),
    DMALM_RFC_PK	NUMBER,
DMALM_PROJECT_FK_02	VARCHAR2(15 BYTE),
DMALM_STATO_WORKITEM_FK_03	NUMBER(15,0),
DMALM_TEMPO_FK_04	NUMBER(15,0),
DMALM_USER_FK_06	NUMBER(15,0),
RANK_STATO_RFC	NUMBER,
RANK_STATO_RFC_MESE	NUMBER(5,0),
DT_CARICAMENTO_RFC	DATE,
TAG_ALM	VARCHAR2(4000 BYTE),
TS_TAG_ALM	TIMESTAMP(6),
ANNULLATO	VARCHAR2(500 BYTE),
STG_PK	VARCHAR2(4000 BYTE),
URI_RFC	VARCHAR2(4000 BYTE),
DATA_CARICAMENTO	TIMESTAMP(6),
DT_STORICIZZAZIONE	TIMESTAMP(6),
DATA_MODIFICA_RECORD	TIMESTAMP(6),
TIMESPENT	FLOAT,
DESCRIPTION	VARCHAR2(4000 BYTE),
TIPOLOGIA_INTERVENTO	VARCHAR2(250 BYTE),
TIPOLOGIA_DATI_TRATTATI	VARCHAR2(250 BYTE),
RICHIESTA_IT	VARCHAR2(20 BYTE),
INFRASTRUTTURA_ESISTENTE	VARCHAR2(4000 BYTE),
CAMBIAMENTO_RICHIESTO	VARCHAR2(4000 BYTE),
DESCRIZIONE_UTENZA	VARCHAR2(4000 BYTE),
REQUISITI_DI_UTILIZZO	VARCHAR2(4000 BYTE),
MODALITA_GESTIONE	VARCHAR2(4000 BYTE),
CRIPTAZIONE_DATI	VARCHAR2(20 BYTE),
POLITICA_ARCHIVIZIONE_DATI	VARCHAR2(20 BYTE),
SEPARAZIONE_RUOLI_ACCESSO_DATI	VARCHAR2(20 BYTE),
CLASSE_DI_SERVIZIO	VARCHAR2(20 BYTE),
ACCESSO_AL_SERVIZIO	VARCHAR2(4000 BYTE),
ASSISTENZA_UTENTI	VARCHAR2(250 BYTE),
ANALISI_DEI_RISCHI	VARCHAR2(4000 BYTE),
DESCRIZIONE_DEL_SERVIZIO	VARCHAR2(4000 BYTE),
COD_SCHEDA_SERVIZIO_POLARION	VARCHAR2(4000 BYTE),
TITOLO_DELLA_RICHIESTA	VARCHAR2(250 BYTE),
ID_REPOSITORY VARCHAR2(20),
DATA_CAMBIO_STATO_RFC TIMESTAMP(6),
DATA_ANNULLAMENTO TIMESTAMP(6)
);
