SPOOL 330_TABELLE_FONTE.sql

SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
--------------------------------------------------------
--  File creato - mercoledì-dicembre-11-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SIRE_PROJECT
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SIRE_PROJECT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_ACTIVE VARCHAR2(1 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_FINISH DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	FK_LEAD VARCHAR2(4000 BYTE), 
	FK_URI_LEAD VARCHAR2(4000 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_LOCKWORKRECORDSDATE DATE, 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PROJECTGROUP VARCHAR2(4000 BYTE), 
	FK_URI_PROJECTGROUP VARCHAR2(4000 BYTE), 
	C_START DATE, 
	C_TRACKERPREFIX VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SIRE_STRUCT_WI_LINKWI
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SIRE_STRUCT_WI_LINKWI 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_REVISION VARCHAR2(4000 BYTE), 
	C_SUSPECT VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SIRE_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SIRE_WORKITEM 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_AUTOSUSPECT VARCHAR2(1 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DUEDATE DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALESTIMATE NUMBER(15,8), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	FK_MODULE VARCHAR2(4000 BYTE), 
	FK_URI_MODULE VARCHAR2(4000 BYTE), 
	C_OUTLINENUMBER VARCHAR2(4000 BYTE), 
	C_PLANNEDEND TIMESTAMP (6), 
	C_PLANNEDSTART TIMESTAMP (6), 
	C_PREVIOUSSTATUS VARCHAR2(4000 BYTE), 
	C_PRIORITY VARCHAR2(4000 BYTE), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_REMAININGESTIMATE NUMBER(15,8), 
	C_RESOLUTION VARCHAR2(4000 BYTE), 
	C_RESOLVEDON TIMESTAMP (6), 
	C_SEVERITY VARCHAR2(4000 BYTE), 
	C_STATUS VARCHAR2(4000 BYTE), 
	FK_TIMEPOINT VARCHAR2(4000 BYTE), 
	FK_URI_TIMEPOINT VARCHAR2(4000 BYTE), 
	C_TIMESPENT NUMBER(15,8), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_TYPE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SISS_PROJECT
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SISS_PROJECT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_ACTIVE VARCHAR2(1 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_FINISH DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	FK_LEAD VARCHAR2(4000 BYTE), 
	FK_URI_LEAD VARCHAR2(4000 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_LOCKWORKRECORDSDATE DATE, 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PROJECTGROUP VARCHAR2(4000 BYTE), 
	FK_URI_PROJECTGROUP VARCHAR2(4000 BYTE), 
	C_START DATE, 
	C_TRACKERPREFIX VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SISS_STRUCT_WI_LINKWI
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SISS_STRUCT_WI_LINKWI 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_REVISION VARCHAR2(4000 BYTE), 
	C_SUSPECT VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_C_SISS_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_C_SISS_WORKITEM 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_AUTOSUSPECT VARCHAR2(1 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DUEDATE DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALESTIMATE NUMBER(15,8), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	FK_MODULE VARCHAR2(4000 BYTE), 
	FK_URI_MODULE VARCHAR2(4000 BYTE), 
	C_OUTLINENUMBER VARCHAR2(4000 BYTE), 
	C_PLANNEDEND TIMESTAMP (6), 
	C_PLANNEDSTART TIMESTAMP (6), 
	C_PREVIOUSSTATUS VARCHAR2(4000 BYTE), 
	C_PRIORITY VARCHAR2(4000 BYTE), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_REMAININGESTIMATE NUMBER(15,8), 
	C_RESOLUTION VARCHAR2(4000 BYTE), 
	C_RESOLVEDON TIMESTAMP (6), 
	C_SEVERITY VARCHAR2(4000 BYTE), 
	C_STATUS VARCHAR2(4000 BYTE), 
	FK_TIMEPOINT VARCHAR2(4000 BYTE), 
	FK_URI_TIMEPOINT VARCHAR2(4000 BYTE), 
	C_TIMESPENT NUMBER(15,8), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_TYPE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6)
   ) ;

--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_ATTACHMENT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_CONTENT BLOB, 
	C_FILENAME VARCHAR2(4000 BYTE), 
	C_ID VARCHAR2(4000 BYTE), 
	C_LENGTH NUMBER(20,0), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6), 
	C_URL VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_CF_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_CF_WORKITEM 
   (	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	C_BOOLEAN_VALUE VARCHAR2(1 BYTE), 
	C_LONG_VALUE NUMBER(20,0), 
	C_FLOAT_VALUE NUMBER(15,8), 
	C_CURRENCY_VALUE NUMBER(20,2), 
	C_DATE_VALUE TIMESTAMP (6), 
	C_DATEONLY_VALUE DATE, 
	C_DURATIONTIME_VALUE NUMBER(15,8), 
	C_STRING_VALUE VARCHAR2(4000 BYTE), 
	C_TEXT_VALUE VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_PROJECT
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_PROJECT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_ACTIVE VARCHAR2(1 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_FINISH DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	FK_LEAD VARCHAR2(4000 BYTE), 
	FK_URI_LEAD VARCHAR2(4000 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_LOCKWORKRECORDSDATE DATE, 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PROJECTGROUP VARCHAR2(4000 BYTE), 
	FK_URI_PROJECTGROUP VARCHAR2(4000 BYTE), 
	C_START DATE, 
	C_TRACKERPREFIX VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_PROJECTGROUP
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_PROJECTGROUP 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PARENT VARCHAR2(4000 BYTE), 
	FK_URI_PARENT VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_REL_WI_USER_ASS
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_REL_WI_USER_ASS 
   (	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	FK_USER VARCHAR2(4000 BYTE), 
	FK_URI_USER VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_REVISION
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_REVISION 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_AUTHOR VARCHAR2(4000 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_INTERNALCOMMIT VARCHAR2(1 BYTE), 
	C_MESSAGE VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	C_REPOSITORYNAME VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_STRUCT_WI_HYLINK
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_STRUCT_WI_HYLINK 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	C_URL VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_STRUCT_WI_LINKWI
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_STRUCT_WI_LINKWI 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_REVISION VARCHAR2(4000 BYTE), 
	C_SUSPECT VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_USER
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_USER 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_AVATARFILENAME VARCHAR2(4000 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DISABLEDNOTIFICATIONS VARCHAR2(1 BYTE), 
	C_EMAIL VARCHAR2(4000 BYTE), 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALS VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SIRE_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SIRE_WORKITEM 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_AUTOSUSPECT VARCHAR2(1 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DUEDATE DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALESTIMATE NUMBER(15,8), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	FK_MODULE VARCHAR2(4000 BYTE), 
	FK_URI_MODULE VARCHAR2(4000 BYTE), 
	C_OUTLINENUMBER VARCHAR2(4000 BYTE), 
	C_PLANNEDEND TIMESTAMP (6), 
	C_PLANNEDSTART TIMESTAMP (6), 
	C_PREVIOUSSTATUS VARCHAR2(4000 BYTE), 
	C_PRIORITY VARCHAR2(4000 BYTE), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_REMAININGESTIMATE NUMBER(15,8), 
	C_RESOLUTION VARCHAR2(4000 BYTE), 
	C_RESOLVEDON TIMESTAMP (6), 
	C_SEVERITY VARCHAR2(4000 BYTE), 
	C_STATUS VARCHAR2(4000 BYTE), 
	FK_TIMEPOINT VARCHAR2(4000 BYTE), 
	FK_URI_TIMEPOINT VARCHAR2(4000 BYTE), 
	C_TIMESPENT NUMBER(15,8), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_TYPE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_ATTACHMENT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_CONTENT BLOB, 
	C_FILENAME VARCHAR2(4000 BYTE), 
	C_ID VARCHAR2(4000 BYTE), 
	C_LENGTH NUMBER(20,0), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6), 
	C_URL VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_CF_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_CF_WORKITEM 
   (	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	C_BOOLEAN_VALUE VARCHAR2(1 BYTE), 
	C_LONG_VALUE NUMBER(20,0), 
	C_FLOAT_VALUE NUMBER(15,8), 
	C_CURRENCY_VALUE NUMBER(20,2), 
	C_DATE_VALUE TIMESTAMP (6), 
	C_DATEONLY_VALUE DATE, 
	C_DURATIONTIME_VALUE NUMBER(15,8), 
	C_STRING_VALUE VARCHAR2(4000 BYTE), 
	C_TEXT_VALUE VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_PROJECT
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_PROJECT 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_ACTIVE VARCHAR2(1 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_FINISH DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	FK_LEAD VARCHAR2(4000 BYTE), 
	FK_URI_LEAD VARCHAR2(4000 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_LOCKWORKRECORDSDATE DATE, 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PROJECTGROUP VARCHAR2(4000 BYTE), 
	FK_URI_PROJECTGROUP VARCHAR2(4000 BYTE), 
	C_START DATE, 
	C_TRACKERPREFIX VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_PROJECTGROUP
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_PROJECTGROUP 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	FK_PARENT VARCHAR2(4000 BYTE), 
	FK_URI_PARENT VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_REL_WI_USER_ASS
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_REL_WI_USER_ASS 
   (	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	FK_USER VARCHAR2(4000 BYTE), 
	FK_URI_USER VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_REVISION
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_REVISION 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_AUTHOR VARCHAR2(4000 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_INTERNALCOMMIT VARCHAR2(1 BYTE), 
	C_MESSAGE VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE), 
	C_REPOSITORYNAME VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_STRUCT_WI_HYLINK
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_STRUCT_WI_HYLINK 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	C_URL VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_STRUCT_WI_LINKWI
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_STRUCT_WI_LINKWI 
   (	FK_P_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_P_WORKITEM VARCHAR2(4000 BYTE), 
	C_ROLE VARCHAR2(4000 BYTE), 
	FK_WORKITEM VARCHAR2(4000 BYTE), 
	FK_URI_WORKITEM VARCHAR2(4000 BYTE), 
	C_REVISION VARCHAR2(4000 BYTE), 
	C_SUSPECT VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_USER
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_USER 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	C_AVATARFILENAME VARCHAR2(4000 BYTE), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DISABLEDNOTIFICATIONS VARCHAR2(1 BYTE), 
	C_EMAIL VARCHAR2(4000 BYTE), 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALS VARCHAR2(4000 BYTE), 
	C_NAME VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_H_SISS_WORKITEM
--------------------------------------------------------

  CREATE TABLE DM_ALM_H_SISS_WORKITEM 
   (	C_PK VARCHAR2(4000 BYTE), 
	C_URI VARCHAR2(4000 BYTE), 
	C_REV NUMBER(20,0), 
	C_DELETED VARCHAR2(1 BYTE), 
	C_IS_LOCAL VARCHAR2(1 BYTE), 
	FK_AUTHOR VARCHAR2(4000 BYTE), 
	FK_URI_AUTHOR VARCHAR2(4000 BYTE), 
	C_AUTOSUSPECT VARCHAR2(1 BYTE), 
	C_CREATED TIMESTAMP (6), 
	C_DESCRIPTION VARCHAR2(4000 BYTE), 
	C_DUEDATE DATE, 
	C_ID VARCHAR2(4000 BYTE), 
	C_INITIALESTIMATE NUMBER(15,8), 
	C_LOCATION VARCHAR2(4000 BYTE), 
	FK_MODULE VARCHAR2(4000 BYTE), 
	FK_URI_MODULE VARCHAR2(4000 BYTE), 
	C_OUTLINENUMBER VARCHAR2(4000 BYTE), 
	C_PLANNEDEND TIMESTAMP (6), 
	C_PLANNEDSTART TIMESTAMP (6), 
	C_PREVIOUSSTATUS VARCHAR2(4000 BYTE), 
	C_PRIORITY VARCHAR2(4000 BYTE), 
	FK_PROJECT VARCHAR2(4000 BYTE), 
	FK_URI_PROJECT VARCHAR2(4000 BYTE), 
	C_REMAININGESTIMATE NUMBER(15,8), 
	C_RESOLUTION VARCHAR2(4000 BYTE), 
	C_RESOLVEDON TIMESTAMP (6), 
	C_SEVERITY VARCHAR2(4000 BYTE), 
	C_STATUS VARCHAR2(4000 BYTE), 
	FK_TIMEPOINT VARCHAR2(4000 BYTE), 
	FK_URI_TIMEPOINT VARCHAR2(4000 BYTE), 
	C_TIMESPENT NUMBER(15,8), 
	C_TITLE VARCHAR2(4000 BYTE), 
	C_TYPE VARCHAR2(4000 BYTE), 
	C_UPDATED TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MISURA
--------------------------------------------------------

  CREATE TABLE DM_ALM_MISURA 
   (	ID_MSR NUMBER(8,0), 
	APPLICAZIONE VARCHAR2(500 BYTE), 
	NOTE_ASM VARCHAR2(4000 BYTE), 
	VAF_PREDEFINITO VARCHAR2(500 BYTE), 
	NOME_PROGETTO VARCHAR2(500 BYTE), 
	VERSIONE_PRJ VARCHAR2(500 BYTE), 
	TIPO_PROGETTO VARCHAR2(4000 BYTE), 
	CICLO_DI_VITA VARCHAR2(500 BYTE), 
	NOTE_PRJ VARCHAR2(4000 BYTE), 
	INCLUDE_IN_BENCHMARKING_DB VARCHAR2(500 BYTE), 
	NOME_MISURA VARCHAR2(500 BYTE), 
	VERSIONE_MSR VARCHAR2(500 BYTE), 
	DT_CONSOLIDAMENTO VARCHAR2(500 BYTE), 
	APPROCCIO VARCHAR2(500 BYTE), 
	METODO VARCHAR2(500 BYTE), 
	FASE_CICLO_DI_VITA VARCHAR2(500 BYTE), 
	DT_CREAZIONE VARCHAR2(500 BYTE), 
	DT_RIFERIMENTO VARCHAR2(500 BYTE), 
	STATO_MISURA VARCHAR2(500 BYTE), 
	NOTE_MSR VARCHAR2(4000 BYTE), 
	MODELLO VARCHAR2(500 BYTE), 
	ADJMIN VARCHAR2(500 BYTE), 
	ADJUFP VARCHAR2(500 BYTE), 
	ADJMAX VARCHAR2(500 BYTE), 
	FP_PESATI_MIN VARCHAR2(500 BYTE), 
	FP_PESATI_UFP VARCHAR2(500 BYTE), 
	FP_PESATI_MAX VARCHAR2(500 BYTE), 
	FP_NON_PESATI_MIN VARCHAR2(500 BYTE), 
	FP_NON_PESATI_UFP VARCHAR2(500 BYTE), 
	FP_NON_PESATI_MAX VARCHAR2(500 BYTE), 
	SCOPO VARCHAR2(500 BYTE), 
	AMBITO VARCHAR2(500 BYTE), 
	CONFINE VARCHAR2(1000 BYTE), 
	FONTI VARCHAR2(500 BYTE), 
	LINK_DOCUMENTALE VARCHAR2(4000 BYTE), 
	RESPONSABILE VARCHAR2(500 BYTE), 
	ESPERIENZA VARCHAR2(500 BYTE), 
	UTENTE_MISURATORE VARCHAR2(500 BYTE), 
	DT_INIZIO_ESERCIZIO VARCHAR2(500 BYTE), 
	DT_DISMISSIONE VARCHAR2(500 BYTE), 
	NUMERO_UTENTI VARCHAR2(500 BYTE), 
	FREQUENZA_UTILIZZO VARCHAR2(500 BYTE), 
	UTILIZZATA VARCHAR2(500 BYTE), 
	PROPRIETA_LEGALE VARCHAR2(500 BYTE), 
	INCLUDI_IN_DB_PATRIMONIO VARCHAR2(500 BYTE), 
	DT_AVVIO VARCHAR2(500 BYTE), 
	DT_FINE_EFFETTIVA VARCHAR2(500 BYTE), 
	IMPEGNO_EFFETTIVO VARCHAR2(500 BYTE), 
	COSTO VARCHAR2(500 BYTE), 
	DURATA_EFFETTIVA VARCHAR2(500 BYTE), 
	STAFF_MEDIO VARCHAR2(500 BYTE), 
	PERMISSIONS VARCHAR2(4000 BYTE), 
	P_APP_DN_ASM VARCHAR2(500 BYTE), 
	P_APP_DT_INIZIO_VALIDITA_ASM VARCHAR2(500 BYTE), 
	P_APP_DT_FINE_VALIDITA_ASM VARCHAR2(500 BYTE), 
	P_APP_DT_ULTIMO_AGGIORN VARCHAR2(500 BYTE), 
	P_APP_NOME_AUTH_LAST_UPDATE VARCHAR2(500 BYTE), 
	P_APP_DN_UTENTI_FINALI_ASM VARCHAR2(4000 BYTE), 
	P_APP_CD_ASM_CONFINANTI VARCHAR2(4000 BYTE), 
	P_APP_DN_SIST_TERZI_CONFIN VARCHAR2(4000 BYTE), 
	P_APP_CD_FLUSSI_IO_ASM VARCHAR2(4000 BYTE), 
	P_APP_FL_SERVIZIO_COMUNE VARCHAR2(500 BYTE), 
	P_APP_CD_ALTRE_ASM_COMMON_SERV VARCHAR2(500 BYTE), 
	P_APP_CD_DIREZIONE_DEMAND VARCHAR2(500 BYTE), 
	P_APP_FL_MISURARE_SVIMEV_FP VARCHAR2(500 BYTE), 
	P_APP_FL_DAMISURARE_PATR_FP VARCHAR2(500 BYTE), 
	P_APP_CD_AMBITO_MAN_ATTUALE VARCHAR2(1024 BYTE), 
	P_APP_CD_AMBITO_MAN_FUTURO VARCHAR2(1024 BYTE), 
	P_APP_FL_IN_MANUTENZIONE VARCHAR2(500 BYTE), 
	P_PRJ_FL_AMB_TEC_TRANS_BAT_REP VARCHAR2(500 BYTE), 
	P_PRJ_FL_AMB_TECN_GIS VARCHAR2(500 BYTE), 
	P_PRJ_AMB_TECN_PORTALI VARCHAR2(500 BYTE), 
	P_PRJ_FL_AMB_TECN_PIAT_ENTERPR VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPLIC_LG_FP_DWH VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPL_LG_FP_GIS VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPL_LG_FP_EDMA VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPL_LG_FP_MWARE VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPL_LG_FP_WEB VARCHAR2(500 BYTE), 
	P_APP_INDIC_VALIDAZIONE_ASM VARCHAR2(500 BYTE), 
	ID_ASM NUMBER(8,0), 
	ID_PROGETTO NUMBER(8,0), 
	P_PRJ_FORNITORE_SVILUPPO_MEV VARCHAR2(500 BYTE), 
	P_PRJ_FORNITORE_MPP VARCHAR2(500 BYTE), 
	P_PRJ_DT_CONSEGNA_MPP_FORN VARCHAR2(500 BYTE), 
	P_PRJ_AUDIT_MONITORE VARCHAR2(500 BYTE), 
	P_PRJ_AUDIT_INDEX_VERIFY VARCHAR2(500 BYTE), 
	P_PRJ_INDEX_ALM_VALID_PROG_ASM VARCHAR2(500 BYTE), 
	A_1_NUM VARCHAR2(500 BYTE), 
	A_1_UFP VARCHAR2(500 BYTE), 
	A_2_NUM VARCHAR2(500 BYTE), 
	A_2_UFP VARCHAR2(500 BYTE), 
	P_APP_ACC_AUTH_LAST_UPDATE VARCHAR2(500 BYTE), 
	APP_CLS VARCHAR2(500 BYTE), 
	B_1_NUM VARCHAR2(500 BYTE), 
	B_1_UFP VARCHAR2(500 BYTE), 
	B_2_NUM VARCHAR2(500 BYTE), 
	B_2_UFP VARCHAR2(500 BYTE), 
	B_3_NUM VARCHAR2(500 BYTE), 
	B_3_UFP VARCHAR2(500 BYTE), 
	B_5_NUM VARCHAR2(500 BYTE), 
	B_5_UFP VARCHAR2(500 BYTE), 
	BFP_NUM VARCHAR2(500 BYTE), 
	BFP_UFP VARCHAR2(500 BYTE), 
	C_1_NUM VARCHAR2(500 BYTE), 
	C_1_UFP VARCHAR2(500 BYTE), 
	C_2_NUM VARCHAR2(500 BYTE), 
	C_2_UFP VARCHAR2(500 BYTE), 
	CRUD_NUM VARCHAR2(500 BYTE), 
	CRUD_UFP VARCHAR2(500 BYTE), 
	D_1_NUM VARCHAR2(500 BYTE), 
	D_1_UFP VARCHAR2(500 BYTE), 
	D_2_NUM VARCHAR2(500 BYTE), 
	D_2_UFP VARCHAR2(500 BYTE), 
	EI_NUM VARCHAR2(500 BYTE), 
	EI_UFP VARCHAR2(500 BYTE), 
	EIF_NUM VARCHAR2(500 BYTE), 
	EIF_UFP VARCHAR2(500 BYTE), 
	EO_NUM VARCHAR2(500 BYTE), 
	EO_UFP VARCHAR2(500 BYTE), 
	EQ_NUM VARCHAR2(500 BYTE), 
	EQ_UFP VARCHAR2(500 BYTE), 
	FU_NUM VARCHAR2(500 BYTE), 
	FU_UFP VARCHAR2(500 BYTE), 
	GDG_NUM VARCHAR2(500 BYTE), 
	GDG_UFP VARCHAR2(500 BYTE), 
	GEI_NUM VARCHAR2(500 BYTE), 
	GEI_UFP VARCHAR2(500 BYTE), 
	GEIF_NUM VARCHAR2(500 BYTE), 
	GEIF_UFP VARCHAR2(500 BYTE), 
	GEO_NUM VARCHAR2(500 BYTE), 
	GEO_UFP VARCHAR2(500 BYTE), 
	GEQ_NUM VARCHAR2(500 BYTE), 
	GEQ_UFP VARCHAR2(500 BYTE), 
	GILF_NUM VARCHAR2(500 BYTE), 
	GILF_UFP VARCHAR2(500 BYTE), 
	GP_NUM VARCHAR2(500 BYTE), 
	GP_UFP VARCHAR2(500 BYTE), 
	IFP_NUM VARCHAR2(500 BYTE), 
	IFP_UFP VARCHAR2(500 BYTE), 
	ILF_NUM VARCHAR2(500 BYTE), 
	ILF_UFP VARCHAR2(500 BYTE), 
	LDG_NUM VARCHAR2(500 BYTE), 
	LDG_UFP VARCHAR2(500 BYTE), 
	MF_NUM VARCHAR2(500 BYTE), 
	MF_UFP VARCHAR2(500 BYTE), 
	MLDG_NUM VARCHAR2(500 BYTE), 
	MLDG_UFP VARCHAR2(500 BYTE), 
	MP_NUM VARCHAR2(500 BYTE), 
	MP_UFP VARCHAR2(500 BYTE), 
	PF_NUM VARCHAR2(500 BYTE), 
	PF_UFP VARCHAR2(500 BYTE), 
	POST_VER_ADD_CFP VARCHAR2(500 BYTE), 
	POST_VER_CHG VARCHAR2(500 BYTE), 
	POST_VER_DEL VARCHAR2(500 BYTE), 
	POST_VER_FP VARCHAR2(500 BYTE), 
	PRE_VER_ADD_CFP VARCHAR2(500 BYTE), 
	PRE_VER_CHG VARCHAR2(500 BYTE), 
	PRE_VER_DEL VARCHAR2(500 BYTE), 
	PRE_VER_FP VARCHAR2(500 BYTE), 
	P_PRJ_CD_RDI VARCHAR2(500 BYTE), 
	P_PRJ_FCC_FATT_CORREZ_TOTAL VARCHAR2(500 BYTE), 
	P_PRJ_FL_AMBITO_TECN_FUTURO01 VARCHAR2(500 BYTE), 
	P_PRJ_FL_AMBITO_TECN_FUTURO02 VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPLIC_LG_FP_FUTURO01 VARCHAR2(500 BYTE), 
	P_PRJ_FL_APPLIC_LG_FP_FUTURO02 VARCHAR2(500 BYTE), 
	P_PRJ_IMPORTO_A_CONSUNTIVO VARCHAR2(500 BYTE), 
	P_PRJ_IMPORTO_RDI_A_PREVENTIVO VARCHAR2(500 BYTE), 
	P_PRJ_MFC_A_CONSUNTIVO VARCHAR2(500 BYTE), 
	P_PRJ_MFC_A_PREVENTIVO VARCHAR2(500 BYTE), 
	P_PRJ_MP_PERCENT_CICLO_DI_VITA VARCHAR2(500 BYTE), 
	P_PRJ_PUN_PREZZO_UNIT_NOMINAL VARCHAR2(500 BYTE), 
	PRJ_CLS VARCHAR2(500 BYTE), 
	TP_NUM VARCHAR2(500 BYTE), 
	TP_UFP VARCHAR2(500 BYTE), 
	UGDG_NUM VARCHAR2(500 BYTE), 
	UGDG_UFP VARCHAR2(500 BYTE), 
	UGEP_NUM VARCHAR2(500 BYTE), 
	UGEP_UFP VARCHAR2(500 BYTE), 
	UGO_NUM VARCHAR2(500 BYTE), 
	UGO_UFP VARCHAR2(500 BYTE), 
	UGP_NUM VARCHAR2(500 BYTE), 
	UGP_UFP VARCHAR2(500 BYTE), 
	VER_DELTA VARCHAR2(500 BYTE), 
	VER_DELTA_PERCENT VARCHAR2(500 BYTE), 
	VER_END VARCHAR2(500 BYTE), 
	VER_START VARCHAR2(500 BYTE), 
	P_PRJ_A_DISPOSIZIONE_01 VARCHAR2(500 BYTE), 
	P_PRJ_A_DISPOSIZIONE_02 VARCHAR2(500 BYTE), 
	CHIAVE_NATURALE NUMBER(20,0), 
	DT_PREVISTA_PROSSIMA_MPP_ASM TIMESTAMP (6), 
	FIP01_INIZIO_ESERCIZIO_ASM TIMESTAMP (6), 
	FIP02_INDICE_QUALITA_DOC_ASM NUMBER(15,0), 
	FIP03_COMP_PT_SVIL_ESERC_ASM VARCHAR2(500 BYTE), 
	FIP04_NR_PT_TGT_ESERC_ASM NUMBER(15,0), 
	FIP07_LING_PROG_PRIN_REAL_ASM VARCHAR2(500 BYTE), 
	FIP10_GRADO_ACCESSIBILITA_ASM NUMBER(15,0), 
	FIP11_GRADO_QUALITA_COD_ASM VARCHAR2(500 BYTE), 
	FIP12_UT_FRAMEWORK_AZ_ASM VARCHAR2(500 BYTE), 
	FIP13_COMP_ALG_SW_ASM NUMBER(15,0), 
	FIP15_LV_CURA_GRAF_INT_UT_ASM VARCHAR2(500 BYTE), 
	B_4_NUM VARCHAR2(4000 BYTE), 
	B_4_UFP VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_ATTIVITA
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_ATTIVITA 
   (	IDATTIVITAPADRE NUMBER(10,0), 
	IDATTIVITA NUMBER(10,0), 
	IDCONTRATTO NUMBER(10,0), 
	CODATTIVITA VARCHAR2(500 BYTE), 
	TITOLO VARCHAR2(500 BYTE), 
	DESATTIVITA VARCHAR2(4000 BYTE), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE, 
	AVANZAMENTO NUMBER(10,5), 
	DATA_ULTIMO_AVANZAMENTO DATE, 
	TIPO_ATTIVITA CHAR(1 BYTE), 
	STATO CHAR(1 BYTE), 
	INSERITO_DA NUMBER(10,0), 
	INSERITO_IL DATE, 
	MODIFICATO_DA NUMBER(10,0), 
	MODIFICATO_IL DATE, 
	RECORDSTATUS CHAR(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_CONTRATTI
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_CONTRATTI 
   (	IDCONTRATTO NUMBER(10,0), 
	CODCONTRATTO VARCHAR2(500 BYTE), 
	TITOLOCONTRATTO VARCHAR2(500 BYTE), 
	ANNO_RIFERIMENTO NUMBER(4,0), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE, 
	TIPO VARCHAR2(4000 BYTE), 
	STATO VARCHAR2(4000 BYTE), 
	FIRMA_DIGITALE CHAR(1 BYTE), 
	VARIATO VARCHAR2(4000 BYTE), 
	NUM_VARIAZIONI NUMBER, 
	CODDIREZIONE VARCHAR2(500 BYTE), 
	DESDIREZIONE VARCHAR2(500 BYTE), 
	CODUO VARCHAR2(500 BYTE), 
	DESUO VARCHAR2(500 BYTE), 
	CODSTRUTTURA VARCHAR2(500 BYTE), 
	DESSTRUTTURA VARCHAR2(500 BYTE), 
	TOTALE_CONTRATTO NUMBER, 
	TOTALE_IMPEGNATO NUMBER, 
	TOTALE_SPALMATO NUMBER, 
	TOTALE_VERBALIZZATO NUMBER, 
	TOTALE_RICHIESTO NUMBER, 
	TOTALE_FATTURATO NUMBER, 
	TOTALE_FATTURABILE NUMBER, 
	PROSSIMO_FIRMATARIO VARCHAR2(4000 BYTE), 
	IN_CORSO_IL DATE, 
	NUMERO_RILASCI NUMBER, 
	NUMERO_RILASCI_FORFAIT NUMBER, 
	NUMERO_RILASCI_CANONE NUMBER, 
	NUMERO_RILASCI_CONSUMO NUMBER, 
	NUMERO_VERBALI NUMBER, 
	NUMERO_VERBALI_FORFAIT NUMBER, 
	NUMERO_VERBALI_CONSUMO NUMBER, 
	DESMOTIVOVARIAZIONE VARCHAR2(500 BYTE), 
	REPOSITORY VARCHAR2(500 BYTE), 
	PRIORITA VARCHAR2(500 BYTE), 
	ID_SM NUMBER(10,0), 
	SERVICE_MANAGER VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_FIRMAT_VERBALE
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_FIRMAT_VERBALE 
   (	IDVERBALEVALIDAZIONE NUMBER(10,0), 
	IDUTENTE NUMBER(10,0), 
	FIRMATARIO_VERBALE VARCHAR2(500 BYTE), 
	TIPOLOGIA_RESPONSABILE VARCHAR2(500 BYTE), 
	ORDINE_FIRMA NUMBER(4,0), 
	FIRMATO CHAR(1 BYTE), 
	DATA_FIRMA DATE, 
	IDENTE NUMBER(10,0), 
	ENTE VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_RESPON_CONTRATTO
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_RESPON_CONTRATTO 
   (	IDCONTRATTO NUMBER(10,0), 
	IDUTENTE NUMBER(10,0), 
	RESPONSABILE VARCHAR2(500 BYTE), 
	DESTIPOLOGIARESPONSABILE VARCHAR2(500 BYTE), 
	FIRMATARIO CHAR(1 BYTE), 
	ORDINE_FIRMA NUMBER(4,0), 
	FIRMATO CHAR(1 BYTE), 
	DATA_FIRMA DATE, 
	IDENTE NUMBER(10,0), 
	ENTE VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_RESPON_OFFERTA
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_RESPON_OFFERTA 
   (	IDCONTRATTO NUMBER(10,0), 
	AM_NOME VARCHAR2(500 BYTE), 
	AM_DATAFIRMA DATE, 
	AM_FIRMATO CHAR(1 BYTE), 
	SAM_NOME VARCHAR2(500 BYTE), 
	SAM_DATAFIRMA DATE, 
	SAM_FIRMATO CHAR(1 BYTE), 
	VDG_NOME VARCHAR2(500 BYTE), 
	VDG_DATAFIRMA DATE, 
	VDG_FIRMATO CHAR(1 BYTE), 
	DG_NOME VARCHAR2(500 BYTE), 
	DG_DATAFIRMA DATE, 
	DG_FIRMATO CHAR(1 BYTE), 
	CD_NOME VARCHAR2(500 BYTE), 
	CD_DATAFIRMA DATE, 
	CD_FIRMATO CHAR(1 BYTE), 
	COPERTINA_FIRMATA VARCHAR2(4000 BYTE), 
	DATA_FIRMA_COPERTINA DATE, 
	STATO_RAZIONALE CHAR(1 BYTE), 
	CONTROLLER VARCHAR2(500 BYTE), 
	DATA_VERIFICA DATE, 
	PROSSIMO_FIRMATARIO_RAZIONALE VARCHAR2(500 BYTE), 
	RAZIONALE_DIGITALE CHAR(32 BYTE), 
	NOTA_RAZIONALE VARCHAR2(4000 BYTE), 
	MOTIVAZIONE_RIGETTO VARCHAR2(4000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_RILASCI
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_RILASCI 
   (	IDRILASCIO NUMBER(10,0), 
	IDCONTRATTO NUMBER(10,0), 
	CODRILASCIO VARCHAR2(500 BYTE), 
	TIPORILASCIO VARCHAR2(500 BYTE), 
	SOTTOTIPORILASCIO VARCHAR2(4000 BYTE), 
	TITOLORILASCIO VARCHAR2(4000 BYTE), 
	DESATTIVITA VARCHAR2(4000 BYTE), 
	DATA_INIZIO DATE, 
	DATA_RILASCIO DATE, 
	DATA_VALIDAZIONE DATE, 
	STATO_FATTURAZIONE VARCHAR2(500 BYTE), 
	STATO_FINANZIAMENTO VARCHAR2(500 BYTE), 
	IMPORTO_RILASCIO NUMBER, 
	TOTALE_SPALMATO NUMBER, 
	TOTALE_VERBALIZZATO NUMBER, 
	TOTALE_RICHIESTA NUMBER, 
	TOTALE_FATTURATO NUMBER, 
	TOTALE_FATTURABILE NUMBER, 
	DATA_RILASCIO_EFFETTIVO DATE, 
	VARIANTE_MIGLIORATIVA VARCHAR2(500 BYTE), 
	STATO_VERBALIZZAZIONE VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_RILASCI_VERBALI
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_RILASCI_VERBALI 
   (	CODVERBALE VARCHAR2(500 BYTE), 
	IDVERBALEVALIDAZIONE NUMBER(10,0), 
	IDRILASCIO NUMBER(10,0), 
	IMPORTO NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_MPS_VERBALI
--------------------------------------------------------

  CREATE TABLE DM_ALM_MPS_VERBALI 
   (	CODVERBALE VARCHAR2(500 BYTE), 
	DATA_VERBALE DATE, 
	DATA_FIRMA DATE, 
	NOTE VARCHAR2(4000 BYTE), 
	CONFORME CHAR(1 BYTE), 
	TIPO_VERBALE VARCHAR2(500 BYTE), 
	STATO_VERBALE VARCHAR2(4000 BYTE), 
	TOTALE_VERBALE NUMBER, 
	FATTURATO_VERBALE NUMBER, 
	PROSSIMO_FIRMATARIO VARCHAR2(4000 BYTE), 
	FIRMA_DIGITALE CHAR(1 BYTE), 
	IDVERBALEVALIDAZIONE NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_PROJECT_ROLES
--------------------------------------------------------

  CREATE TABLE DM_ALM_PROJECT_ROLES 
   (	DESCRIZIONE VARCHAR2(4000 BYTE), 
	REPOSITORY VARCHAR2(20 BYTE), 
	RUOLO VARCHAR2(100 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_SCHEDE_SERVIZIO
--------------------------------------------------------

  CREATE TABLE DM_ALM_SCHEDE_SERVIZIO 
   (	ID VARCHAR2(100 BYTE), 
	NAME VARCHAR2(500 BYTE), 
	SORT NUMBER(15,8), 
	REPOSITORY VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_STATO_WORKITEM_SVN
--------------------------------------------------------

  CREATE TABLE DM_ALM_STATO_WORKITEM_SVN 
   (	DSCRIZIONE VARCHAR2(4000 BYTE), 
	ICON_URL VARCHAR2(4000 BYTE), 
	ID VARCHAR2(100 BYTE), 
	NAME VARCHAR2(500 BYTE), 
	SORT_ORDER NUMBER(15,8), 
	TEMPLATE VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_STG_CALIPSO_SCHEDA_SERV
--------------------------------------------------------

  CREATE TABLE DM_ALM_STG_CALIPSO_SCHEDA_SERV 
   (	Codice servizio VARCHAR2(500 BYTE), 
	Servizio di business VARCHAR2(500 BYTE), 
	Ambito VARCHAR2(500 BYTE), 
	Cliente VARCHAR2(500 BYTE), 
	Responsabile di Struttura VARCHAR2(500 BYTE), 
	Responsabile del Servizio VARCHAR2(500 BYTE), 
	Responsabile di Gestione VARCHAR2(500 BYTE), 
	Referente di Gestione VARCHAR2(500 BYTE), 
	Referente dell applicazione VARCHAR2(500 BYTE), 
	Software a supporto VARCHAR2(500 BYTE), 
	Ambito manutenzione ordinar sw VARCHAR2(500 BYTE), 
	Tipologia Incarico VARCHAR2(500 BYTE), 
	Scheda Incarico VARCHAR2(500 BYTE), 
	Stato del servizio VARCHAR2(500 BYTE), 
	Tipologia Infrastruttura VARCHAR2(500 BYTE), 
	Classe di servizio infrstrttrl VARCHAR2(500 BYTE), 
	Ambito ASSI e GEST per RL VARCHAR2(500 BYTE), 
	Data Ultimo Aggiornamento VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table DM_ALM_WORKITEM_LINK_ROLES
--------------------------------------------------------

  CREATE TABLE DM_ALM_WORKITEM_LINK_ROLES 
   (	DSCRIZIONE VARCHAR2(4000 BYTE), 
	ID_RUOLO VARCHAR2(100 BYTE), 
	NOME_RUOLO VARCHAR2(500 BYTE), 
	NOME_RUOLO_INVERSO VARCHAR2(500 BYTE), 
	PARENT VARCHAR2(10 BYTE), 
	REPOSITORY VARCHAR2(20 BYTE), 
	TEMPLATES VARCHAR2(100 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Index SYS_C00253714
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253714 ON DM_ALM_C_SIRE_PROJECT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253698
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253698 ON DM_ALM_C_SIRE_WORKITEM (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253712
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253712 ON DM_ALM_C_SISS_PROJECT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253696
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253696 ON DM_ALM_C_SISS_WORKITEM (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253710
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253710 ON DM_ALM_H_SIRE_ATTACHMENT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253706
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253706 ON DM_ALM_H_SIRE_PROJECT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253702
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253702 ON DM_ALM_H_SIRE_PROJECTGROUP (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253694
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253694 ON DM_ALM_H_SIRE_REVISION (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253690
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253690 ON DM_ALM_H_SIRE_USER (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253686
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253686 ON DM_ALM_H_SIRE_WORKITEM (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253708
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253708 ON DM_ALM_H_SISS_ATTACHMENT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253704
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253704 ON DM_ALM_H_SISS_PROJECT (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253700
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253700 ON DM_ALM_H_SISS_PROJECTGROUP (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253692
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253692 ON DM_ALM_H_SISS_REVISION (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253688
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253688 ON DM_ALM_H_SISS_USER (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C00253684
--------------------------------------------------------

  CREATE UNIQUE INDEX SYS_C00253684 ON DM_ALM_H_SISS_WORKITEM (C_PK) 
  ;
--------------------------------------------------------
--  DDL for Index DM_ALM_MISURA_ID1
--------------------------------------------------------

  CREATE INDEX DM_ALM_MISURA_ID1 ON DM_ALM_MISURA (APPLICAZIONE) 
  ;
--------------------------------------------------------
--  DDL for Index DM_ALM_MISURA_ID2
--------------------------------------------------------

  CREATE INDEX DM_ALM_MISURA_ID2 ON DM_ALM_MISURA (NOME_MISURA) 
  ;
--------------------------------------------------------
--  DDL for Index DM_ALM_MISURA_ID3
--------------------------------------------------------

  CREATE INDEX DM_ALM_MISURA_ID3 ON DM_ALM_MISURA (NOME_PROGETTO) 
  ;
--------------------------------------------------------
--  Constraints for Table DM_ALM_C_SIRE_PROJECT
--------------------------------------------------------

  ALTER TABLE DM_ALM_C_SIRE_PROJECT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_C_SIRE_PROJECT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_C_SIRE_WORKITEM
--------------------------------------------------------

  ALTER TABLE DM_ALM_C_SIRE_WORKITEM ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_C_SIRE_WORKITEM MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_C_SISS_PROJECT
--------------------------------------------------------

  ALTER TABLE DM_ALM_C_SISS_PROJECT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_C_SISS_PROJECT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_C_SISS_WORKITEM
--------------------------------------------------------

  ALTER TABLE DM_ALM_C_SISS_WORKITEM ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_C_SISS_WORKITEM MODIFY (C_PK NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_ATTACHMENT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_ATTACHMENT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_PROJECT
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_PROJECT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_PROJECT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_PROJECTGROUP
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_PROJECTGROUP ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_PROJECTGROUP MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_REVISION
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_REVISION ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_REVISION MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_USER
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_USER ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_USER MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SIRE_WORKITEM
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SIRE_WORKITEM ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SIRE_WORKITEM MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_ATTACHMENT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_ATTACHMENT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_PROJECT
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_PROJECT ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_PROJECT MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_PROJECTGROUP
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_PROJECTGROUP ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_PROJECTGROUP MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_REVISION
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_REVISION ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_REVISION MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_USER
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_USER ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_USER MODIFY (C_PK NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DM_ALM_H_SISS_WORKITEM
--------------------------------------------------------

  ALTER TABLE DM_ALM_H_SISS_WORKITEM ADD PRIMARY KEY (C_PK) ENABLE;
  ALTER TABLE DM_ALM_H_SISS_WORKITEM MODIFY (C_PK NOT NULL ENABLE);
