SPOOL 331_TABELLE_CARICAMENTO_FONTE.sql

SET DEFINE OFF;
SET ECHO ON;
SET TIMING ON;
SET TIME ON;
SET SQLBLANKLINES ON;
CREATE TABLE DMALM_CARICAMENTO_FONTE (	
    COD_FONTE VARCHAR2(50 BYTE), 
	STATO_CARICAMENTO VARCHAR2(10 BYTE)
);

CREATE TABLE DMALM_FONTE_TABELLE (	
    COD_TABELLA VARCHAR2(50 BYTE), 
	FLAG_DELETE VARCHAR2(10 BYTE)
);
CREATE OR REPLACE PROCEDURE DELETE_DATI_FONTE_TABELLE AS 
CURSOR fonte_tabelle IS SELECT COD_TABELLA FROM DMALM_FONTE_TABELLE WHERE FLAG_DELETE = 'Y';
codTabella VARCHAR2(50);
BEGIN
   OPEN fonte_tabelle;
    LOOP 
        FETCH fonte_tabelle INTO codTabella;
        EXIT WHEN fonte_tabelle%NOTFOUND;
            EXECUTE IMMEDIATE 'TRUNCATE TABLE '||codTabella;
    END LOOP;
    CLOSE fonte_tabelle;
END DELETE_DATI_FONTE_TABELLE;