-- DAVIDE
ALTER TABLE DM_ALM_SV.BCK_MPS_BO_CONTRATTI MODIFY (CODDIREZIONE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.BCK_MPS_BO_CONTRATTI MODIFY (CODUO VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_EL_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_EL_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_PROGETTO_SFERA MODIFY (P_PRJ_AUDIT_MONITORE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_RELEASE_DI_PROGETTO MODIFY (ID_AUTORE_RELEASEDIPROG VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_RELEASE_DI_PROGETTO_ODS MODIFY (ID_AUTORE_RELEASEDIPROG VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_EL_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_EL_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_CONTRATTI MODIFY (CODUO VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_FIRMAT_VERBALE MODIFY (ENTE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_RESPON_CONTRATTO MODIFY (ENTE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (CODICE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (COD_RESPONSABILE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (NOME VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (COGNOME VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (ID_GRADO_UFFICIO VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (ID_SEDE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (TIPOPERSONA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (IDENTFICATORE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (COD_RESPONSABILE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (ID_SEDE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (TIPO_PERSONA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_TASK_IT MODIFY (ID_AUTORE_TASK_IT VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_TASK_IT_ODS MODIFY (ID_AUTORE_TASK_IT VARCHAR2(32));
ALTER TABLE DM_ALM_SV.MPS_BO_CONTRATTI MODIFY (CODDIREZIONE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.MPS_BO_CONTRATTI MODIFY (CODUO VARCHAR2(32));
ALTER TABLE DM_ALM_SV.MPS_BO_RESPONSABILI_CONTRATTO MODIFY (ENTE VARCHAR2(32));


-- SIMONE
ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_CONTRATTI MODIFY (CODDIREZIONE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_MPS_BO_CONTRATTI MODIFY (CODDIREZIONE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_RESPON_OFFERTA MODIFY (RAZIONALE_DIGITALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.MPS_BO_RESPONSABILI_OFFERTA MODIFY (RAZIONALE_DIGITALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_MPS_BO_RESPONSABILI_OFFERTA MODIFY (RAZIONALE_DIGITALE VARCHAR2(32));

UPDATE DM_ALM_SV.DMALM_STG_PERSONALE SET INTERNO = null;
ALTER TABLE DM_ALM_SV.DMALM_STG_PERSONALE MODIFY (INTERNO NUMBER);
UPDATE DM_ALM_SV.DMALM_STG_PERSONALE SET INTERNO = -1;

UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET INTERNO = null;
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (INTERNO NUMBER);
UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET INTERNO = -1;

UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET ID_GRADO_UFFICIO = null;
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (ID_GRADO_UFFICIO NUMBER);
UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET ID_GRADO_UFFICIO = -1;

UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET ID_TIPOLOGIA_UFFICIO = null;
ALTER TABLE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE MODIFY (ID_TIPOLOGIA_UFFICIO NUMBER);
UPDATE DM_ALM_SV.DMALM_STG_UNITA_ORGANIZZATIVE SET ID_TIPOLOGIA_UFFICIO = -1;

ALTER TABLE DM_ALM_SV.DMALM_STG_MPS_ATTIVITA MODIFY (TITOLO VARCHAR2(300));
ALTER TABLE DM_ALM_SV.MPS_BO_ATTIVITA MODIFY (TITOLO VARCHAR2(300));
ALTER TABLE DM_ALM_SV.T_MPS_BO_ATTIVITA MODIFY (TITOLO VARCHAR2(300));
ALTER TABLE DM_ALM_SV.DMALM_CHANGED_WORKITEM MODIFY (TYPE VARCHAR2(50));

ALTER TABLE DM_ALM_SV.T_MPS_BO_CONTRATTI MODIFY (CODUO VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_MPS_BO_RESPONS_CONTRATTO MODIFY (ENTE VARCHAR2(32));

ALTER TABLE DM_ALM_SV.T_DMALM_EL_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_DMALM_PROGETTO_SFERA MODIFY (P_PRJ_AUDIT_MONITORE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_DMALM_RELEASE_DI_PROGETTO MODIFY (ID_AUTORE_RELEASEDIPROG VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_DMALM_TASK_IT MODIFY (ID_AUTORE_TASK_IT VARCHAR2(32));

ALTER TABLE DM_ALM_SV.T_DMALM_PERSONALE MODIFY (MATRICOLA VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_DMALM_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));
ALTER TABLE DM_ALM_SV.T_DMALM_EL_PERSONALE MODIFY (CODICE_FISCALE VARCHAR2(32));

ALTER TABLE DM_ALM_SV.DMALM_TEMPLATE_SVILUPPO MODIFY (ID_FILIERA NUMBER(10));
ALTER TABLE DM_ALM_SV.T_DMALM_TEMPLATE_SVILUPPO MODIFY (ID_FILIERA NUMBER(10));









