alter table DM_ALM_SV.DMALM_STG_EL_PRODOTTI_ARCH add(AMBITO_TECNOLOGICO VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_STG_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_DENOM VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_STG_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_CODICE VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_STG_EL_PRODOTTI_ARCH add(STATO_PRODOTTO VARCHAR2(100));

alter table DM_ALM_SV.DMALM_EL_PRODOTTI_ARCH add(AMBITO_TECNOLOGICO VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_DENOM VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_CODICE VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_EL_PRODOTTI_ARCH add(STATO_PRODOTTO VARCHAR2(100));

alter table DM_ALM_SV.T_DMALM_EL_PRODOTTI_ARCH add(AMBITO_TECNOLOGICO VARCHAR2(4000));
alter table DM_ALM_SV.T_DMALM_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_DENOM VARCHAR2(4000));
alter table DM_ALM_SV.T_DMALM_EL_PRODOTTI_ARCH add(AMBITO_MANUTENZIONE_CODICE VARCHAR2(4000));
alter table DM_ALM_SV.T_DMALM_EL_PRODOTTI_ARCH add(STATO_PRODOTTO VARCHAR2(100));
