rename table DMALM_CLASSIFICATORE_DEMAND TO DMALM_CLASSIFICATORE
rename table DMALM_CLASSIFICATORE_DEM_ODS TO DMALM_CLASSIFICATORE_ODS
rename table T_DMALM_CLASSIFICATORE_DEMAND TO T_DMALM_CLASSIFICATORE

--alter table DM_ALM_SV.DMALM_SIRE_HISTORY_PROJECT add(RM_RESPONSABILI_PROGETTO VARCHAR2(4000));
--alter table DM_ALM_SV.DMALM_SIRE_HISTORY_PROJECT add(PROGETTO_IN_DEROGA BOOLEAN);
--alter table DM_ALM_SV.DMALM_SIRE_HISTORY_PROJECT add(ASSIGNEE_PROGETTO_IT_IN_DEROGA VARCHAR2(32));
--alter table DM_ALM_SV.DMALM_SIRE_HISTORY_PROJECT add(LOCATION_SORGENTI VARCHAR2(4000));

--alter table DM_ALM_SV.DMALM_SISS_HISTORY_PROJECT add(RM_RESPONSABILI_PROGETTO VARCHAR2(4000));
--alter table DM_ALM_SV.DMALM_SISS_HISTORY_PROJECT add(PROGETTO_IN_DEROGA BOOLEAN);
--alter table DM_ALM_SV.DMALM_SISS_HISTORY_PROJECT add(ASSIGNEE_PROGETTO_IT_IN_DEROGA VARCHAR2(32));
--alter table DM_ALM_SV.DMALM_SISS_HISTORY_PROJECT add(LOCATION_SORGENTI VARCHAR2(4000));

alter table DM_ALM_SV.DMALM_CLASSIFICATORE add(RM_RESPONSABILI_PROGETTO VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE add(PROGETTO_IN_DEROGA BOOLEAN);
alter table DM_ALM_SV.DMALM_CLASSIFICATORE add(ASSIGNEE_PROGETTO_IT_IN_DEROGA VARCHAR2(32));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE add(LOCATION_SORGENTI VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE add(TYPE VARCHAR2(50));

alter table DM_ALM_SV.DMALM_CLASSIFICATORE_ODS add(RM_RESPONSABILI_PROGETTO VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE_ODS add(PROGETTO_IN_DEROGA BOOLEAN);
alter table DM_ALM_SV.DMALM_CLASSIFICATORE_ODS add(ASSIGNEE_PROGETTO_IT_IN_DEROGA VARCHAR2(32));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE_ODS add(LOCATION_SORGENTI VARCHAR2(4000));
alter table DM_ALM_SV.DMALM_CLASSIFICATORE_ODS add(TYPE VARCHAR2(50));

alter table DM_ALM_SV.T_DMALM_CLASSIFICATORE add(RM_RESPONSABILI_PROGETTO VARCHAR2(4000));
alter table DM_ALM_SV.T_DMALM_CLASSIFICATORE add(PROGETTO_IN_DEROGA BOOLEAN);
alter table DM_ALM_SV.T_DMALM_CLASSIFICATORE add(ASSIGNEE_PROGETTO_IT_IN_DEROGA VARCHAR2(32));
alter table DM_ALM_SV.T_DMALM_CLASSIFICATORE add(LOCATION_SORGENTI VARCHAR2(4000));
alter table DM_ALM_SV.T_DMALM_CLASSIFICATORE add(TYPE VARCHAR2(50));

UPDATE DM_ALM_SV.DMALM_CLASSIFICATORE SET type = 'classificatore_demand' WHERE DMALM_CLASSIFICATORE_PK in 
(select c.DMALM_CLASSIFICATORE_PK from DMALM_CLASSIFICATORE_DEMAND c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');
UPDATE DM_ALM_SV.DMALM_CLASSIFICATORE SET type = 'classificatore' WHERE DMALM_CLASSIFICATORE_PK not in 
(select c.DMALM_CLASSIFICATORE_PK from DMALM_CLASSIFICATORE_DEMAND c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');
UPDATE DM_ALM_SV.DMALM_CLASSIFICATORE_ODS SET type = 'classificatore_demand' WHERE DMALM_CLASSIFICATORE_PK in 
(select c.DMALM_CLASSIFICATORE_PK from DMALM_CLASSIFICATORE_ODS c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');
UPDATE DM_ALM_SV.DMALM_CLASSIFICATORE_ODS SET type = 'classificatore' WHERE DMALM_CLASSIFICATORE_PK not in 
(select c.DMALM_CLASSIFICATORE_PK from DMALM_CLASSIFICATORE_ODS c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');
UPDATE DM_ALM_SV.T_DMALM_CLASSIFICATORE SET type = 'classificatore_demand' WHERE DMALM_CLASSIFICATORE_PK in 
(select c.DMALM_CLASSIFICATORE_PK from T_DMALM_CLASSIFICATORE c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');
UPDATE DM_ALM_SV.T_DMALM_CLASSIFICATORE SET type = 'classificatore' WHERE DMALM_CLASSIFICATORE_PK not in 
(select c.DMALM_CLASSIFICATORE_PK from T_DMALM_CLASSIFICATORE c, DMALM_PROJECT p where c.DMALM_PROJECT_FK_02 = p.DMALM_PROJECT_PK AND p.TEMPLATE = 'DEMAND2016');