ALTER TABLE DM_ALM_SV.DMALM_ANOMALIA_PRODOTTO add(DATA_DISPONIBILITA DATE);
ALTER TABLE DM_ALM_SV.DMALM_ANOMALIA_PRODOTTO_ODS add(DATA_DISPONIBILITA TIMESTAMP);
ALTER TABLE DM_ALM_SV.T_DMALM_ANOMALIA_PRODOTTO add(DATA_DISPONIBILITA DATE);
ALTER TABLE DM_ALM_SV.DMALM_ANOMALIA_PRODOTTO_DUMMY add(DATA_DISPONIBILITA DATE);


ALTER TABLE DM_ALM_SV.DMALM_DIFETTO_PRODOTTO add(DATA_DISPONIBILITA DATE);
ALTER TABLE DM_ALM_SV.DMALM_DIFETTO_PRODOTTO_ODS add(DATA_DISPONIBILITA TIMESTAMP);
ALTER TABLE DM_ALM_SV.T_DMALM_DIFETTO_PRODOTTO add(DATA_DISPONIBILITA DATE);
ALTER TABLE DM_ALM_SV.DMALM_DIFETTO_PRODOTTO_DUMMY add(DATA_DISPONIBILITA DATE);
