alter table DM_ALM_SV.DMALM_EL_PERSONALE add(DMALM_UNITAORGANIZZATIVA_FK_01 NUMBER(15));
alter table DM_ALM_SV.DMALM_EL_PERSONALE add(DMALM_UNITAORGANIZZ_FLAT_FK_02 NUMBER(15));

alter table DM_ALM_SV.T_DMALM_EL_PERSONALE add(DMALM_UNITAORGANIZZATIVA_FK_01 NUMBER(15));
alter table DM_ALM_SV.T_DMALM_EL_PERSONALE add(DMALM_UNITAORGANIZZ_FLAT_FK_02 NUMBER(15));

alter table DM_ALM_SV.DMALM_STG_EL_PRODOTTI_ARCH add(CD_RESPONSABILE_PRODOTTO VARCHAR2(32));
