alter table DM_ALM_SV.DMALM_EL_PRODOTTI_ARCH add(DMALM_UNITAORG_FLAT_FK_03 NUMBER(15));
alter table DM_ALM_SV.T_DMALM_EL_PRODOTTI_ARCH add(DMALM_UNITAORG_FLAT_FK_03 NUMBER(15));

alter table DM_ALM_SV.DMALM_ASM add(DMALM_UNITAORG_FLAT_FK_04 NUMBER(15));
alter table DM_ALM_SV.T_DMALM_ASM add(DMALM_UNITAORG_FLAT_FK_04 NUMBER(15));


