 SELECT
	distinct(p.C_ID) as CD_AREA_TEMATICA, 
	p.SIRE_HISTORY_PROJECT_PK as DMALM_AREA_TEMATICA_PK,
	pg.C_NAME as DS_AREA_TEMATICA,
	p.DATA_CARICAMENTO as DT_CARICAMENTO
 FROM 
 DMALM_SIRE_HISTORY_PROJECT p left join DMALM_SIRE_HISTORY_PROJGROUP pg on p.FK_URI_PROJECTGROUP = pg.C_PK
 where p.C_LOCATION like 'default:/Sviluppo/%'
	and LENGTH(p.C_LOCATION) - LENGTH(REPLACE(p.C_LOCATION, '/', '')) > 4
	and p.DATA_CARICAMENTO = pg.DATA_CARICAMENTO
	and p.DATA_CARICAMENTO = ?
union ALL  
 SELECT 
	distinct(p.C_ID) as CD_AREA_TEMATICA, 
	p.SISS_HISTORY_PROJECT_PK as DMALM_AREA_TEMATICA_PK,
	pg.C_NAME as DS_AREA_TEMATICA,
	p.DATA_CARICAMENTO as DT_CARICAMENTO
 FROM 
 DMALM_SISS_HISTORY_PROJECT p left join DMALM_SISS_HISTORY_PROJGROUP pg on p.FK_URI_PROJECTGROUP = pg.C_PK
 where 
	p.C_LOCATION like 'default:/Sviluppo/%'
	and LENGTH(p.C_LOCATION) - LENGTH(REPLACE(p.C_LOCATION, '/', '')) > 4
	and p.DATA_CARICAMENTO = pg.DATA_CARICAMENTO
	and p.DATA_CARICAMENTO =  ?