SELECT 
 UO.DMALM_STG_UNITA_ORG_PK,
 UO.ID_EDMA,
 UO.CD_AREA,
 UO.DT_INIZIO_VALIDITA_EDMA,
 UO.DT_FINE_VALIDITA_EDMA,
 UO.DS_AREA_EDMA,
 UO.DT_ATTIVAZIONE,
 UO.DT_DISATTIVAZIONE,
 UO.NOTE,
 UO.INTERNO,
 UO.CD_RESPONSABILE_AREA,
 UO.INDIRIZZO_EMAIL,
 UO.ID_TIPOLOGIA_UFFICIO,
 UO.ID_GRADO_UFFICIO,
 UO.ID_SEDE,
 NVL(UO.CD_UO_SUPERIORE, 'ARIA S.P.A') AS CD_UO_SUPERIORE,
 UOSUP.DS_AREA_EDMA AS DS_UO_SUPERIORE,
 UO.CD_ENTE,
 UO.CD_VISIBILITA,
 UO.DT_CARICAMENTO 
FROM DMALM_STG_EL_UNITA_ORGANIZZ UO 
LEFT JOIN DMALM_STG_EL_UNITA_ORGANIZZ UOSUP 
     ON NVL(UO.CD_UO_SUPERIORE, 'ARIA S.P.A') = UOSUP.CD_AREA AND UO.DT_CARICAMENTO = UOSUP.DT_CARICAMENTO 
WHERE UO.DT_CARICAMENTO = ? 
