SELECT 
	f.DMALM_STG_FUNZIONALITA_PK, 
	f.ID_FUNZIONALITA_EDMA, 
	f.ID_EDMA_PADRE, 
	f.ID_FUNZIONALITA, 
	f.TIPO_OGGETTO, 
	f.SIGLA_PRODOTTO, 
	f.SIGLA_SOTTOSISTEMA, 
	f.SIGLA_MODULO, 
	f.SIGLA_FUNZIONALITA, 
	f.NOME, 
	f.DS_FUNZIONALITA, 
		CASE 
		WHEN INSTR(f.NOME, 'ANNULLATO') > 0 THEN 'SI' 
		ELSE 'NO' 
	END AS ANNULLATO, 
	CASE 
		WHEN 
			LENGTH(REGEXP_SUBSTR(f.NOME, '##[a-zA-Z0-9_.*!?-]+#'))=11 and INSTR(f.NOME, 'ANNULLATO') > 0 
		THEN 
			TO_TIMESTAMP(replace(replace(REGEXP_SUBSTR(f.NOME, '##[a-zA-Z0-9_.*!?-]+#'),'##',''),'#',''),'yyyymmdd') 
		ELSE 
			null 
	END AS DT_ANNULLAMENTO, 
	f.CATEGORIA, 
	f.LINGUAGGI, 
	f.TIPI_ELABORAZIONE, 
	f.DT_CARICAMENTO, 
    NVL(CASE WHEN f.SIGLA_MODULO is null 
      THEN 0 
       ELSE  
         ( SELECT m.DMALM_MODULO_PK FROM DMALM_EL_MODULI m where m.SIGLA_MODULO = f.SIGLA_MODULO and m.DT_CARICAMENTO = 
                                                     (SELECT MAX(DT_CARICAMENTO) FROM DMALM_EL_MODULI mx where mx.SIGLA_MODULO = f.SIGLA_MODULO) )  
 END, 0) as MODULO_FK 
 from DMALM_STG_EL_FUNZIONALITA f  
 where f.DT_CARICAMENTO =  ? 
 
  
	
	