select
 DMALM_STG_CLASSIFICATORI_PK,
 ID_CLASSIFICATORE_ORESTE,
 TIPO_CLASSIFICATORE,
 CODICE_CLASSIFICATORE,
 DT_CARICAMENTO 
from DMALM_STG_EL_CLASSIFICATORI  
where DT_CARICAMENTO = ? 
and TIPO_CLASSIFICATORE is not null 
and CODICE_CLASSIFICATORE is not null 
