SELECT
 at.DMALM_STG_AMB_TECNOLOGICO_PK,
 at.ID_AMB_TECNOLOGICO_EDMA,
 at.ID_AMB_TECNOLOGICO_EDMA_PADRE,
 at.ID_AMB_TECNOLOGICO,
 at.SIGLA_PRODOTTO,
 at.SIGLA_MODULO,
 at.NOME,
 at.ARCHITETTURA,
 at.INFRASTRUTTURA,
 at.SISTEMA_OPERATIVO,
 at.TIPO_LAYER,
 at.VERSIONE_SO,
 at.DS_AMBIENTE_TECNOLOGICO,
 at.DT_CARICAMENTO,
 CASE
  WHEN INSTR(at.NOME, 'ANNULLATO') > 0 
  THEN 'SI'
  ELSE 'NO'
 END AS ANNULLATO,
 CASE
  WHEN LENGTH(REGEXP_SUBSTR(at.NOME, '##[a-zA-Z0-9_.*!?-]+#'))=11 and INSTR(at.NOME, 'ANNULLATO') > 0
  THEN TO_TIMESTAMP(replace(replace(REGEXP_SUBSTR(at.NOME, '##[a-zA-Z0-9_.*!?-]+#'),'##',''),'#',''),'yyyymmdd')
  ELSE NULL
 END AS DT_ANNULLAMENTO,
 NVL(CASE WHEN at.SIGLA_PRODOTTO is null
       THEN 0
       ELSE ( SELECT p.DMALM_PRODOTTO_PK FROM DMALM_EL_PRODOTTI_ARCH p where p.SIGLA = at.SIGLA_PRODOTTO and p.DT_CARICAMENTO = (SELECT MAX(DT_CARICAMENTO) FROM DMALM_EL_PRODOTTI_ARCH mx where mx.SIGLA = at.SIGLA_PRODOTTO) ) 
 END, 0) as PRODOTTO_FK,
 NVL(CASE WHEN SIGLA_MODULO is null
       THEN 0
       ELSE ( SELECT m.DMALM_MODULO_PK FROM DMALM_EL_MODULI m where m.SIGLA_MODULO = at.SIGLA_MODULO and m.DT_CARICAMENTO = (SELECT MAX(DT_CARICAMENTO) FROM DMALM_EL_MODULI mx where mx.SIGLA_MODULO = at.SIGLA_MODULO) ) 
 END, 0) as MODULO_FK 
FROM DMALM_STG_EL_AMBIENTE_TECNO at 
WHERE at.DT_CARICAMENTO  = ? 
