SELECT 
	f.DMALM_STG_FUNZIONALITA_PK as DMALM_FUNZIONALITA_SEQ,
	f.ID_EDMA_FUNZIONALITA as ID_EDMA,
	NVL(m.ID_EDMA_MODULO,0) as ID_EDMA_PADRE,
	f.ID_FUNZIONALITA as ID_FUNZIONALITA,
	f.TIPO_FUNZIONALITA as TIPO_OGGETTO,
	f.SIGLA_PRODOTTO as SIGLA_PRODOTTO,
	f.SIGLA_SOTTOSISTEMA as SIGLA_SOTTOSISTEMA,
	f.SIGLA_MODULO as SIGLA_MODULO,
	f.SIGLA_FUNZIONALITA as SIGLA_FUNZIONALITA,
	f.NOME_FUNZIONALITA as NOME,
	f.DESCRIZIONE as DS_FUNZIONALITA,
		CASE
		WHEN INSTR(f.NOME_FUNZIONALITA, 'ANNULLATO') > 0 THEN 'SI'
		ELSE 'NO'
	END AS ANNULLATO,
	CASE
		WHEN
			LENGTH(REGEXP_SUBSTR(f.NOME_FUNZIONALITA, '##[a-zA-Z0-9_.*!?-]+#'))=11 and INSTR(f.NOME_FUNZIONALITA, 'ANNULLATO') > 0
		THEN
			TO_TIMESTAMP(replace(replace(REGEXP_SUBSTR(f.NOME_FUNZIONALITA, '##[a-zA-Z0-9_.*!?-]+#'),'##',''),'#',''),'yyyymmdd')
		ELSE
			{ts '9999-12-31 00:00:00'}
	END AS DATA_ANNULLAMENTO,
	f.CLASF_CATEGORIA as CATEGORIA,
	f.CLASF_LINGUAGGIO_DI_PROG as LINGUAGGI,
	f.CLASF_TIPO_ELABOR as TIPI_ELABORAZIONE
	from 
	DMALM_STG_FUNZIONALITA f left join DMALM_STG_MODULI m on f.ID_EDMA_PADRE = m.ID_EDMA_MODULO and f.DATA_CARICAMENTO = m.DATA_CARICAMENTO
	where f.DATA_CARICAMENTO = ? 
	