SELECT * 
FROM DMALM_EL_FUNZIONALITA p1 
WHERE DMALM_MODULO_FK_01 = ? 
AND DT_FINE_VALIDITA = (SELECT MAX (DT_FINE_VALIDITA) FROM DMALM_EL_FUNZIONALITA p2 WHERE p1.ID_FUNZIONALITA=p2.ID_FUNZIONALITA) 
AND NOME NOT LIKE '#ANNULLATO FISICAMENTE##%' 