SELECT * 
FROM DMALM_EL_FUNZIONALITA p1 
WHERE p1.ID_FUNZIONALITA NOT IN (SELECT ID_FUNZIONALITA FROM DMALM_STG_EL_FUNZIONALITA WHERE DT_CARICAMENTO = ?) 
AND DT_FINE_VALIDITA = (SELECT MAX(DT_FINE_VALIDITA) FROM DMALM_STG_EL_FUNZIONALITA p2 WHERE p1.ID_FUNZIONALITA=p2.ID_FUNZIONALITA) 
AND p1.DMALM_FUNZIONALITA_PK>0 
AND p1.NOME NOT LIKE '#ANNULLATO FISICAMENTE##%' 