update dmalm_anomalia_prodotto wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_anomalia_prodotto wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_anomalia_assistenza wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_anomalia_assistenza wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_build wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_build wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_classificatore wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_classificatore wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_difetto_prodotto wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_difetto_prodotto wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_richiesta_manutenzione wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_richiesta_manutenzione wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_documento wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_documento wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_sviluppo_dem wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_sviluppo_dem wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_fase wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_fase wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
 update dmalm_pei wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_pei wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_ese wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_ese wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_programma wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_programma wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_di_progetto wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_di_progetto wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_it wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_it wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_servizi wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_release_servizi wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
 update dmalm_richiesta_gestione wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_richiesta_gestione wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_demand wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_demand wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_manutenzione wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_manutenzione wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_sottoprogramma wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_sottoprogramma wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_sviluppo_svil wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_progetto_sviluppo_svil wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_task wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_task wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_task_it wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_task_it wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02)  
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_testcase wi set annullato = (
select annullato from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02) 
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
update dmalm_testcase wi set dt_annullamento = (
select dt_annullamento from dmalm_project where DMALM_PROJECT_PK = wi.dmalm_project_fk_02) 
where not nvl(annullato, 'NULL') = 'ANNULLATO FISICAMENTE'; 
