	update dmalm_anomalia_prodotto wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02);
	update dmalm_anomalia_assistenza wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_build wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update DMALM_CLASSIFICATORE_DEMAND wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_difetto_prodotto wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_richiesta_manutenzione wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_documento wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_progetto_sviluppo_dem wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_fase wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_pei wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_progetto_ese wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_programma wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_release_di_progetto wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_release_it wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_release_servizi wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_richiesta_gestione wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_progetto_demand wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_manutenzione wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_sottoprogramma wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_progetto_sviluppo_svil wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_task wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_task_it wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02); 
	update dmalm_testcase wi set DMALM_STRUTTURA_ORG_FK_01 = (
	select DMALM_UNITAORGANIZZATIVA_FK_03 from dmalm_project p where p.DMALM_PROJECT_PK = wi.DMALM_PROJECT_FK_02);