	select
		m.DMALM_STG_MODULI_PK as DMALM_MODULO_SEQ,
		m.ID_EDMA_MODULO as ID_EDMA,
		NVL(CASE
			WHEN p.ID_EDMA_PRODOTTO is null
			THEN ( SELECT s.ID_EDMA_PADRE_SOTTOSISTEMA FROM DMALM_STG_SOTTOSISTEMI s where s.ID_EDMA_SOTTOSISTEMA = m.ID_EDMA_PADRE_MODULO and m.DATA_CARICAMENTO = s.DATA_CARICAMENTO ) 
			ELSE p.ID_EDMA_PRODOTTO
		END, 0) as ID_EDMA_PADRE_PRODOTTO,
		NVL(CASE
			WHEN p.ID_EDMA_PRODOTTO is null
			THEN ( SELECT s.ID_EDMA_SOTTOSISTEMA FROM DMALM_STG_SOTTOSISTEMI s where s.ID_EDMA_SOTTOSISTEMA = m.ID_EDMA_PADRE_MODULO and m.DATA_CARICAMENTO = s.DATA_CARICAMENTO )  
			ELSE 0
		END,0) as ID_EDMA_PADRE_SOTTOSISTEMA,
		m.ID_EDMA_PADRE_MODULO,
		m.ID_MODULO as ID_MODULO,
		m.TIPO_OGGETTO as TIPO_OGGETTO,
		m.SIGLA_PRODOTTO_MODULO as SIGLA_PRODOTTO,
		m.SIGLA_SOTTOSISTEMA_MODULO as SIGLA_SOTTOSISTEMA,
		m.SIGLA_MODULO as SIGLA_MODULO,
		m.NOME_MODULO as NOME,
		m.DESCRIZIONE_MODULO as DS_MODULO,
		CASE
			WHEN INSTR(m.NOME_MODULO, 'ANNULLATO') > 0 THEN 'SI'
			ELSE 'NO'
		END AS ANNULLATO,
		CASE
			WHEN
				LENGTH(REGEXP_SUBSTR(m.NOME_MODULO, '##[a-zA-Z0-9_.*!?-]+#'))=11 and INSTR(m.NOME_MODULO, 'ANNULLATO') > 0
			THEN
				TO_TIMESTAMP(replace(replace(REGEXP_SUBSTR(m.NOME_MODULO, '##[a-zA-Z0-9_.*!?-]+#'),'##',''),'#',''),'yyyymmdd')
			ELSE
				{ts '9999-12-31 00:00:00'}
		END AS DATA_ANNULLAMENTO,
		NVL(
		NVL(pers_target.DMALM_PERSONALE_PK,
		(	SELECT personale.DMALM_PERSONALE_PK 
			FROM DMALM_STG_SOTTOSISTEMI s, DMALM_STG_PROD_ARCHITETTURE p, DMALM_STG_PERSONALE stg_personale, DMALM_PERSONALE personale
			where p.ID_EDMA_PRODOTTO = s.ID_EDMA_PADRE_SOTTOSISTEMA 
			and s.ID_EDMA_SOTTOSISTEMA = m.ID_EDMA_PADRE_MODULO 
			and m.DATA_CARICAMENTO = s.DATA_CARICAMENTO 
			and m.DATA_CARICAMENTO =  p.DATA_CARICAMENTO
			and stg_personale.CODICE = replace(replace(REGEXP_SUBSTR(p.EDMA_RESP_PRODOTTO, '{[a-zA-Z0-9_.*!?-]+}'),'{',''),'}','')
			and stg_personale.DATA_CARICAMENTO = m.DATA_CARICAMENTO and stg_personale.DATA_FINE_VALIDITA = '9999-12-31 00:00:00'
			and personale.CD_PERSONALE = stg_personale.CODICE and personale.DT_FINE_VALIDITA = {ts '9999-12-31 00:00:00'} )
		), 0) AS RESPONSABILE,
		m.CLASF_SOTTOSISTEMA_MODULO as SOTTOSISTEMA,
		m.CLASF_TECNOLOGIA_MODULO as TECNOLOGIE,
		m.CLASF_TIPOLOGIA_MODULO as TIPO_MODULO
	from 
	DMALM_STG_MODULI m 
		left join DMALM_STG_PROD_ARCHITETTURE p on p.ID_EDMA_PRODOTTO = m.ID_EDMA_PADRE_MODULO and m.DATA_CARICAMENTO = p.DATA_CARICAMENTO
			left join DMALM_STG_PERSONALE pers on pers.CODICE =  replace(replace(REGEXP_SUBSTR(p.EDMA_RESP_PRODOTTO, '{[a-zA-Z0-9_.*!?-]+}'),'{',''),'}','') and pers.DATA_CARICAMENTO = p.DATA_CARICAMENTO and pers.DATA_FINE_VALIDITA = '9999-12-31 00:00:00'
				left join DMALM_PERSONALE pers_target on pers_target.CD_PERSONALE = pers.CODICE and pers_target.DT_FINE_VALIDITA = {ts '9999-12-31 00:00:00'}
	where m.DATA_CARICAMENTO = ?