	SELECT
		p.DMALM_STG_PROD_ARCHITETTURE_PK as DMALM_PRODOTTO_SEQ,
		p.ID_EDMA_PRODOTTO as ID_EDMA,
		p.ID_PRODOTTO as ID_PRODOTTO,
		p.TIPO_OGGETTO as TIPO_OGGETTO,
		p.SIGLA_PRODOTTO as SIGLA,
		p.NOME_PRODOTTO as NOME,
		p.DESCRIZIONE_PRODOTTO as DS_PRODOTTO,
		NVL(DMALM_PERSONALE.DMALM_PERSONALE_PK, 0) as RESPONSABILE_AREA,
		NVL(DMALM_UNITA_ORGANIZZATIVA.DMALM_UNITA_ORG_PK, 0) as AREA,
		case
		WHEN INSTR(p.NOME_PRODOTTO, '#ANNULLATO LOGICAMENTE#') > 0 THEN 'SI'
		ELSE 'NO'
		end as ANNULLATO,
		CASE
		WHEN INSTR(p.NOME_PRODOTTO, '#ANNULLATO LOGICAMENTE#') > 0 and instr(p.NOME_PRODOTTO, '#ANNULLATO LOGICAMENTE##')=1 and substr(p.NOME_PRODOTTO,instr(p.NOME_PRODOTTO, '##')+10,1) = '#' THEN TO_TIMESTAMP(substr(p.NOME_PRODOTTO, instr(p.NOME_PRODOTTO, '#ANNULLATO LOGICAMENTE##')+24,8),'yyyymmdd')
		else {ts '9999-12-31 00:00:00'}
		end as DATA_ANNULLAMENTO,
		p.NOME_PRODOTTO as NOME_PRODOTTO,
		p.CLASF_AMBITO_MANUTENZIONE as AMBITO_MANUTENZIONE,
		p.CLASF_AREA_TEMATICA as AREA_TEMATICA,
		p.CLASF_BASE_DATI_ETL as BASE_DATI_ETL,
		p.CLASF_BASE_DATI_LETTURA as BASE_DATI_LETTURA,
		p.CLASF_BASE_DATI_SCRITTURA as BASE_DATI_SCRITTURA,
		p.CLASF_CATEGORIA as CATEGORIA,
		p.CLASF_FORN_RIS_EST_GARA as FORNITURA_RISORSE_ESTERNE
	FROM 
		DMALM_STG_PROD_ARCHITETTURE p
			left join DMALM_STG_PERSONALE pers on pers.CODICE =  replace(replace(REGEXP_SUBSTR(p.EDMA_RESP_PRODOTTO, '{[a-zA-Z0-9_.*!?-]+}'),'{',''),'}','') and pers.DATA_CARICAMENTO = p.DATA_CARICAMENTO and pers.DATA_FINE_VALIDITA = '9999-12-31 00:00:00'
				left join DMALM_STG_UNITA_ORGANIZZATIVE uo on uo.codice = TRIM(substr(p.EDMA_AREA_PRODOTTO,0,INSTR(p.EDMA_AREA_PRODOTTO,'-')-1)) and uo.DATA_CARICAMENTO = p.DATA_CARICAMENTO and uo.DATA_FINE_VALIDITA = '9999-12-31 00:00:00'
					left join DMALM_PERSONALE on DMALM_PERSONALE.CD_PERSONALE = pers.CODICE and DMALM_PERSONALE.DT_FINE_VALIDITA = {ts '9999-12-31 00:00:00'}
						left join DMALM_UNITA_ORGANIZZATIVA on DMALM_UNITA_ORGANIZZATIVA.CD_AREA = uo.codice and DMALM_UNITA_ORGANIZZATIVA.DT_FINE_VALIDITA = {ts '9999-12-31 00:00:00'}
	where p.DATA_CARICAMENTO = ? 
