    select
	    s.DMALM_STG_SOTTOSISTEMI_PK as DMALM_SOTTOSISTEMA_PK,
		s.ID_EDMA_SOTTOSISTEMA as ID_EDMA,
		NVL(p.ID_EDMA_PRODOTTO, 0) as ID_EDMA_PADRE,
		s.ID_SOTTOSISTEMA as ID_SOTTOSISTEMA,
		s.TIPO_OGGETTO as TIPO_OGGETTO,
		s.SIGLA_PRODOTTO_SOTTOSISTEMA as SIGLA_PRODOTTO,
		s.SIGLA_SOTTOSISTEMA as SIGLA_SOTTOSISTEMA,
		s.NOME_SOTTOSISTEMA as NOME,
		s.DESCRIZIONE_SOTTOSISTEMA as DS_SOTTOSISTEMA,
		CASE
			WHEN INSTR(s.NOME_SOTTOSISTEMA, 'ANNULLATO') > 0 THEN 'SI'
			ELSE 'NO'
		END AS ANNULLATO,
		case
			when
				INSTR(s.NOME_SOTTOSISTEMA, 'ANNULLATO') > 0 and LENGTH(REGEXP_SUBSTR(s.NOME_SOTTOSISTEMA, '##[a-zA-Z0-9_.*!?-]+#'))=11
			then
				TO_TIMESTAMP(replace(replace(REGEXP_SUBSTR(s.NOME_SOTTOSISTEMA, '##[a-zA-Z0-9_.*!?-]+#'),'##',''),'#',''),'yyyymmdd')
			else
				{ts '9999-12-31 00:00:00'}
		end as DATA_ANNULLAMENTO,
		s.CLASF_TIPO_SOTTOSISTEMA as TIPO,
		s.CLASF_BASE_DATI_ETL as BASE_DATI_ETL,
		s.CLASF_BASE_DATI_LETTURA as BASE_DATI_LETTURA,
		s.CLASF_BASE_DATI_SCRITTURA as BASE_DATI_SCRITTURA
	from 
		DMALM_STG_SOTTOSISTEMI s left join DMALM_STG_PROD_ARCHITETTURE p on s.ID_EDMA_PADRE_SOTTOSISTEMA = p.ID_EDMA_PRODOTTO and s.DATA_CARICAMENTO=p.DATA_CARICAMENTO
	where 
		s.DATA_CARICAMENTO = ? 