 SELECT 
	uo.ID as ID_EDMA,
	uo.DATA_ATTIVAZIONE as DT_ATTIVAZIONE,
	uo.DATA_DISATTIVAZIONE as DT_DISATTIVAZIONE,
	uo.DATA_INIZIO_VALIDITA as DT_INIZIO_VALIDITA,
	uo.DATA_FINE_VALIDITA as DT_FINE_VALIDITA,
	uo.NOTE as NOTE,
	uo.ID_TIPOLOGIA_UFFICIO as ID_TIPOLOGIA_UFFICIO,
	uo.ID_GRADO_UFFICIO as ID_GRADO_UFFICIO,
	uo.ID_SEDE as ID_SEDE,
	uo.COD_VISIBILITA as CD_VISIBILITA,
	uo.COD_ENTE as CD_ENTE,
	uo.INDIRIZZO_EMAIL as EMAIL,
	uo.INTERNO as INTERNO,
	uo.DATA_CARICAMENTO as DT_CARICAMENTO,
	uo.DMALM_STG_UNITA_ORG_PK as DMALM_STRUTTURA_ORG_PK,
	uo.CODICE as CD_AREA,
	uo.DESCRIZIONE as DS_AREA_EDMA,
	NVL(uo.COD_SUPERIORE, 'LISPA') as CD_UO_SUPERIORE,
	uo.COD_RESPONSABILE as CD_RESPONSABILE_AREA,
	personale.IDENTFICATORE as DN_RESPONSABILE_AREA, 
	uosup.DESCRIZIONE as DS_UO_SUPERIORE
 FROM DMALM_STG_UNITA_ORGANIZZATIVE uo 
 	left join  DMALM_STG_PERSONALE personale 
 	on uo.COD_RESPONSABILE = personale.CODICE and uo.DATA_CARICAMENTO = personale.DATA_CARICAMENTO
 		left join DMALM_STG_UNITA_ORGANIZZATIVE uosup 
 		on uo.COD_SUPERIORE = uosup.CODICE and uo.DATA_CARICAMENTO = uosup.DATA_CARICAMENTO
 WHERE uo.DATA_CARICAMENTO = ? 
	