merge into DMALM_WORKITEM_ASSIGNEES tg using
	(select DMALM_WORKITEM_FK, DMALM_USER_FK, CD_WORKITEM, ID_USER, DATA_CARICAMENTO, ID_REPOSITORY, WORKITEM_TYPE, DMALM_WORKITEM_ASSIGNEE_PK 
	from (select 
	'SIRE' as ID_REPOSITORY,
	t.DMALM_PK as DMALM_WORKITEM_FK,
	u.DMALM_USER_PK as DMALM_USER_FK,
	t.CODICE as CD_WORKITEM,
	u.ID_USER as ID_USER,
	t.TYPE as WORKITEM_TYPE,
	wiassire.DATA_CARICAMENTO as DATA_CARICAMENTO,
	wiassire.WORKITEM_USER_ASSIGNED_PK as DMALM_WORKITEM_ASSIGNEE_PK 
	from DMALM_SIRE_HISTORY_WORKUSERASS wiassire 
	left join TOTAL t 
	on wiassire.FK_WORKITEM = t.STG_PK
	left join DMALM_SIRE_HISTORY_USER hu 
	on wiassire.FK_USER = hu.C_PK
	left join DMALM_USER u on u.ID_USER=hu.C_ID
	left join DMALM_SIRE_HISTORY_REVISION r on to_char(hu.C_REV) = r.C_NAME
	where hu.C_PK is not null and t.STG_PK is not null
	and u.ID_REPOSITORY = 'SIRE'
	and r.C_CREATED between u.DT_INIZIO_VALIDITA and u.DT_FINE_VALIDITA
	union  ALL  
	select 
	'SISS' as ID_REPOSITORY,
	t.DMALM_PK as DMALM_WORKITEM_FK,
	u.DMALM_USER_PK as DMALM_USER_FK,
	t.CODICE as CD_WORKITEM,
	u.ID_USER as ID_USER,
	t.TYPE as WORKITEM_TYPE,
	wiassiss.DATA_CARICAMENTO as DATA_CARICAMENTO,
	wiassiss.SISS_HISTORY_WORKUSERASS_PK as DMALM_WORKITEM_ASSIGNEE_PK 
	from DMALM_SISS_HISTORY_WORKUSERASS wiassiss 
	left join TOTAL t 
	on wiassiss.FK_WORKITEM = t.STG_PK
	left join DMALM_SISS_HISTORY_USER hu 
	on wiassiss.FK_USER = hu.C_PK
	left join DMALM_USER u on u.ID_USER=hu.C_ID
	left join DMALM_SISS_HISTORY_REVISION r on to_char(hu.C_REV) = r.C_NAME
	where hu.C_PK is not null and t.STG_PK is not null
	and u.ID_REPOSITORY = 'SISS' 
	and r.C_CREATED between u.DT_INIZIO_VALIDITA and u.DT_FINE_VALIDITA)
	) stg on (stg.DMALM_WORKITEM_FK=tg.DMALM_WORKITEM_FK and  stg.DMALM_USER_FK=tg.DMALM_USER_FK)
	WHEN NOT MATCHED THEN
    INSERT (tg.DMALM_WORKITEM_FK, tg.DMALM_USER_FK, tg.CD_WORKITEM, tg.ID_USER, tg.DATA_CARICAMENTO, tg.DMALM_WORKITEM_ASSIGNEE_PK, tg.ID_REPOSITORY, tg.WORKITEM_TYPE) VALUES (stg.DMALM_WORKITEM_FK, stg.DMALM_USER_FK, stg.CD_WORKITEM, stg.ID_USER, stg.DATA_CARICAMENTO, stg.DMALM_WORKITEM_ASSIGNEE_PK, stg.ID_REPOSITORY, stg.WORKITEM_TYPE) 
